// Generated by Susan from CodegenOMSIC_Equations.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use openmodelica_backend_types::BackendDAE;
use openmodelica_codegen::CodegenUtilSimulation;
use openmodelica_codegen_cfunctions::CodegenCFunctions;
use openmodelica_codegen_util::CodegenUtil;
use openmodelica_frontend_base::ComponentReference;
use openmodelica_frontend_types::DAE;
use openmodelica_simcode_types::SimCode;
use openmodelica_simcode_types::SimCodeFunction;
use openmodelica_tpl::Tpl;
use openmodelica_util_datatypes_basic::List;

pub fn equationFunctionPrototypes(
    mut txt: Tpl::Text,
    a_eq: &metamodelica::Ref<SimCode::SimEqSystem>,
    a_modelNamePrefixStr: &ArcStr,
) -> Result<Tpl::Text> {
    let mut l_ix;
    let mut out_txt;
    l_ix = CodegenUtilSimulation::equationIndex((*Tpl::emptyTxt).clone(), a_eq)?;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING {
            value: literal!("void "),
        }),
    )?;
    out_txt = CodegenUtil::symbolName(out_txt, a_modelNamePrefixStr, &literal!("eqFunction"))?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }),
    )?;
    out_txt = Tpl::writeText(out_txt, l_ix)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING {
            value: literal!("(Data_Struct_something* data, Data_Struct_something* threadData);"),
        }),
    )?;
    out_txt = Tpl::writeTok(out_txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
    Ok(out_txt)
}

fn fun_51(mut in_txt: Tpl::Text, in_a_eq: &metamodelica::Ref<SimCode::SimEqSystem>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_eq {
        Deref @ SimCode::SimEqSystem::SES_RESIDUAL { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("resFunction") }))?;
            Ok(txt)
        }
        Deref @ SimCode::SimEqSystem::SES_ALGEBRAIC_SYSTEM { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("algSystFunction") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("eqFunction") }))?;
            Ok(txt)
        }
        _ => Err("fun_51: no case matched"),
    } }
}

fn fun_52(mut in_txt: Tpl::Text, in_a_eq: &metamodelica::Ref<SimCode::SimEqSystem>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_eq {
        Deref @ SimCode::SimEqSystem::SES_RESIDUAL { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("struct omsi_function_t* this_function, const omsi_values* model_vars_and_params, void* data") }))?;
            Ok(txt)
        }
        Deref @ SimCode::SimEqSystem::SES_ALGEBRAIC_SYSTEM { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("struct omsi_function_t* this_function, const omsi_values* model_vars_and_params") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("struct omsi_function_t* this_function, const omsi_values* model_vars_and_params") }))?;
            Ok(txt)
        }
        _ => Err("fun_52: no case matched"),
    } }
}

fn fun_53(mut in_txt: Tpl::Text, in_a_eq: &metamodelica::Ref<SimCode::SimEqSystem>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_eq {
        Deref @ SimCode::SimEqSystem::SES_RESIDUAL { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("omsi_real* res = (omsi_real*) data;") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_53: no case matched"),
    } }
}

fn fun_54(mut in_txt: Tpl::Text, mut in_mArg: bool, mut in_a_varDecls: Tpl::Text) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            let mut a_varDecls = in_a_varDecls;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("/* Variables */\n") }))?;
            txt = Tpl::writeText(txt, a_varDecls)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_54: no case matched"),
    } }
}

pub fn generateEquationFunction(
    mut txt: Tpl::Text,
    a_eq: &metamodelica::Ref<SimCode::SimEqSystem>,
    a_modelNamePrefixStr: &ArcStr,
    a_modelFunctionnamePrefixStr: &ArcStr,
    a_context: &SimCodeFunction::Context,
    mut a_functionPrototypes: Tpl::Text,
) -> Result<(Tpl::Text, Tpl::Text)> {
    let mut l_ix;
    let mut ret_2;
    let mut l_equationInfos;
    let mut l_varDecls;
    let mut l_varFrees;
    let mut l_auxFunction;
    let mut l_equationCode;
    let mut l_funcName;
    let mut l_funcArguments;
    let mut l_dataCast;
    let mut out_a_functionPrototypes;
    let mut out_txt;
    let mut ret_10;
    l_ix = CodegenUtilSimulation::equationIndex((*Tpl::emptyTxt).clone(), a_eq)?;
    ret_2 = List::fill(a_eq.clone(), 1);
    l_equationInfos = CodegenUtilSimulation::dumpEqs((*Tpl::emptyTxt).clone(), &ret_2)?;
    l_varDecls = (*Tpl::emptyTxt).clone();
    l_varFrees = (*Tpl::emptyTxt).clone();
    l_auxFunction = (*Tpl::emptyTxt).clone();
    (l_equationCode, l_varDecls, l_varFrees, l_auxFunction) = equationCStr(
        (*Tpl::emptyTxt).clone(),
        a_eq,
        l_varDecls,
        l_varFrees,
        l_auxFunction,
        a_context,
    )?;
    l_funcName = fun_51((*Tpl::emptyTxt).clone(), a_eq)?;
    l_funcArguments = fun_52((*Tpl::emptyTxt).clone(), a_eq)?;
    l_dataCast = fun_53((*Tpl::emptyTxt).clone(), a_eq)?;
    out_a_functionPrototypes = Tpl::writeTok(
        a_functionPrototypes,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING {
            value: literal!("void "),
        }),
    )?;
    out_a_functionPrototypes = CodegenUtil::symbolName(
        out_a_functionPrototypes,
        a_modelNamePrefixStr,
        &Tpl::textString(l_funcName.clone())?,
    )?;
    out_a_functionPrototypes = Tpl::writeTok(
        out_a_functionPrototypes,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }),
    )?;
    out_a_functionPrototypes = Tpl::writeText(out_a_functionPrototypes, l_ix.clone())?;
    out_a_functionPrototypes = Tpl::writeTok(
        out_a_functionPrototypes,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }),
    )?;
    out_a_functionPrototypes = Tpl::writeText(out_a_functionPrototypes, l_funcArguments.clone())?;
    out_a_functionPrototypes = Tpl::writeTok(
        out_a_functionPrototypes,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(");") }),
    )?;
    out_a_functionPrototypes = Tpl::writeTok(
        out_a_functionPrototypes,
        metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
    )?;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("/*\n") }),
    )?;
    out_txt = Tpl::writeText(out_txt, l_equationInfos)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("*/\n") }),
    )?;
    out_txt = Tpl::pushBlock(out_txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING {
            value: literal!("void "),
        }),
    )?;
    out_txt = CodegenUtil::symbolName(out_txt, a_modelNamePrefixStr, &Tpl::textString(l_funcName)?)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }),
    )?;
    out_txt = Tpl::writeText(out_txt, l_ix)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }),
    )?;
    out_txt = Tpl::writeText(out_txt, l_funcArguments)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("){\n") }),
    )?;
    out_txt = Tpl::pushBlock(out_txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
    out_txt = Tpl::writeText(out_txt, l_dataCast)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(out_txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
    ret_10 = stringEq(&Tpl::textString(l_varDecls.clone())?, &literal!(""));
    out_txt = fun_54(out_txt, ret_10, l_varDecls)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeText(out_txt, l_auxFunction)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeText(out_txt, l_equationCode)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::popBlock(out_txt)?;
    out_txt = Tpl::popBlock(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }),
    )?;
    out_txt = Tpl::writeTok(out_txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
    Ok((out_txt, out_a_functionPrototypes))
}

fn fun_56(
    mut in_txt: Tpl::Text,
    in_a_eq: &metamodelica::Ref<SimCode::SimEqSystem>,
    mut in_a_auxFunction: Tpl::Text,
    mut in_a_varFrees: Tpl::Text,
    mut in_a_varDecls: Tpl::Text,
    mut in_a_preExp: Tpl::Text,
    in_a_context: &SimCodeFunction::Context,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_eq, in_a_context) {
        (Deref @ SimCode::SimEqSystem::SES_SIMPLE_ASSIGN { cref: i_cref, exp: i_exp, .. }, a_context) => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            let mut a_preExp = in_a_preExp;
            let mut l_crefStr;
            let mut l_expPart;
            l_crefStr = CodegenCFunctions::crefOMSI((*Tpl::emptyTxt).clone(), i_cref, a_context)?;
            (l_expPart, a_preExp, a_varDecls, a_varFrees, a_auxFunction) = CodegenCFunctions::daeExp((*Tpl::emptyTxt).clone(), i_exp, a_context, a_preExp, a_varDecls, a_varFrees, a_auxFunction)?;
            txt = Tpl::writeText(txt, a_preExp.clone())?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeText(txt, l_crefStr)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" = ") }))?;
            txt = Tpl::writeText(txt, l_expPart)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls, a_preExp))
        }
        (Deref @ SimCode::SimEqSystem::SES_RESIDUAL { exp: i_exp, .. }, a_context) => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            let mut a_preExp = in_a_preExp;
            let mut l_expPart;
            (l_expPart, a_preExp, a_varDecls, a_varFrees, a_auxFunction) = CodegenCFunctions::daeExp((*Tpl::emptyTxt).clone(), i_exp, a_context, a_preExp, a_varDecls, a_varFrees, a_auxFunction)?;
            txt = Tpl::writeText(txt, a_preExp.clone())?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("*res = ") }))?;
            txt = Tpl::writeText(txt, l_expPart)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls, a_preExp))
        }
        (i_eq @ Deref @ SimCode::SimEqSystem::SES_WHEN { .. }, a_context) => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            let mut a_preExp = in_a_preExp;
            let mut l_whenEq;
            (l_whenEq, a_varDecls, a_varFrees, a_auxFunction) = equationWhen((*Tpl::emptyTxt).clone(), i_eq, a_context, a_varDecls, a_varFrees, a_auxFunction)?;
            txt = Tpl::writeText(txt, l_whenEq)?;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls, a_preExp))
        }
        (_, _) => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            let mut a_preExp = in_a_preExp;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("NOT IMPLEMENTED YET Error in function equationCStr in template CodegenOMSIC_Equations") }))?;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls, a_preExp))
        }
        _ => Err("fun_56: no case matched"),
    } }
}

pub fn equationCStr(
    mut txt: Tpl::Text,
    a_eq: &metamodelica::Ref<SimCode::SimEqSystem>,
    mut a_varDecls: Tpl::Text,
    mut a_varFrees: Tpl::Text,
    mut a_auxFunction: Tpl::Text,
    a_context: &SimCodeFunction::Context,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    let mut l_preExp;
    let mut out_txt;
    let mut out_a_auxFunction;
    let mut out_a_varFrees;
    let mut out_a_varDecls;
    l_preExp = (*Tpl::emptyTxt).clone();
    (out_txt, out_a_auxFunction, out_a_varFrees, out_a_varDecls, l_preExp) =
        fun_56(txt, a_eq, a_auxFunction, a_varFrees, a_varDecls, l_preExp, a_context)?;
    Ok((out_txt, out_a_varDecls, out_a_varFrees, out_a_auxFunction))
}

fn fun_58(
    mut in_txt: Tpl::Text,
    in_a_eq: &metamodelica::Ref<SimCode::SimEqSystem>,
    in_a_modelNamePrefixStr: &ArcStr,
    in_a_input: &ArcStr,
    in_a_omsiName: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_eq, in_a_modelNamePrefixStr, in_a_input, in_a_omsiName) {
        (Deref @ SimCode::SimEqSystem::SES_SIMPLE_ASSIGN { index: i_index, .. }, a_modelNamePrefixStr, a_input, _) => {
            let mut txt = in_txt;
            let mut l_i;
            l_i = Tpl::writeStr((*Tpl::emptyTxt).clone(), intString(*i_index))?;
            txt = CodegenUtil::symbolName(txt, a_modelNamePrefixStr, &literal!("eqFunction"))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeText(txt, l_i)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeStr(txt, a_input.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(");") }))?;
            Ok(txt)
        }
        (Deref @ SimCode::SimEqSystem::SES_WHEN { index: i_index, .. }, a_modelNamePrefixStr, a_input, _) => {
            let mut txt = in_txt;
            let mut l_i;
            l_i = Tpl::writeStr((*Tpl::emptyTxt).clone(), intString(*i_index))?;
            txt = CodegenUtil::symbolName(txt, a_modelNamePrefixStr, &literal!("eqFunction"))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeText(txt, l_i)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeStr(txt, a_input.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(");") }))?;
            Ok(txt)
        }
        (Deref @ SimCode::SimEqSystem::SES_RESIDUAL { index: i_index, .. }, a_modelNamePrefixStr, a_input, _) => {
            let mut txt = in_txt;
            txt = CodegenUtil::symbolName(txt, a_modelNamePrefixStr, &literal!("resFunction"))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(*i_index))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeStr(txt, a_input.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(");") }))?;
            Ok(txt)
        }
        (Deref @ SimCode::SimEqSystem::SES_ALGEBRAIC_SYSTEM { algSysIndex: i_algSysIndex, .. }, a_modelNamePrefixStr, a_input, a_omsiName) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("new_status = ") }))?;
            txt = CodegenUtil::symbolName(txt, a_modelNamePrefixStr, a_omsiName)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_algSystFunction_") }))?;
            txt = Tpl::writeStr(txt, intString(*i_algSysIndex))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeStr(txt, a_input.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(");\n"), literal!("status = (new_status==omsi_ok && status==omsi_ok) ? omsi_ok:new_status;")], lastHasNewLine: false }))?;
            Ok(txt)
        }
        (_, _, _, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("/* equationCall not implemented yet */") }))?;
            Ok(txt)
        }
        _ => Err("fun_58: no case matched"),
    } }
}

pub fn equationCall(
    mut txt: Tpl::Text,
    a_eq: &metamodelica::Ref<SimCode::SimEqSystem>,
    a_modelNamePrefixStr: &ArcStr,
    a_modelFunctionnamePrefixStr: &ArcStr,
    a_input: &ArcStr,
    a_omsiName: &ArcStr,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = fun_58(txt, a_eq, a_modelNamePrefixStr, a_input, a_omsiName)?;
    Ok(out_txt)
}

fn lm_60(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<SimCode::OMSIFunction>>,
) -> Result<Tpl::Text> {
    for lstElt_60 in items {
        ::match_deref::match_deref! { match lstElt_60 {
            i_col => {
                let mut l_columnsString;
                l_columnsString = generateMatrixColumnInitialization((*Tpl::emptyTxt).clone(), i_col)?;
            }
            _ => return Err("lm_60: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_61(
    mut in_txt: Tpl::Text,
    in_a_matrix: &Option<metamodelica::Ref<SimCode::DerivativeMatrix>>,
    mut in_a_columnsString: Tpl::Text,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_matrix {
        Some(Deref @ SimCode::DerivativeMatrix { columns: i_m_columns, .. }) => {
            let mut txt = in_txt;
            let mut a_columnsString = in_a_columnsString;
            let mut l_0__;
            l_0__ = lm_60((*Tpl::emptyTxt).clone(), i_m_columns)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            txt = Tpl::writeText(txt, a_columnsString)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_61: no case matched"),
    } }
}

pub fn generateMatrixInitialization(
    mut txt: Tpl::Text,
    a_matrix: &Option<metamodelica::Ref<SimCode::DerivativeMatrix>>,
) -> Result<Tpl::Text> {
    let mut l_columnsString;
    let mut out_txt;
    l_columnsString = (*Tpl::emptyTxt).clone();
    out_txt = fun_61(txt, a_matrix, l_columnsString)?;
    Ok(out_txt)
}

fn lm_63(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<SimCode::SimEqSystem>>,
    a_omsiFunction_context: &SimCodeFunction::Context,
    mut a_auxFunction: Tpl::Text,
    mut a_varFrees: Tpl::Text,
    mut a_varDecls: Tpl::Text,
    mut a_body: Tpl::Text,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    for lstElt_63 in items {
        ::match_deref::match_deref! { match lstElt_63 {
            i_eq => {
                (a_body, a_varDecls, a_varFrees, a_auxFunction) = equationCStr(a_body, i_eq, a_varDecls, a_varFrees, a_auxFunction, a_omsiFunction_context)?;
            }
            _ => return Err("lm_63: no case matched"),
        } }
    }
    Ok((txt, a_auxFunction, a_varFrees, a_varDecls, a_body))
}

fn fun_64(
    mut in_txt: Tpl::Text,
    in_a_column: &metamodelica::Ref<SimCode::OMSIFunction>,
    mut in_a_auxFunction: Tpl::Text,
    mut in_a_varFrees: Tpl::Text,
    mut in_a_varDecls: Tpl::Text,
    mut in_a_body: Tpl::Text,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match in_a_column {
        Deref @ SimCode::OMSIFunction { equations: i_equations, context: i_omsiFunction_context, .. } => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            let mut a_body = in_a_body;
            let mut l_0__;
            (l_0__, a_auxFunction, a_varFrees, a_varDecls, a_body) = lm_63((*Tpl::emptyTxt).clone(), i_equations, i_omsiFunction_context, a_auxFunction, a_varFrees, a_varDecls, a_body)?;
            txt = Tpl::writeText(txt, a_body.clone())?;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls, a_body))
        }
        _ => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            let mut a_body = in_a_body;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls, a_body))
        }
        _ => Err("fun_64: no case matched"),
    } }
}

pub fn generateMatrixColumnInitialization(
    mut txt: Tpl::Text,
    a_column: &metamodelica::Ref<SimCode::OMSIFunction>,
) -> Result<Tpl::Text> {
    let mut l_varDecls;
    let mut l_varFrees;
    let mut l_auxFunction;
    let mut l_body;
    let mut out_txt;
    l_varDecls = (*Tpl::emptyTxt).clone();
    l_varFrees = (*Tpl::emptyTxt).clone();
    l_auxFunction = (*Tpl::emptyTxt).clone();
    l_body = (*Tpl::emptyTxt).clone();
    (out_txt, l_auxFunction, l_varFrees, l_varDecls, l_body) =
        fun_64(txt, a_column, l_auxFunction, l_varFrees, l_varDecls, l_body)?;
    Ok(out_txt)
}

fn lm_66(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<SimCode::OMSIFunction>>,
    a_omsiName: &ArcStr,
    mut a_functionPrototypes: Tpl::Text,
    a_index: &ArcStr,
    a_modelName: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text)> {
    for lstElt_66 in items {
        ::match_deref::match_deref! { match lstElt_66 {
            i_col => {
                (txt, a_functionPrototypes) = generateDereivativeMatrixColumnFunction(txt, i_col, a_modelName, a_index, a_functionPrototypes)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
                (txt, a_functionPrototypes) = generateDereivativeMatrixColumnCall(txt, i_col, a_modelName, a_index, a_functionPrototypes, a_omsiName)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_66: no case matched"),
        } }
    }
    Ok((txt, a_functionPrototypes))
}

fn fun_67(
    mut in_txt: Tpl::Text,
    in_a_matrix: &Option<metamodelica::Ref<SimCode::DerivativeMatrix>>,
    in_a_omsiName: &ArcStr,
    mut in_a_functionPrototypes: Tpl::Text,
    in_a_index: &ArcStr,
    in_a_modelName: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_matrix, in_a_omsiName, in_a_index, in_a_modelName) {
        (Some(Deref @ SimCode::DerivativeMatrix { columns: i_m_columns, .. }), a_omsiName, a_index, a_modelName) => {
            let mut txt = in_txt;
            let mut a_functionPrototypes = in_a_functionPrototypes;
            let mut l_columnsString;
            l_columnsString = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\n"), literal!("\n")], lastHasNewLine: true })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            (l_columnsString, a_functionPrototypes) = lm_66(l_columnsString, i_m_columns, a_omsiName, a_functionPrototypes, a_index, a_modelName)?;
            l_columnsString = Tpl::popIter(l_columnsString)?;
            txt = Tpl::writeText(txt, l_columnsString)?;
            Ok((txt, a_functionPrototypes))
        }
        (_, _, _, _) => {
            let mut txt = in_txt;
            let mut a_functionPrototypes = in_a_functionPrototypes;
            Ok((txt, a_functionPrototypes))
        }
        _ => Err("fun_67: no case matched"),
    } }
}

pub fn generateDerivativeMatrix(
    mut txt: Tpl::Text,
    a_matrix: &Option<metamodelica::Ref<SimCode::DerivativeMatrix>>,
    a_modelName: &ArcStr,
    a_index: &ArcStr,
    mut a_functionPrototypes: Tpl::Text,
    a_omsiName: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text)> {
    let mut l_columnsString;
    let mut out_txt;
    let mut out_a_functionPrototypes;
    l_columnsString = (*Tpl::emptyTxt).clone();
    (out_txt, out_a_functionPrototypes) =
        fun_67(txt, a_matrix, a_omsiName, a_functionPrototypes, a_index, a_modelName)?;
    Ok((out_txt, out_a_functionPrototypes))
}

fn lm_69(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<SimCode::SimEqSystem>>,
    mut a_functionPrototypes: Tpl::Text,
    a_omsiFunction_context: &SimCodeFunction::Context,
    a_modelName: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text)> {
    for lstElt_69 in items {
        ::match_deref::match_deref! { match lstElt_69 {
            i_eq => {
                (txt, a_functionPrototypes) = generateEquationFunction(txt, i_eq, a_modelName, &literal!(""), a_omsiFunction_context, a_functionPrototypes)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_69: no case matched"),
        } }
    }
    Ok((txt, a_functionPrototypes))
}

fn fun_70(
    mut in_txt: Tpl::Text,
    in_a_column: &metamodelica::Ref<SimCode::OMSIFunction>,
    mut in_a_functionPrototypes: Tpl::Text,
    in_a_modelName: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_column, in_a_modelName) {
        (Deref @ SimCode::OMSIFunction { equations: i_equations, context: i_omsiFunction_context, .. }, a_modelName) => {
            let mut txt = in_txt;
            let mut a_functionPrototypes = in_a_functionPrototypes;
            let mut l_bodyBuffer;
            l_bodyBuffer = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            (l_bodyBuffer, a_functionPrototypes) = lm_69(l_bodyBuffer, i_equations, a_functionPrototypes, i_omsiFunction_context, a_modelName)?;
            l_bodyBuffer = Tpl::popIter(l_bodyBuffer)?;
            txt = Tpl::writeText(txt, l_bodyBuffer)?;
            Ok((txt, a_functionPrototypes))
        }
        (_, _) => {
            let mut txt = in_txt;
            let mut a_functionPrototypes = in_a_functionPrototypes;
            Ok((txt, a_functionPrototypes))
        }
        _ => Err("fun_70: no case matched"),
    } }
}

pub fn generateDereivativeMatrixColumnFunction(
    mut txt: Tpl::Text,
    a_column: &metamodelica::Ref<SimCode::OMSIFunction>,
    a_modelName: &ArcStr,
    a_index: &ArcStr,
    mut a_functionPrototypes: Tpl::Text,
) -> Result<(Tpl::Text, Tpl::Text)> {
    let mut l_bodyBuffer;
    let mut l_preExp;
    let mut l_varDecls;
    let mut l_varFrees;
    let mut l_auxFunction;
    let mut out_txt;
    let mut out_a_functionPrototypes;
    l_bodyBuffer = (*Tpl::emptyTxt).clone();
    l_preExp = (*Tpl::emptyTxt).clone();
    l_varDecls = (*Tpl::emptyTxt).clone();
    l_varFrees = (*Tpl::emptyTxt).clone();
    l_auxFunction = (*Tpl::emptyTxt).clone();
    (out_txt, out_a_functionPrototypes) = fun_70(txt, a_column, a_functionPrototypes, a_modelName)?;
    Ok((out_txt, out_a_functionPrototypes))
}

fn lm_72(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<SimCode::SimEqSystem>>,
    a_omsiName: &ArcStr,
    a_modelName: &ArcStr,
) -> Result<Tpl::Text> {
    for lstElt_72 in items {
        ::match_deref::match_deref! { match lstElt_72 {
            i_eq => {
                txt = equationCall(txt, i_eq, a_modelName, &literal!(""), &literal!("this_function, model_vars_and_params"), a_omsiName)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_72: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_73(
    mut in_txt: Tpl::Text,
    in_a_column: &metamodelica::Ref<SimCode::OMSIFunction>,
    in_a_index: &ArcStr,
    mut in_a_functionPrototypes: Tpl::Text,
    in_a_omsiName: &ArcStr,
    in_a_modelName: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_column, in_a_index, in_a_omsiName, in_a_modelName) {
        (Deref @ SimCode::OMSIFunction { equations: i_equations, .. }, a_index, a_omsiName, a_modelName) => {
            let mut txt = in_txt;
            let mut a_functionPrototypes = in_a_functionPrototypes;
            let mut l_bodyBuffer;
            l_bodyBuffer = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_bodyBuffer = lm_72(l_bodyBuffer, i_equations, a_omsiName, a_modelName)?;
            l_bodyBuffer = Tpl::popIter(l_bodyBuffer)?;
            a_functionPrototypes = Tpl::writeTok(a_functionPrototypes, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("omsi_status ") }))?;
            a_functionPrototypes = CodegenUtil::symbolName(a_functionPrototypes, a_modelName, a_omsiName)?;
            a_functionPrototypes = Tpl::writeTok(a_functionPrototypes, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_derivativeMatFunc_") }))?;
            a_functionPrototypes = Tpl::writeStr(a_functionPrototypes, a_index.clone())?;
            a_functionPrototypes = Tpl::writeTok(a_functionPrototypes, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(struct omsi_function_t* this_function, const omsi_values* model_vars_and_params, void* data);") }))?;
            a_functionPrototypes = Tpl::writeTok(a_functionPrototypes, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("/*\n"), literal!("Description something\n"), literal!("*/\n"), literal!("omsi_status ")], lastHasNewLine: false }))?;
            txt = CodegenUtil::symbolName(txt, a_modelName, a_omsiName)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_derivativeMatFunc_") }))?;
            txt = Tpl::writeStr(txt, a_index.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("(struct omsi_function_t* this_function, const omsi_values* model_vars_and_params, void* data){\n"), literal!("\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeText(txt, l_bodyBuffer)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\n"), literal!("return omsi_ok;\n")], lastHasNewLine: true }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok((txt, a_functionPrototypes))
        }
        (_, _, _, _) => {
            let mut txt = in_txt;
            let mut a_functionPrototypes = in_a_functionPrototypes;
            Ok((txt, a_functionPrototypes))
        }
        _ => Err("fun_73: no case matched"),
    } }
}

pub fn generateDereivativeMatrixColumnCall(
    mut txt: Tpl::Text,
    a_column: &metamodelica::Ref<SimCode::OMSIFunction>,
    a_modelName: &ArcStr,
    a_index: &ArcStr,
    mut a_functionPrototypes: Tpl::Text,
    a_omsiName: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text)> {
    let mut l_bodyBuffer;
    let mut l_preExp;
    let mut l_varDecls;
    let mut l_varFrees;
    let mut l_auxFunction;
    let mut out_txt;
    let mut out_a_functionPrototypes;
    l_bodyBuffer = (*Tpl::emptyTxt).clone();
    l_preExp = (*Tpl::emptyTxt).clone();
    l_varDecls = (*Tpl::emptyTxt).clone();
    l_varFrees = (*Tpl::emptyTxt).clone();
    l_auxFunction = (*Tpl::emptyTxt).clone();
    (out_txt, out_a_functionPrototypes) =
        fun_73(txt, a_column, a_index, a_functionPrototypes, a_omsiName, a_modelName)?;
    Ok((out_txt, out_a_functionPrototypes))
}

fn lm_75(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<DAE::ComponentRef>>,
    a_context: &SimCodeFunction::Context,
) -> Result<Tpl::Text> {
    for lstElt_75 in items {
        ::match_deref::match_deref! { match lstElt_75 {
            i_cr => {
                let mut ret_0;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
                txt = CodegenCFunctions::crefOMSI(txt, i_cr, a_context)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" && !") }))?;
                ret_0 = ComponentReference::crefPrefixPre(i_cr.clone());
                txt = CodegenCFunctions::crefOMSI(txt, &ret_0, a_context)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" /* edge */)") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_75: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_76(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_context: &SimCodeFunction::Context,
    in_a_conditions: &metamodelica::List<metamodelica::Ref<DAE::ComponentRef>>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_context, in_a_conditions) {
        (false, a_context, a_conditions) => {
            let mut txt = in_txt;
            txt = Tpl::pushIter(txt, metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" || ") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            txt = lm_75(txt, a_conditions, a_context)?;
            txt = Tpl::popIter(txt)?;
            Ok(txt)
        }
        (_, _, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("0") }))?;
            Ok(txt)
        }
        _ => Err("fun_76: no case matched"),
    } }
}

fn fun_77(
    mut in_txt: Tpl::Text,
    in_mArg: &metamodelica::Ref<DAE::Type>,
    mut in_a_val: Tpl::Text,
    in_a_context: &SimCodeFunction::Context,
    in_a_stateVar: &metamodelica::Ref<DAE::ComponentRef>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_context, in_a_stateVar) {
        (Deref @ DAE::Type::T_ARRAY { .. }, _, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("TODO: Implement for arrays!") }))?;
            Ok(txt)
        }
        (_, a_context, a_stateVar) => {
            let mut txt = in_txt;
            let mut a_val = in_a_val;
            txt = CodegenCFunctions::crefOMSI(txt, a_stateVar, a_context)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" = ") }))?;
            txt = Tpl::writeText(txt, a_val)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok(txt)
        }
        _ => Err("fun_77: no case matched"),
    } }
}

fn fun_78(
    mut in_txt: Tpl::Text,
    in_a_stmt: &BackendDAE::WhenOperator,
    mut in_a_auxFunction: Tpl::Text,
    mut in_a_varFrees: Tpl::Text,
    mut in_a_varDecls: Tpl::Text,
    in_a_context: &SimCodeFunction::Context,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_stmt, in_a_context) {
        (BackendDAE::WhenOperator::ASSIGN { left: Deref @ DAE::Exp::CREF { componentRef: i_left, .. }, right: i_right, .. }, a_context) => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            let mut l_preExp;
            let mut l_lhs;
            let mut l_rhs;
            l_preExp = (*Tpl::emptyTxt).clone();
            l_lhs = CodegenCFunctions::crefOMSI((*Tpl::emptyTxt).clone(), i_left, a_context)?;
            (l_rhs, l_preExp, a_varDecls, a_varFrees, a_auxFunction) = CodegenCFunctions::daeExp((*Tpl::emptyTxt).clone(), i_right, a_context, l_preExp, a_varDecls, a_varFrees, a_auxFunction)?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeText(txt, l_preExp)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeText(txt, l_lhs)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" = ") }))?;
            txt = Tpl::writeText(txt, l_rhs)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            txt = Tpl::popBlock(txt)?;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls))
        }
        (BackendDAE::WhenOperator::REINIT { stateVar: i_stateVar, value: i_value, .. }, a_context) => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            let mut l_preExp;
            let mut l_val;
            let mut ret_4;
            let mut l_lhs;
            l_preExp = (*Tpl::emptyTxt).clone();
            (l_val, l_preExp, a_varDecls, a_varFrees, a_auxFunction) = CodegenCFunctions::daeExp((*Tpl::emptyTxt).clone(), i_value, a_context, l_preExp, a_varDecls, a_varFrees, a_auxFunction)?;
            ret_4 = ComponentReference::crefTypeConsiderSubs(i_stateVar)?;
            l_lhs = fun_77((*Tpl::emptyTxt).clone(), &ret_4, l_val, a_context, i_stateVar)?;
            txt = Tpl::writeText(txt, l_preExp)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeText(txt, l_lhs)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("/* ToDo: Add some info that variable was reinitialized */") }))?;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls))
        }
        (_, _) => {
            let mut txt = in_txt;
            let mut a_auxFunction = in_a_auxFunction;
            let mut a_varFrees = in_a_varFrees;
            let mut a_varDecls = in_a_varDecls;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("TODO: when expression not supported yet") }))?;
            Ok((txt, a_auxFunction, a_varFrees, a_varDecls))
        }
        _ => Err("fun_78: no case matched"),
    } }
}

fn lm_79(
    mut txt: Tpl::Text,
    items: &metamodelica::List<BackendDAE::WhenOperator>,
    mut a_auxFunction: Tpl::Text,
    mut a_varFrees: Tpl::Text,
    mut a_varDecls: Tpl::Text,
    a_context: &SimCodeFunction::Context,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    for lstElt_79 in items {
        ::match_deref::match_deref! { match lstElt_79 {
            i_stmt => {
                (txt, a_auxFunction, a_varFrees, a_varDecls) = fun_78(txt, i_stmt, a_auxFunction, a_varFrees, a_varDecls, a_context)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_79: no case matched"),
        } }
    }
    Ok((txt, a_auxFunction, a_varFrees, a_varDecls))
}

pub fn equationWhen(
    mut in_txt: Tpl::Text,
    in_a_eq: &metamodelica::Ref<SimCode::SimEqSystem>,
    in_a_context: &SimCodeFunction::Context,
    mut in_a_varDecls: Tpl::Text,
    mut in_a_varFrees: Tpl::Text,
    mut in_a_auxFunction: Tpl::Text,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_eq, in_a_context) {
        (Deref @ SimCode::SimEqSystem::SES_WHEN { whenStmtLst: i_whenStmtLst, conditions: i_conditions, elseWhen: None, .. }, a_context) => {
            let mut txt = in_txt;
            let mut a_varDecls = in_a_varDecls;
            let mut a_varFrees = in_a_varFrees;
            let mut a_auxFunction = in_a_auxFunction;
            let mut ret_1;
            let mut l_helpIf;
            let mut l_assign;
            ret_1 = listEmpty(i_conditions.clone());
            l_helpIf = fun_76((*Tpl::emptyTxt).clone(), ret_1, a_context, i_conditions)?;
            l_assign = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            (l_assign, a_auxFunction, a_varFrees, a_varDecls) = lm_79(l_assign, i_whenStmtLst, a_auxFunction, a_varFrees, a_varDecls, a_context)?;
            l_assign = Tpl::popIter(l_assign)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("if(") }))?;
            txt = Tpl::writeText(txt, l_helpIf)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(")\n"), literal!("{\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeText(txt, l_assign)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok((txt, a_varDecls, a_varFrees, a_auxFunction))
        }
        (_, _) => {
            let mut txt = in_txt;
            let mut a_varDecls = in_a_varDecls;
            let mut a_varFrees = in_a_varFrees;
            let mut a_auxFunction = in_a_auxFunction;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("TODO: Implement elsewhen") }))?;
            Ok((txt, a_varDecls, a_varFrees, a_auxFunction))
        }
        _ => Err("equationWhen: no case matched"),
    } }
}
