// Generated by Susan from NFInstDumpTpl.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use crate::NFInstDump;
use crate::NFInstTypes;
use openmodelica_frontend_base::Expression;
use openmodelica_frontend_dump::AbsynDumpTpl;
use openmodelica_frontend_dump::ExpressionDumpTpl;
use openmodelica_frontend_inst::NFInstPrefix;
use openmodelica_frontend_types::DAE;
use openmodelica_tpl::Tpl;

pub fn dumpModel(
    mut txt: Tpl::Text,
    a_name: &ArcStr,
    a_cls: &metamodelica::Ref<NFInstTypes::Class>,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING {
            value: literal!("class "),
        }),
    )?;
    out_txt = Tpl::writeStr(out_txt, a_name.clone())?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = dumpClass(out_txt, a_cls)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING {
            value: literal!("end "),
        }),
    )?;
    out_txt = Tpl::writeStr(out_txt, a_name.clone())?;
    Ok(out_txt)
}

pub fn dumpComponent(
    mut in_txt: Tpl::Text,
    in_a_component: &metamodelica::Ref<NFInstTypes::Component>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_component {
        i_component @ Deref @ NFInstTypes::Component::UNTYPED_COMPONENT { name: i_name, binding: i_binding, baseType: i_baseType, .. } => {
            let mut txt = in_txt;
            let mut l_name__str;
            let mut l_bind__str;
            let mut l_ty__str;
            let mut ret_4;
            let mut l_dims__str;
            l_name__str = AbsynDumpTpl::dumpPath((*Tpl::emptyTxt).clone(), i_name)?;
            l_bind__str = dumpBinding((*Tpl::emptyTxt).clone(), i_binding)?;
            l_ty__str = ExpressionDumpTpl::dumpType((*Tpl::emptyTxt).clone(), i_baseType)?;
            ret_4 = NFInstDump::dumpUntypedComponentDims(i_component)?;
            l_dims__str = Tpl::writeStr((*Tpl::emptyTxt).clone(), ret_4)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("{") }))?;
            txt = Tpl::writeText(txt, l_ty__str)?;
            txt = Tpl::writeText(txt, l_dims__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("} ") }))?;
            txt = Tpl::writeText(txt, l_name__str)?;
            txt = Tpl::writeText(txt, l_bind__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Component::TYPED_COMPONENT { name: i_name, binding: i_binding, ty: i_ty, .. } => {
            let mut txt = in_txt;
            let mut l_name__str;
            let mut l_bind__str;
            let mut l_ty__str;
            l_name__str = AbsynDumpTpl::dumpPath((*Tpl::emptyTxt).clone(), i_name)?;
            l_bind__str = dumpBinding((*Tpl::emptyTxt).clone(), i_binding)?;
            l_ty__str = ExpressionDumpTpl::dumpType((*Tpl::emptyTxt).clone(), i_ty)?;
            txt = Tpl::writeText(txt, l_ty__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, l_name__str)?;
            txt = Tpl::writeText(txt, l_bind__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Component::CONDITIONAL_COMPONENT { name: i_name, .. } => {
            let mut txt = in_txt;
            let mut l_name__str;
            l_name__str = AbsynDumpTpl::dumpPath((*Tpl::emptyTxt).clone(), i_name)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("conditional ") }))?;
            txt = Tpl::writeText(txt, l_name__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Component::DELETED_COMPONENT { name: i_name, .. } => {
            let mut txt = in_txt;
            let mut l_name__str;
            l_name__str = AbsynDumpTpl::dumpPath((*Tpl::emptyTxt).clone(), i_name)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("deleted ") }))?;
            txt = Tpl::writeText(txt, l_name__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Component::OUTER_COMPONENT { innerName: Some(i_in), name: i_name, .. } => {
            let mut txt = in_txt;
            let mut l_outer__str;
            let mut l_inner__str;
            l_outer__str = AbsynDumpTpl::dumpPath((*Tpl::emptyTxt).clone(), i_name)?;
            l_inner__str = AbsynDumpTpl::dumpPath((*Tpl::emptyTxt).clone(), i_in)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("outer ") }))?;
            txt = Tpl::writeText(txt, l_outer__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -> ") }))?;
            txt = Tpl::writeText(txt, l_inner__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Component::OUTER_COMPONENT { name: i_name, .. } => {
            let mut txt = in_txt;
            let mut l_outer__str;
            l_outer__str = AbsynDumpTpl::dumpPath((*Tpl::emptyTxt).clone(), i_name)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("outer ") }))?;
            txt = Tpl::writeText(txt, l_outer__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpComponent: no case matched"),
    } }
}

fn fun_11(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        true => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            Ok(txt)
        }
        _ => Err("fun_11: no case matched"),
    } }
}

pub fn dumpElement(mut in_txt: Tpl::Text, in_a_element: &metamodelica::Ref<NFInstTypes::Element>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_element {
        Deref @ NFInstTypes::Element::ELEMENT { component: i_component, cls: i_cls, .. } => {
            let mut txt = in_txt;
            let mut l_comp__str;
            let mut l_cls__str;
            let mut ret_3;
            let mut l_sep__str;
            l_comp__str = dumpComponent((*Tpl::emptyTxt).clone(), i_component)?;
            l_cls__str = dumpClass((*Tpl::emptyTxt).clone(), i_cls)?;
            ret_3 = Tpl::isEmpty(l_cls__str.clone());
            l_sep__str = fun_11((*Tpl::emptyTxt).clone(), ret_3)?;
            txt = Tpl::writeText(txt, l_comp__str)?;
            txt = Tpl::writeText(txt, l_sep__str)?;
            txt = Tpl::writeText(txt, l_cls__str)?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Element::CONDITIONAL_ELEMENT { component: i_component, .. } => {
            let mut txt = in_txt;
            let mut l_comp__str;
            l_comp__str = dumpComponent((*Tpl::emptyTxt).clone(), i_component)?;
            txt = Tpl::writeText(txt, l_comp__str)?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Element::EXTENDED_ELEMENTS { cls: i_cls, .. } => {
            let mut txt = in_txt;
            let mut l_cls__str;
            l_cls__str = dumpClass((*Tpl::emptyTxt).clone(), i_cls)?;
            txt = Tpl::writeText(txt, l_cls__str)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpElement: no case matched"),
    } }
}

fn lm_13(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<NFInstTypes::Element>>) -> Result<Tpl::Text> {
    for lstElt_13 in items {
        ::match_deref::match_deref! { match lstElt_13 {
            i_comp => {
                txt = dumpElement(txt, i_comp)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_13: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_14(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<NFInstTypes::Equation>>,
) -> Result<Tpl::Text> {
    for lstElt_14 in items {
        ::match_deref::match_deref! { match lstElt_14 {
            i_ieq => {
                txt = dumpEquation(txt, i_ieq)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_14: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_15(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<NFInstTypes::Equation>>,
) -> Result<Tpl::Text> {
    for lstElt_15 in items {
        ::match_deref::match_deref! { match lstElt_15 {
            i_eq => {
                txt = dumpEquation(txt, i_eq)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_15: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_16(mut in_txt: Tpl::Text, mut in_mArg: bool, mut in_a_comp__str: Tpl::Text) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        true => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut a_comp__str = in_a_comp__str;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeText(txt, a_comp__str)?;
            txt = Tpl::popBlock(txt)?;
            Ok(txt)
        }
        _ => Err("fun_16: no case matched"),
    } }
}

fn fun_17(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        true => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("end equation;") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_17: no case matched"),
    } }
}

fn fun_18(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    mut in_a_eq__str: Tpl::Text,
    mut in_a_ieq__str: Tpl::Text,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        true => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut a_eq__str = in_a_eq__str;
            let mut a_ieq__str = in_a_ieq__str;
            let mut ret_0;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\n"), literal!("initial equation\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeText(txt, a_ieq__str)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            ret_0 = Tpl::isEmpty(a_eq__str);
            txt = fun_17(txt, ret_0)?;
            Ok(txt)
        }
        _ => Err("fun_18: no case matched"),
    } }
}

fn fun_19(mut in_txt: Tpl::Text, mut in_mArg: bool, mut in_a_eq__str: Tpl::Text) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        true => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut a_eq__str = in_a_eq__str;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\n"), literal!("equation\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeText(txt, a_eq__str)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("end equation;") }))?;
            Ok(txt)
        }
        _ => Err("fun_19: no case matched"),
    } }
}

pub fn dumpClass(mut in_txt: Tpl::Text, in_a_cls: &metamodelica::Ref<NFInstTypes::Class>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_cls {
        Deref @ NFInstTypes::Class::COMPLEX_CLASS { components: i_components, initialEquations: i_initialEquations, equations: i_equations, .. } => {
            let mut txt = in_txt;
            let mut l_comp__str;
            let mut l_ieq__str;
            let mut l_eq__str;
            let mut ret_4;
            let mut l_comp__seq__str;
            let mut ret_6;
            let mut l_ieq__seq__str;
            let mut ret_8;
            let mut l_eq__seq__str;
            l_comp__str = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_comp__str = lm_13(l_comp__str, i_components)?;
            l_comp__str = Tpl::popIter(l_comp__str)?;
            l_ieq__str = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_ieq__str = lm_14(l_ieq__str, i_initialEquations)?;
            l_ieq__str = Tpl::popIter(l_ieq__str)?;
            l_eq__str = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_eq__str = lm_15(l_eq__str, i_equations)?;
            l_eq__str = Tpl::popIter(l_eq__str)?;
            ret_4 = Tpl::isEmpty(l_comp__str.clone());
            l_comp__seq__str = fun_16((*Tpl::emptyTxt).clone(), ret_4, l_comp__str)?;
            ret_6 = Tpl::isEmpty(l_ieq__str.clone());
            l_ieq__seq__str = fun_18((*Tpl::emptyTxt).clone(), ret_6, l_eq__str.clone(), l_ieq__str)?;
            ret_8 = Tpl::isEmpty(l_eq__str.clone());
            l_eq__seq__str = fun_19((*Tpl::emptyTxt).clone(), ret_8, l_eq__str)?;
            txt = Tpl::writeText(txt, l_comp__seq__str)?;
            txt = Tpl::writeText(txt, l_ieq__seq__str)?;
            txt = Tpl::writeText(txt, l_eq__seq__str)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpClass: no case matched"),
    } }
}

pub fn dumpExp(mut txt: Tpl::Text, a_exp: &metamodelica::Ref<DAE::Exp>) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = ExpressionDumpTpl::dumpExp(txt, a_exp, &literal!("\""))?;
    Ok(out_txt)
}

fn fun_22(mut in_txt: Tpl::Text, in_a_range: &Option<metamodelica::Ref<DAE::Exp>>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_range {
        Some(i_range__exp) => {
            let mut txt = in_txt;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("in ") }))?;
            txt = dumpExp(txt, i_range__exp)?;
            txt = Tpl::popBlock(txt)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_22: no case matched"),
    } }
}

fn lm_23(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<NFInstTypes::Equation>>,
) -> Result<Tpl::Text> {
    for lstElt_23 in items {
        ::match_deref::match_deref! { match lstElt_23 {
            i_eq => {
                txt = dumpEquation(txt, i_eq)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_23: no case matched"),
        } }
    }
    Ok(txt)
}

pub fn dumpEquation(
    mut in_txt: Tpl::Text,
    in_a_equation: &metamodelica::Ref<NFInstTypes::Equation>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_equation {
        Deref @ NFInstTypes::Equation::EQUALITY_EQUATION { lhs: i_lhs, rhs: i_rhs, .. } => {
            let mut txt = in_txt;
            let mut l_lhs__str;
            let mut l_rhs__str;
            let mut ret_3;
            let mut l_lhs__ty__str;
            let mut ret_5;
            let mut l_rhs__ty__str;
            l_lhs__str = dumpExp((*Tpl::emptyTxt).clone(), i_lhs)?;
            l_rhs__str = dumpExp((*Tpl::emptyTxt).clone(), i_rhs)?;
            ret_3 = Expression::r#typeof(i_lhs.clone())?;
            l_lhs__ty__str = ExpressionDumpTpl::dumpType((*Tpl::emptyTxt).clone(), &ret_3)?;
            ret_5 = Expression::r#typeof(i_rhs.clone())?;
            l_rhs__ty__str = ExpressionDumpTpl::dumpType((*Tpl::emptyTxt).clone(), &ret_5)?;
            txt = Tpl::writeText(txt, l_lhs__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" {") }))?;
            txt = Tpl::writeText(txt, l_lhs__ty__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("} = {") }))?;
            txt = Tpl::writeText(txt, l_rhs__ty__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("} ") }))?;
            txt = Tpl::writeText(txt, l_rhs__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Equation::FOR_EQUATION { indexType: i_indexType, range: i_range, body: i_body, name: i_name, index: i_index, .. } => {
            let mut txt = in_txt;
            let mut l_ty__str;
            let mut l_range__str;
            let mut l_eql__str;
            l_ty__str = ExpressionDumpTpl::dumpType((*Tpl::emptyTxt).clone(), i_indexType)?;
            l_range__str = fun_22((*Tpl::emptyTxt).clone(), i_range)?;
            l_eql__str = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_eql__str = lm_23(l_eql__str, i_body)?;
            l_eql__str = Tpl::popIter(l_eql__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("for {") }))?;
            txt = Tpl::writeText(txt, l_ty__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("} ") }))?;
            txt = Tpl::writeStr(txt, i_name.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" /* index ") }))?;
            txt = Tpl::writeStr(txt, intString(*i_index))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" */") }))?;
            txt = Tpl::writeText(txt, l_range__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(" loop\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeText(txt, l_eql__str)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("end for;") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Equation::IF_EQUATION { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("if equation;") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Equation::ASSERT_EQUATION { condition: i_condition, message: i_message, .. } => {
            let mut txt = in_txt;
            let mut l_cond__str;
            let mut l_msg__str;
            l_cond__str = dumpExp((*Tpl::emptyTxt).clone(), i_condition)?;
            l_msg__str = dumpExp((*Tpl::emptyTxt).clone(), i_message)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("assert(") }))?;
            txt = Tpl::writeText(txt, l_cond__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(", ") }))?;
            txt = Tpl::writeText(txt, l_msg__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(");") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Equation::TERMINATE_EQUATION { message: i_message, .. } => {
            let mut txt = in_txt;
            let mut l_msg__str;
            l_msg__str = dumpExp((*Tpl::emptyTxt).clone(), i_message)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("terminate(") }))?;
            txt = Tpl::writeText(txt, l_msg__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(");") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Equation::REINIT_EQUATION { cref: i_cref, reinitExp: i_reinitExp, .. } => {
            let mut txt = in_txt;
            let mut l_cref__str;
            let mut l_exp__str;
            l_cref__str = ExpressionDumpTpl::dumpCref((*Tpl::emptyTxt).clone(), i_cref)?;
            l_exp__str = dumpExp((*Tpl::emptyTxt).clone(), i_reinitExp)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("reinit(") }))?;
            txt = Tpl::writeText(txt, l_cref__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(", ") }))?;
            txt = Tpl::writeText(txt, l_exp__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
            Ok(txt)
        }
        Deref @ NFInstTypes::Equation::NORETCALL_EQUATION { exp: i_exp, .. } => {
            let mut txt = in_txt;
            txt = dumpExp(txt, i_exp)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("dumpEquation: IMPLEMENT ME") }))?;
            Ok(txt)
        }
        _ => Err("dumpEquation: no case matched"),
    } }
}

pub fn dumpBinding(mut in_txt: Tpl::Text, in_a_binding: &NFInstTypes::Binding) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_binding {
        NFInstTypes::Binding::RAW_BINDING { bindingExp: i_aexp, .. } => {
            let mut txt = in_txt;
            let mut l_exp__str;
            l_exp__str = AbsynDumpTpl::dumpExp((*Tpl::emptyTxt).clone(), i_aexp)?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("= <RAW> ") }))?;
            txt = Tpl::writeText(txt, l_exp__str)?;
            txt = Tpl::popBlock(txt)?;
            Ok(txt)
        }
        NFInstTypes::Binding::UNTYPED_BINDING { bindingExp: i_bindingExp, .. } => {
            let mut txt = in_txt;
            let mut l_exp__str;
            l_exp__str = dumpExp((*Tpl::emptyTxt).clone(), i_bindingExp)?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("= ") }))?;
            txt = Tpl::writeText(txt, l_exp__str)?;
            txt = Tpl::popBlock(txt)?;
            Ok(txt)
        }
        NFInstTypes::Binding::TYPED_BINDING { bindingExp: i_bindingExp, bindingType: i_bindingType, .. } => {
            let mut txt = in_txt;
            let mut l_exp__str;
            let mut l_ty__str;
            l_exp__str = dumpExp((*Tpl::emptyTxt).clone(), i_bindingExp)?;
            l_ty__str = ExpressionDumpTpl::dumpType((*Tpl::emptyTxt).clone(), i_bindingType)?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("= (") }))?;
            txt = Tpl::writeText(txt, l_ty__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(") ") }))?;
            txt = Tpl::writeText(txt, l_exp__str)?;
            txt = Tpl::popBlock(txt)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpBinding: no case matched"),
    } }
}

fn fun_26(
    mut in_txt: Tpl::Text,
    in_a_dims: &metamodelica::List<metamodelica::Ref<DAE::Dimension>>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_dims {
        Deref @ metamodelica::ListNode::Nil => {
            let mut txt = in_txt;
            Ok(txt)
        }
        i_dims => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("[") }))?;
            txt = ExpressionDumpTpl::dumpDimensions(txt, i_dims)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("]") }))?;
            Ok(txt)
        }
        _ => Err("fun_26: no case matched"),
    } }
}

fn fun_27(mut in_txt: Tpl::Text, mut in_mArg: bool, mut in_a_rest__str: Tpl::Text) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        true => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut a_rest__str = in_a_rest__str;
            txt = Tpl::writeText(txt, a_rest__str)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".") }))?;
            Ok(txt)
        }
        _ => Err("fun_27: no case matched"),
    } }
}

pub fn dumpPrefix(mut in_txt: Tpl::Text, in_a_prefix: &metamodelica::Ref<NFInstPrefix::Prefix>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_prefix {
        Deref @ NFInstPrefix::Prefix::PREFIX { dims: i_dims, restPrefix: i_restPrefix, name: i_name, .. } => {
            let mut txt = in_txt;
            let mut l_dims__str;
            let mut l_rest__str;
            let mut ret_3;
            let mut l_pre__str;
            l_dims__str = fun_26((*Tpl::emptyTxt).clone(), i_dims)?;
            l_rest__str = dumpPrefix((*Tpl::emptyTxt).clone(), i_restPrefix)?;
            ret_3 = Tpl::isEmpty(l_rest__str.clone());
            l_pre__str = fun_27((*Tpl::emptyTxt).clone(), ret_3, l_rest__str)?;
            txt = Tpl::writeText(txt, l_pre__str)?;
            txt = Tpl::writeStr(txt, i_name.clone())?;
            txt = Tpl::writeText(txt, l_dims__str)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpPrefix: no case matched"),
    } }
}

pub fn dumpDimension(mut in_txt: Tpl::Text, in_a_dim: &NFInstTypes::Dimension) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_dim {
        NFInstTypes::Dimension::UNTYPED_DIMENSION { dimension: i_dimension, .. } => {
            let mut txt = in_txt;
            txt = ExpressionDumpTpl::dumpDimension(txt, i_dimension)?;
            Ok(txt)
        }
        NFInstTypes::Dimension::TYPED_DIMENSION { dimension: i_dimension, .. } => {
            let mut txt = in_txt;
            txt = ExpressionDumpTpl::dumpDimension(txt, i_dimension)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpDimension: no case matched"),
    } }
}

pub fn errorMsg(mut txt: Tpl::Text, a_errMessage: &ArcStr) -> Result<Tpl::Text> {
    let mut out_txt;
    Tpl::addTemplateError(a_errMessage.clone())?;
    out_txt = Tpl::writeStr(txt, a_errMessage.clone())?;
    Ok(out_txt)
}
