// Generated by Susan from CodegenFMU2.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use crate::CodegenFMUCommon;
use openmodelica_codegen::CodegenUtilSimulation;
use openmodelica_codegen_util::CodegenUtil;
use openmodelica_simcode_types::SimCode;
use openmodelica_simcode_types::SimCodeVar;
use openmodelica_tpl::Tpl;
use openmodelica_util::FMI;
use openmodelica_util::Flags;
use openmodelica_util::Settings;
use openmodelica_util::Util;

fn fun_50(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_sourceFiles: &metamodelica::List<ArcStr>,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_sourceFiles, in_a_simCode) {
        (false, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        (_, a_sourceFiles, a_simCode) => {
            let mut txt = in_txt;
            txt = CodegenFMUCommon::ModelExchange(txt, a_simCode, a_sourceFiles)?;
            Ok(txt)
        }
        _ => Err("fun_50: no case matched"),
    } }
}

fn fun_51(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_sourceFiles: &metamodelica::List<ArcStr>,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_sourceFiles, in_a_simCode) {
        (false, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        (_, a_sourceFiles, a_simCode) => {
            let mut txt = in_txt;
            txt = CoSimulation(txt, a_simCode, a_sourceFiles)?;
            Ok(txt)
        }
        _ => Err("fun_51: no case matched"),
    } }
}

fn fun_52(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("<LogCategories>\n"), literal!("  <Category name=\"logEvents\" />\n"), literal!("  <Category name=\"logSingularLinearSystems\" />\n"), literal!("  <Category name=\"logNonlinearSystems\" />\n"), literal!("  <Category name=\"logDynamicStateSelection\" />\n"), literal!("  <Category name=\"logStatusWarning\" />\n"), literal!("  <Category name=\"logStatusDiscard\" />\n"), literal!("  <Category name=\"logStatusError\" />\n"), literal!("  <Category name=\"logStatusFatal\" />\n"), literal!("  <Category name=\"logStatusPending\" />\n"), literal!("  <Category name=\"logAll\" />\n"), literal!("  <Category name=\"logFmi2Call\" />\n"), literal!("</LogCategories>")], lastHasNewLine: false }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("<LogCategories>\n"), literal!("  <Category name=\"logEvents\" description=\"logEvents\" />\n"), literal!("  <Category name=\"logSingularLinearSystems\" description=\"logSingularLinearSystems\" />\n"), literal!("  <Category name=\"logNonlinearSystems\" description=\"logNonlinearSystems\" />\n"), literal!("  <Category name=\"logDynamicStateSelection\" description=\"logDynamicStateSelection\" />\n"), literal!("  <Category name=\"logStatusWarning\" description=\"logStatusWarning\" />\n"), literal!("  <Category name=\"logStatusDiscard\" description=\"logStatusDiscard\" />\n"), literal!("  <Category name=\"logStatusError\" description=\"logStatusError\" />\n"), literal!("  <Category name=\"logStatusFatal\" description=\"logStatusFatal\" />\n"), literal!("  <Category name=\"logStatusPending\" description=\"logStatusPending\" />\n"), literal!("  <Category name=\"logAll\" description=\"logAll\" />\n"), literal!("  <Category name=\"logFmi2Call\" description=\"logFmi2Call\" />\n"), literal!("</LogCategories>")], lastHasNewLine: false }))?;
            Ok(txt)
        }
        _ => Err("fun_52: no case matched"),
    } }
}

pub fn fmiModelDescription(
    mut in_txt: Tpl::Text,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    in_a_guid: &ArcStr,
    in_a_FMUType: &ArcStr,
    in_a_sourceFiles: &metamodelica::List<ArcStr>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_simCode, in_a_guid, in_a_FMUType, in_a_sourceFiles) {
        (i_simCode @ Deref @ SimCode::SimCode { simulationSettingsOpt: i_simulationSettingsOpt, modelStructure: i_modelStructure, .. }, a_guid, a_FMUType, a_sourceFiles) => {
            let mut txt = in_txt;
            let mut ret_0;
            let mut ret_1;
            let mut ret_2;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<fmiModelDescription\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = fmiModelDescriptionAttributes(txt, i_simCode, a_guid)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(">\n") }))?;
            ret_0 = FMI::isFMIMEType(a_FMUType);
            txt = fun_50(txt, ret_0, a_sourceFiles, i_simCode)?;
            txt = Tpl::softNewLine(txt)?;
            ret_1 = FMI::isFMICSType(a_FMUType);
            txt = fun_51(txt, ret_1, a_sourceFiles, i_simCode)?;
            txt = Tpl::softNewLine(txt)?;
            txt = CodegenFMUCommon::UnitDefinitions(txt, i_simCode)?;
            txt = Tpl::softNewLine(txt)?;
            txt = CodegenFMUCommon::fmiTypeDefinitions(txt, i_simCode, &literal!("2.0"))?;
            txt = Tpl::softNewLine(txt)?;
            ret_2 = Flags::isSet(Flags::FMU_EXPERIMENTAL.clone())?;
            txt = fun_52(txt, ret_2)?;
            txt = Tpl::softNewLine(txt)?;
            txt = CodegenFMUCommon::DefaultExperiment(txt, i_simulationSettingsOpt, &literal!("2.0"))?;
            txt = Tpl::softNewLine(txt)?;
            txt = CodegenFMUCommon::fmiModelVariables(txt, i_simCode, &literal!("2.0"))?;
            txt = Tpl::softNewLine(txt)?;
            txt = CodegenFMUCommon::ModelStructure(txt, i_modelStructure)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</fmiModelDescription>") }))?;
            Ok(txt)
        }
        (_, _, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fmiModelDescription: no case matched"),
    } }
}

fn fun_54(mut in_txt: Tpl::Text, mut in_mArg: bool, mut in_a_author: Tpl::Text) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            let mut a_author = in_a_author;
            let mut ret_0;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("author=\"") }))?;
            ret_0 = Util::escapeModelicaStringToXmlString(Tpl::textString(a_author)?)?;
            txt = Tpl::writeStr(txt, ret_0)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_54: no case matched"),
    } }
}

fn fun_55(mut in_txt: Tpl::Text, mut in_mArg: bool, mut in_a_copyright: Tpl::Text) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            let mut a_copyright = in_a_copyright;
            let mut ret_0;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("copyright=\"") }))?;
            ret_0 = Util::escapeModelicaStringToXmlString(Tpl::textString(a_copyright)?)?;
            txt = Tpl::writeStr(txt, ret_0)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_55: no case matched"),
    } }
}

fn fun_56(mut in_txt: Tpl::Text, mut in_mArg: bool, mut in_a_license: Tpl::Text) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            let mut a_license = in_a_license;
            let mut ret_0;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("license=\"") }))?;
            ret_0 = Util::escapeModelicaStringToXmlString(Tpl::textString(a_license)?)?;
            txt = Tpl::writeStr(txt, ret_0)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_56: no case matched"),
    } }
}

pub fn fmiModelDescriptionAttributes(
    mut in_txt: Tpl::Text,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    in_a_guid: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_simCode, in_a_guid) {
        (i_simCode @ Deref @ SimCode::SimCode { modelInfo: SimCode::ModelInfo { varInfo: SimCode::VarInfo { .. }, vars: SimCodeVar::SimVars { .. }, name: i_modelInfo_name, description: i_modelInfo_description, author: i_modelInfo_author, version: i_modelInfo_version, copyright: i_modelInfo_copyright, license: i_modelInfo_license, .. }, .. }, a_guid) => {
            let mut txt = in_txt;
            let mut l_fmiVersion;
            let mut l_modelName;
            let mut l_description;
            let mut l_author;
            let mut l_version;
            let mut l_copyright;
            let mut l_license;
            let mut l_generationTool;
            let mut ret_8;
            let mut ret_10;
            let mut l_generationDateAndTime;
            let mut l_variableNamingConvention;
            let mut l_numberOfEventIndicators;
            let mut ret_13;
            let mut ret_14;
            let mut ret_15;
            let mut ret_16;
            let mut ret_17;
            let mut ret_18;
            let mut ret_19;
            let mut ret_20;
            l_fmiVersion = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("2.0") }))?;
            l_modelName = CodegenUtil::dotPath((*Tpl::emptyTxt).clone(), i_modelInfo_name)?;
            l_description = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_modelInfo_description.clone())?;
            l_author = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_modelInfo_author.clone())?;
            l_version = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_modelInfo_version.clone())?;
            l_copyright = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_modelInfo_copyright.clone())?;
            l_license = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_modelInfo_license.clone())?;
            l_generationTool = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OpenModelica Compiler ") }))?;
            ret_8 = Settings::getVersionNr();
            l_generationTool = Tpl::writeStr(l_generationTool, ret_8)?;
            ret_10 = Util::getCurrentDateTime();
            l_generationDateAndTime = CodegenFMUCommon::xsdateTime((*Tpl::emptyTxt).clone(), &ret_10)?;
            l_variableNamingConvention = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("structured") }))?;
            l_numberOfEventIndicators = CodegenFMUCommon::getNumberOfEventIndicators((*Tpl::emptyTxt).clone(), i_simCode)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("fmiVersion=\"") }))?;
            txt = Tpl::writeText(txt, l_fmiVersion)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("modelName=\"")], lastHasNewLine: false }))?;
            ret_13 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_modelName)?)?;
            txt = Tpl::writeStr(txt, ret_13)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("guid=\"{")], lastHasNewLine: false }))?;
            txt = Tpl::writeStr(txt, a_guid.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("}\"\n"), literal!("description=\"")], lastHasNewLine: false }))?;
            ret_14 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_description)?)?;
            txt = Tpl::writeStr(txt, ret_14)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("version=\"")], lastHasNewLine: false }))?;
            ret_15 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_version)?)?;
            txt = Tpl::writeStr(txt, ret_15)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("\"\n") }))?;
            ret_16 = stringEq(&Tpl::textString(l_author.clone())?, &literal!(""));
            txt = fun_54(txt, ret_16, l_author)?;
            txt = Tpl::softNewLine(txt)?;
            ret_17 = stringEq(&Tpl::textString(l_copyright.clone())?, &literal!(""));
            txt = fun_55(txt, ret_17, l_copyright)?;
            txt = Tpl::softNewLine(txt)?;
            ret_18 = stringEq(&Tpl::textString(l_license.clone())?, &literal!(""));
            txt = fun_56(txt, ret_18, l_license)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("generationTool=\"") }))?;
            ret_19 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_generationTool)?)?;
            txt = Tpl::writeStr(txt, ret_19)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("generationDateAndTime=\"")], lastHasNewLine: false }))?;
            ret_20 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_generationDateAndTime)?)?;
            txt = Tpl::writeStr(txt, ret_20)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("variableNamingConvention=\"")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_variableNamingConvention)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("numberOfEventIndicators=\"")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_numberOfEventIndicators)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fmiModelDescriptionAttributes: no case matched"),
    } }
}

fn fun_58(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("providesDirectionalDerivative=\"false\"") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("providesDirectionalDerivative=\"true\"") }))?;
            Ok(txt)
        }
        _ => Err("fun_58: no case matched"),
    } }
}

pub fn CoSimulation(
    mut in_txt: Tpl::Text,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    in_a_sourceFiles: &metamodelica::List<ArcStr>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_simCode, in_a_sourceFiles) {
        (i_simCode @ Deref @ SimCode::SimCode { .. }, a_sourceFiles) => {
            let mut txt = in_txt;
            let mut l_modelIdentifier;
            let mut ret_1;
            let mut ret_2;
            l_modelIdentifier = CodegenUtilSimulation::modelNamePrefix((*Tpl::emptyTxt).clone(), i_simCode)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<CoSimulation\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("modelIdentifier=\"") }))?;
            ret_1 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_modelIdentifier)?)?;
            txt = Tpl::writeStr(txt, ret_1)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("needsExecutionTool=\"false\"\n"), literal!("canHandleVariableCommunicationStepSize=\"true\"\n"), literal!("canInterpolateInputs=\"true\"\n"), literal!("maxOutputDerivativeOrder=\"1\"\n"), literal!("canRunAsynchronuously=\"false\"\n"), literal!("canBeInstantiatedOnlyOncePerProcess=\"false\"\n"), literal!("canNotUseMemoryManagementFunctions=\"false\"\n"), literal!("canGetAndSetFMUstate=\"true\"\n"), literal!("canSerializeFMUstate=\"true\"\n")], lastHasNewLine: true }))?;
            ret_2 = Flags::isSet(Flags::FMU_EXPERIMENTAL.clone())?;
            txt = fun_58(txt, ret_2)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(">\n") }))?;
            txt = CodegenFMUCommon::SourceFiles(txt, a_sourceFiles)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</CoSimulation>") }))?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("CoSimulation: no case matched"),
    } }
}
