// Generated by Susan from CodegenFMU1.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use crate::CodegenFMUCommon;
use openmodelica_codegen::CodegenUtilSimulation;
use openmodelica_codegen_util::CodegenUtil;
use openmodelica_simcode_types::SimCode;
use openmodelica_simcode_types::SimCodeVar;
use openmodelica_tpl::Tpl;
use openmodelica_util::FMI;
use openmodelica_util::Settings;
use openmodelica_util::Util;

fn fun_50(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = CodegenFMUCommon::Implementation(txt)?;
            Ok(txt)
        }
        _ => Err("fun_50: no case matched"),
    } }
}

pub fn fmiModelDescription(
    mut in_txt: Tpl::Text,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    in_a_guid: &ArcStr,
    in_a_FMUType: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_simCode, in_a_guid, in_a_FMUType) {
        (i_simCode @ Deref @ SimCode::SimCode { simulationSettingsOpt: i_simulationSettingsOpt, .. }, a_guid, a_FMUType) => {
            let mut txt = in_txt;
            let mut ret_0;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<fmiModelDescription\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = fmiModelDescriptionAttributes(txt, i_simCode, a_guid)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(">\n") }))?;
            txt = CodegenFMUCommon::fmiTypeDefinitions(txt, i_simCode, &literal!("1.0"))?;
            txt = Tpl::softNewLine(txt)?;
            txt = CodegenFMUCommon::DefaultExperiment(txt, i_simulationSettingsOpt, &literal!("1.0"))?;
            txt = Tpl::softNewLine(txt)?;
            txt = CodegenFMUCommon::fmiModelVariables(txt, i_simCode, &literal!("1.0"))?;
            txt = Tpl::softNewLine(txt)?;
            ret_0 = FMI::isFMICSType(a_FMUType);
            txt = fun_50(txt, ret_0)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</fmiModelDescription>") }))?;
            Ok(txt)
        }
        (_, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fmiModelDescription: no case matched"),
    } }
}

fn fun_52(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_listStates: &metamodelica::List<metamodelica::Ref<SimCodeVar::SimVar>>,
    mut in_a_vi_numStateVars: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_listStates, in_a_vi_numStateVars) {
        (false, _, a_vi_numStateVars) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(a_vi_numStateVars))?;
            Ok(txt)
        }
        (_, a_listStates, _) => {
            let mut txt = in_txt;
            txt = CodegenFMUCommon::statesnumwithDummy(txt, a_listStates)?;
            Ok(txt)
        }
        _ => Err("fun_52: no case matched"),
    } }
}

pub fn fmiModelDescriptionAttributes(
    mut in_txt: Tpl::Text,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    in_a_guid: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_simCode, in_a_guid) {
        (i_simCode @ Deref @ SimCode::SimCode { modelInfo: SimCode::ModelInfo { varInfo: SimCode::VarInfo { numStateVars: i_vi_numStateVars, .. }, vars: SimCodeVar::SimVars { stateVars: i_listStates, .. }, name: i_modelInfo_name, description: i_modelInfo_description, .. }, .. }, a_guid) => {
            let mut txt = in_txt;
            let mut l_fmiVersion;
            let mut l_modelName;
            let mut l_modelIdentifier;
            let mut l_description;
            let mut l_generationTool;
            let mut ret_5;
            let mut ret_7;
            let mut l_generationDateAndTime;
            let mut l_variableNamingConvention;
            let mut ret_10;
            let mut l_numberOfContinuousStates;
            let mut l_numberOfEventIndicators;
            let mut ret_12;
            let mut ret_13;
            let mut ret_14;
            let mut ret_15;
            l_fmiVersion = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("1.0") }))?;
            l_modelName = CodegenUtil::dotPath((*Tpl::emptyTxt).clone(), i_modelInfo_name)?;
            l_modelIdentifier = CodegenUtilSimulation::modelNamePrefix((*Tpl::emptyTxt).clone(), i_simCode)?;
            l_description = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_modelInfo_description.clone())?;
            l_generationTool = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OpenModelica Compiler ") }))?;
            ret_5 = Settings::getVersionNr();
            l_generationTool = Tpl::writeStr(l_generationTool, ret_5)?;
            ret_7 = Util::getCurrentDateTime();
            l_generationDateAndTime = CodegenFMUCommon::xsdateTime((*Tpl::emptyTxt).clone(), &ret_7)?;
            l_variableNamingConvention = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("structured") }))?;
            ret_10 = intEq(*i_vi_numStateVars, 1);
            l_numberOfContinuousStates = fun_52((*Tpl::emptyTxt).clone(), ret_10, i_listStates, *i_vi_numStateVars)?;
            l_numberOfEventIndicators = CodegenFMUCommon::getNumberOfEventIndicators((*Tpl::emptyTxt).clone(), i_simCode)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("fmiVersion=\"") }))?;
            txt = Tpl::writeText(txt, l_fmiVersion)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("modelName=\"")], lastHasNewLine: false }))?;
            ret_12 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_modelName)?)?;
            txt = Tpl::writeStr(txt, ret_12)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("modelIdentifier=\"")], lastHasNewLine: false }))?;
            ret_13 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_modelIdentifier)?)?;
            txt = Tpl::writeStr(txt, ret_13)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("guid=\"{")], lastHasNewLine: false }))?;
            txt = Tpl::writeStr(txt, a_guid.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("}\"\n"), literal!("description=\"")], lastHasNewLine: false }))?;
            ret_14 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_description)?)?;
            txt = Tpl::writeStr(txt, ret_14)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("generationTool=\"")], lastHasNewLine: false }))?;
            ret_15 = Util::escapeModelicaStringToXmlString(Tpl::textString(l_generationTool)?)?;
            txt = Tpl::writeStr(txt, ret_15)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("generationDateAndTime=\"")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_generationDateAndTime)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("variableNamingConvention=\"")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_variableNamingConvention)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("numberOfContinuousStates=\"")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_numberOfContinuousStates)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\"\n"), literal!("numberOfEventIndicators=\"")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_numberOfEventIndicators)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fmiModelDescriptionAttributes: no case matched"),
    } }
}
