// Generated by Susan from CodegenUtil.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use openmodelica_ast::Absyn;
use openmodelica_backend_types::BackendDAE;
use openmodelica_frontend_base::Expression;
use openmodelica_frontend_dump::ExpressionBasics;
use openmodelica_frontend_dump::ExpressionDumpTpl;
use openmodelica_frontend_dump::TypesDump;
use openmodelica_frontend_types::DAE;
use openmodelica_simcode_types::SimCodeVar;
use openmodelica_tpl::Tpl;
use openmodelica_util::Error;
use openmodelica_util::Flags;
use openmodelica_util::System;
use openmodelica_util::Util;

pub fn symbolName(mut txt: Tpl::Text, a_modelNamePrefix: &ArcStr, a_symbolName: &ArcStr) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = Tpl::writeStr(txt, a_modelNamePrefix.clone())?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }),
    )?;
    out_txt = Tpl::writeStr(out_txt, a_symbolName.clone())?;
    Ok(out_txt)
}

fn fun_45(mut in_txt: Tpl::Text, mut in_mArg: bool, in_a_str: &ArcStr) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_str) {
        (false, a_str) => {
            let mut txt = in_txt;
            let mut ret_0;
            ret_0 = System::stringReplace(a_str.clone(), literal!("."), literal!("_"))?;
            txt = Tpl::writeStr(txt, ret_0)?;
            Ok(txt)
        }
        (_, a_str) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, a_str.clone())?;
            Ok(txt)
        }
        _ => Err("fun_45: no case matched"),
    } }
}

pub fn replaceDotAndUnderscore(mut txt: Tpl::Text, a_str: &ArcStr) -> Result<Tpl::Text> {
    let mut ret_1;
    let mut ret_2;
    let mut l_str__dots;
    let mut ret_4;
    let mut l_str__underscores;
    let mut ret_5;
    let mut out_txt;
    ret_1 = substring(a_str.clone(), 1, 1)?;
    ret_2 = stringEq(&ret_1, &literal!("'"));
    l_str__dots = fun_45((*Tpl::emptyTxt).clone(), ret_2, a_str)?;
    ret_4 = System::stringReplace(Tpl::textString(l_str__dots)?, literal!("_"), literal!("__"))?;
    l_str__underscores = Tpl::writeStr((*Tpl::emptyTxt).clone(), ret_4)?;
    ret_5 = System::unquoteIdentifier(Tpl::textString(l_str__underscores)?);
    out_txt = Tpl::writeStr(txt, ret_5)?;
    Ok(out_txt)
}

pub fn getGeneralTarget(mut in_txt: Tpl::Text, in_a_str: &ArcStr) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_str {
        Deref @ "msvc10" => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("msvc") }))?;
            Ok(txt)
        }
        Deref @ "msvc12" => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("msvc") }))?;
            Ok(txt)
        }
        Deref @ "msvc13" => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("msvc") }))?;
            Ok(txt)
        }
        Deref @ "msvc15" => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("msvc") }))?;
            Ok(txt)
        }
        Deref @ "msvc19" => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("msvc") }))?;
            Ok(txt)
        }
        i_str => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, i_str.clone())?;
            Ok(txt)
        }
        _ => Err("getGeneralTarget: no case matched"),
    } }
}

pub fn underscorePath<'a>(
    mut in_txt: Tpl::Text,
    mut in_a_path: &'a metamodelica::Ref<Absyn::Path>,
) -> Result<Tpl::Text> {
    '__tco: loop {
        break ::match_deref::match_deref! { match in_a_path {
            Deref @ Absyn::Path::QUALIFIED { name: i_name, path: i_path, .. } => {
                let mut txt = in_txt;
                txt = replaceDotAndUnderscore(txt, i_name)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
                (in_txt, in_a_path) = (txt, i_path);
                continue '__tco;
            }
            Deref @ Absyn::Path::IDENT { name: i_name, .. } => {
                let mut txt = in_txt;
                txt = replaceDotAndUnderscore(txt, i_name)?;
                Ok(txt)
            }
            Deref @ Absyn::Path::FULLYQUALIFIED { path: i_path, .. } => {
                let mut txt = in_txt;
                (in_txt, in_a_path) = (txt, i_path);
                continue '__tco;
            }
            _ => {
                let mut txt = in_txt;
                Ok(txt)
            }
            _ => Err("underscorePath: no case matched"),
        } };
    }
}

pub fn crefStr<'a>(mut in_txt: Tpl::Text, mut in_a_cr: &'a metamodelica::Ref<DAE::ComponentRef>) -> Result<Tpl::Text> {
    '__tco: loop {
        break ::match_deref::match_deref! { match in_a_cr {
            Deref @ DAE::ComponentRef::CREF_IDENT { ident: i_ident, subscriptLst: i_subscriptLst, .. } => {
                let mut txt = in_txt;
                let mut ret_0;
                ret_0 = System::unquoteIdentifier(i_ident.clone());
                txt = Tpl::writeStr(txt, ret_0)?;
                txt = subscriptsStr(txt, i_subscriptLst)?;
                Ok(txt)
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: Deref @ "$DER", componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("der(") }))?;
                txt = crefStr(txt, i_componentRef)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
                Ok(txt)
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: Deref @ "$CLKPRE", componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("previous(") }))?;
                txt = crefStr(txt, i_componentRef)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
                Ok(txt)
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: i_ident, subscriptLst: i_subscriptLst, componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                let mut ret_1;
                ret_1 = System::unquoteIdentifier(i_ident.clone());
                txt = Tpl::writeStr(txt, ret_1)?;
                txt = subscriptsStr(txt, i_subscriptLst)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("._") }))?;
                (in_txt, in_a_cr) = (txt, i_componentRef);
                continue '__tco;
            }
            _ => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("CREF_NOT_IDENT_OR_QUAL") }))?;
                Ok(txt)
            }
            _ => Err("crefStr: no case matched"),
        } };
    }
}

pub fn crefStrNoUnderscore<'a>(
    mut in_txt: Tpl::Text,
    mut in_a_cr: &'a metamodelica::Ref<DAE::ComponentRef>,
) -> Result<Tpl::Text> {
    '__tco: loop {
        break ::match_deref::match_deref! { match in_a_cr {
            Deref @ DAE::ComponentRef::CREF_IDENT { ident: i_ident, subscriptLst: i_subscriptLst, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeStr(txt, i_ident.clone())?;
                txt = subscriptsStr(txt, i_subscriptLst)?;
                Ok(txt)
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: Deref @ "$DER", componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("der(") }))?;
                txt = crefStrNoUnderscore(txt, i_componentRef)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
                Ok(txt)
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: Deref @ "$CLKPRE", componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("previous(") }))?;
                txt = crefStrNoUnderscore(txt, i_componentRef)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
                Ok(txt)
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: i_ident, subscriptLst: i_subscriptLst, componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeStr(txt, i_ident.clone())?;
                txt = subscriptsStr(txt, i_subscriptLst)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".") }))?;
                (in_txt, in_a_cr) = (txt, i_componentRef);
                continue '__tco;
            }
            _ => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("CREF_NOT_IDENT_OR_QUAL") }))?;
                Ok(txt)
            }
            _ => Err("crefStrNoUnderscore: no case matched"),
        } };
    }
}

fn lm_51(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<DAE::Subscript>>) -> Result<Tpl::Text> {
    for lstElt_51 in items {
        ::match_deref::match_deref! { match lstElt_51 {
            i_s => {
                txt = subscriptStr(txt, i_s)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_51: no case matched"),
        } }
    }
    Ok(txt)
}

pub fn subscriptsStr(
    mut in_txt: Tpl::Text,
    in_a_subscripts: &metamodelica::List<metamodelica::Ref<DAE::Subscript>>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_subscripts {
        Deref @ metamodelica::ListNode::Nil => {
            let mut txt = in_txt;
            Ok(txt)
        }
        i_subscripts => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("[") }))?;
            txt = Tpl::pushIter(txt, metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            txt = lm_51(txt, i_subscripts)?;
            txt = Tpl::popIter(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("]") }))?;
            Ok(txt)
        }
        _ => Err("subscriptsStr: no case matched"),
    } }
}

pub fn crefStrMatlabSafe<'a>(
    mut in_txt: Tpl::Text,
    mut in_a_cr: &'a metamodelica::Ref<DAE::ComponentRef>,
) -> Result<Tpl::Text> {
    '__tco: loop {
        break ::match_deref::match_deref! { match in_a_cr {
            Deref @ DAE::ComponentRef::CREF_IDENT { ident: i_ident, subscriptLst: i_subscriptLst, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeStr(txt, i_ident.clone())?;
                txt = subscriptsStrMatlabSafe(txt, i_subscriptLst)?;
                Ok(txt)
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: Deref @ "$DER", componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("der_") }))?;
                (in_txt, in_a_cr) = (txt, i_componentRef);
                continue '__tco;
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: Deref @ "$CLKPRE", componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("pre_") }))?;
                (in_txt, in_a_cr) = (txt, i_componentRef);
                continue '__tco;
            }
            Deref @ DAE::ComponentRef::CREF_QUAL { ident: i_ident, subscriptLst: i_subscriptLst, componentRef: i_componentRef, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeStr(txt, i_ident.clone())?;
                txt = subscriptsStrMatlabSafe(txt, i_subscriptLst)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
                (in_txt, in_a_cr) = (txt, i_componentRef);
                continue '__tco;
            }
            _ => {
                let mut txt = in_txt;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("CREF_NOT_IDENT_OR_QUAL") }))?;
                Ok(txt)
            }
            _ => Err("crefStrMatlabSafe: no case matched"),
        } };
    }
}

fn lm_54(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<DAE::Subscript>>) -> Result<Tpl::Text> {
    for lstElt_54 in items {
        ::match_deref::match_deref! { match lstElt_54 {
            i_s => {
                txt = subscriptStr(txt, i_s)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_54: no case matched"),
        } }
    }
    Ok(txt)
}

pub fn subscriptsStrMatlabSafe(
    mut in_txt: Tpl::Text,
    in_a_subscripts: &metamodelica::List<metamodelica::Ref<DAE::Subscript>>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_subscripts {
        Deref @ metamodelica::ListNode::Nil => {
            let mut txt = in_txt;
            Ok(txt)
        }
        i_subscripts => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::pushIter(txt, metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            txt = lm_54(txt, i_subscripts)?;
            txt = Tpl::popIter(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
            Ok(txt)
        }
        _ => Err("subscriptsStrMatlabSafe: no case matched"),
    } }
}

pub fn subscriptStr(mut in_txt: Tpl::Text, in_a_subscript: &metamodelica::Ref<DAE::Subscript>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_subscript {
        Deref @ DAE::Subscript::INDEX { exp: Deref @ DAE::Exp::ICONST { integer: i_i, .. }, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(*i_i))?;
            Ok(txt)
        }
        Deref @ DAE::Subscript::INDEX { exp: Deref @ DAE::Exp::BCONST { bool: i_i_1, .. }, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, Tpl::booleanString(*i_i_1))?;
            Ok(txt)
        }
        Deref @ DAE::Subscript::INDEX { exp: Deref @ DAE::Exp::ENUM_LITERAL { name: i_n, .. }, .. } => {
            let mut txt = in_txt;
            txt = dotPath(txt, i_n)?;
            Ok(txt)
        }
        Deref @ DAE::Subscript::INDEX { exp: i_exp @ Deref @ DAE::Exp::CREF { .. }, .. } => {
            let mut txt = in_txt;
            let mut ret_0;
            ret_0 = ExpressionBasics::printExpStr(i_exp.clone())?;
            txt = Tpl::writeStr(txt, ret_0)?;
            Ok(txt)
        }
        Deref @ DAE::Subscript::SLICE { exp: Deref @ DAE::Exp::ICONST { integer: i_i, .. }, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(*i_i))?;
            Ok(txt)
        }
        Deref @ DAE::Subscript::INDEX { exp: i_exp, .. } => {
            let mut txt = in_txt;
            let mut ret_1;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("UNKNOWN_SUBSCRIPT /* ") }))?;
            ret_1 = ExpressionBasics::printExpStr(i_exp.clone())?;
            txt = escapeCComments(txt, &ret_1)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" */") }))?;
            Ok(txt)
        }
        Deref @ DAE::Subscript::SLICE { exp: i_exp, .. } => {
            let mut txt = in_txt;
            let mut ret_2;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("UNKNOWN_SUBSCRIPT /* ") }))?;
            ret_2 = ExpressionBasics::printExpStr(i_exp.clone())?;
            txt = escapeCComments(txt, &ret_2)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" */") }))?;
            Ok(txt)
        }
        Deref @ DAE::Subscript::WHOLEDIM { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("WHOLEDIM") }))?;
            Ok(txt)
        }
        Deref @ DAE::Subscript::WHOLE_NONEXP { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("WHOLE_NONEXP") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("UNKNOWN_SUBSCRIPT") }))?;
            Ok(txt)
        }
        _ => Err("subscriptStr: no case matched"),
    } }
}

pub fn escapeCComments(mut txt: Tpl::Text, a_stringWithCComments: &ArcStr) -> Result<Tpl::Text> {
    let mut ret_0;
    let mut ret_1;
    let mut out_txt;
    ret_0 = System::stringReplace(a_stringWithCComments.clone(), literal!("/*"), literal!("(*"))?;
    ret_1 = System::stringReplace(ret_0, literal!("*/"), literal!("*)"))?;
    out_txt = Tpl::writeStr(txt, ret_1)?;
    Ok(out_txt)
}

fn fun_58(mut in_txt: Tpl::Text, mut in_mArg: bool, in_a_vName: &ArcStr) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_vName) {
        (false, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OBFUSCATED") }))?;
            Ok(txt)
        }
        (_, a_vName) => {
            let mut txt = in_txt;
            txt = escapeCComments(txt, a_vName)?;
            Ok(txt)
        }
        _ => Err("fun_58: no case matched"),
    } }
}

fn fun_59(mut in_txt: Tpl::Text, mut in_mArg: bool, in_a_vName: &ArcStr) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_vName) {
        (false, a_vName) => {
            let mut txt = in_txt;
            txt = escapeCComments(txt, a_vName)?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OBFUSCATED") }))?;
            Ok(txt)
        }
        _ => Err("fun_59: no case matched"),
    } }
}

pub fn crefCComment(
    mut in_txt: Tpl::Text,
    in_a_v: &metamodelica::Ref<SimCodeVar::SimVar>,
    in_a_vName: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_v, in_a_vName) {
        (Deref @ SimCodeVar::SimVar { isProtected: true, .. }, a_vName) => {
            let mut txt = in_txt;
            let mut ret_0;
            let mut ret_1;
            ret_0 = Flags::getConfigString((*Flags::OBFUSCATE).clone())?;
            ret_1 = stringEq(&ret_0, &literal!("none"));
            txt = fun_58(txt, ret_1, a_vName)?;
            Ok(txt)
        }
        (Deref @ SimCodeVar::SimVar { .. }, a_vName) => {
            let mut txt = in_txt;
            let mut ret_2;
            let mut ret_3;
            ret_2 = Flags::getConfigString((*Flags::OBFUSCATE).clone())?;
            ret_3 = stringEq(&ret_2, &literal!("full"));
            txt = fun_59(txt, ret_3, a_vName)?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("crefCComment: no case matched"),
    } }
}

fn fun_61(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_varKind: &BackendDAE::VarKind,
    in_a_name: &metamodelica::Ref<DAE::ComponentRef>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_varKind, in_a_name) {
        (false, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        (_, a_varKind, a_name) => {
            let mut txt = in_txt;
            let mut txt_0;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("/* ") }))?;
            txt_0 = crefStrNoUnderscore((*Tpl::emptyTxt).clone(), a_name)?;
            txt = escapeCComments(txt, &Tpl::textString(txt_0)?)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = variabilityString(txt, a_varKind)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" */") }))?;
            txt = Tpl::popBlock(txt)?;
            Ok(txt)
        }
        _ => Err("fun_61: no case matched"),
    } }
}

fn fun_62(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_varKind: &BackendDAE::VarKind,
    in_a_name: &metamodelica::Ref<DAE::ComponentRef>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_varKind, in_a_name) {
        (false, a_varKind, a_name) => {
            let mut txt = in_txt;
            let mut txt_0;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("/* ") }))?;
            txt_0 = crefStrNoUnderscore((*Tpl::emptyTxt).clone(), a_name)?;
            txt = escapeCComments(txt, &Tpl::textString(txt_0)?)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = variabilityString(txt, a_varKind)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" */") }))?;
            txt = Tpl::popBlock(txt)?;
            Ok(txt)
        }
        (_, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_62: no case matched"),
    } }
}

pub fn crefCCommentWithVariability(
    mut in_txt: Tpl::Text,
    in_a_v: &metamodelica::Ref<SimCodeVar::SimVar>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_v {
        Deref @ SimCodeVar::SimVar { isProtected: true, name: i_name, varKind: i_varKind, .. } => {
            let mut txt = in_txt;
            let mut ret_0;
            let mut ret_1;
            ret_0 = Flags::getConfigString((*Flags::OBFUSCATE).clone())?;
            ret_1 = stringEq(&ret_0, &literal!("none"));
            txt = fun_61(txt, ret_1, i_varKind, i_name)?;
            Ok(txt)
        }
        Deref @ SimCodeVar::SimVar { name: i_name, varKind: i_varKind, .. } => {
            let mut txt = in_txt;
            let mut ret_2;
            let mut ret_3;
            ret_2 = Flags::getConfigString((*Flags::OBFUSCATE).clone())?;
            ret_3 = stringEq(&ret_2, &literal!("full"));
            txt = fun_62(txt, ret_3, i_varKind, i_name)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("crefCCommentWithVariability: no case matched"),
    } }
}

pub fn escapeSingleQuoteIdent(mut txt: Tpl::Text, a_ident: &ArcStr) -> Result<Tpl::Text> {
    let mut ret_0;
    let mut ret_1;
    let mut out_txt;
    ret_0 = System::stringReplace(a_ident.clone(), literal!("\\'"), literal!("\\\\'"))?;
    ret_1 = System::stringReplace(ret_0, literal!("'"), literal!("\\'"))?;
    out_txt = Tpl::writeStr(txt, ret_1)?;
    Ok(out_txt)
}

pub fn initDefaultValXml(mut in_txt: Tpl::Text, in_a_type__: &metamodelica::Ref<DAE::Type>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_type__ {
        Deref @ DAE::Type::T_INTEGER { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("0") }))?;
            Ok(txt)
        }
        Deref @ DAE::Type::T_REAL { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("0.0") }))?;
            Ok(txt)
        }
        Deref @ DAE::Type::T_BOOL { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("false") }))?;
            Ok(txt)
        }
        Deref @ DAE::Type::T_STRING { .. } => {
            let mut txt = in_txt;
            Ok(txt)
        }
        Deref @ DAE::Type::T_ENUMERATION { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("0") }))?;
            Ok(txt)
        }
        i_type__ => {
            let mut txt = in_txt;
            let mut txt_0;
            let mut ret_0;
            txt_0 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("initial value of unknown type: ") }))?;
            ret_0 = TypesDump::unparseType(i_type__.clone())?;
            txt_0 = Tpl::writeStr(txt_0, ret_0)?;
            txt = error(txt, &Tpl::sourceInfo(literal!("CodegenUtil.tpl"), 254, 14), &Tpl::textString(txt_0)?)?;
            Ok(txt)
        }
        _ => Err("initDefaultValXml: no case matched"),
    } }
}

fn lm_66(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<DAE::Exp>>,
    a_stringQuotes: &ArcStr,
) -> Result<Tpl::Text> {
    for lstElt_66 in items {
        ::match_deref::match_deref! { match lstElt_66 {
            i_elem => {
                txt = initValXml(txt, i_elem, a_stringQuotes)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_66: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_67(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_stringQuotes: &ArcStr,
    in_a_expr: &metamodelica::Ref<DAE::Exp>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_stringQuotes, in_a_expr) {
        (false, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        (_, a_stringQuotes, a_expr) => {
            let mut txt = in_txt;
            txt = initValXml(txt, a_expr, a_stringQuotes)?;
            Ok(txt)
        }
        _ => Err("fun_67: no case matched"),
    } }
}

pub fn initValXml(
    mut in_txt: Tpl::Text,
    in_a_exp: &metamodelica::Ref<DAE::Exp>,
    in_a_stringQuotes: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_exp, in_a_stringQuotes) {
        (Deref @ DAE::Exp::ICONST { integer: i_integer, .. }, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(*i_integer))?;
            Ok(txt)
        }
        (Deref @ DAE::Exp::RCONST { real: i_real, .. }, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, realString(*i_real))?;
            Ok(txt)
        }
        (Deref @ DAE::Exp::SCONST { string: i_string, .. }, a_stringQuotes) => {
            let mut txt = in_txt;
            let mut ret_0;
            txt = Tpl::writeStr(txt, a_stringQuotes.clone())?;
            ret_0 = Util::escapeModelicaStringToXmlString(i_string.clone())?;
            txt = Tpl::writeStr(txt, ret_0)?;
            txt = Tpl::writeStr(txt, a_stringQuotes.clone())?;
            Ok(txt)
        }
        (Deref @ DAE::Exp::BCONST { bool: i_bool, .. }, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, Tpl::booleanString(*i_bool))?;
            Ok(txt)
        }
        (Deref @ DAE::Exp::ARRAY { array: i_array, .. }, a_stringQuotes) => {
            let mut txt = in_txt;
            txt = Tpl::pushIter(txt, metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            txt = lm_66(txt, i_array, a_stringQuotes)?;
            txt = Tpl::popIter(txt)?;
            Ok(txt)
        }
        (Deref @ DAE::Exp::REDUCTION { expr: i_expr, .. }, a_stringQuotes) => {
            let mut txt = in_txt;
            let mut ret_1;
            ret_1 = Expression::isSimpleLiteralValue(i_expr, true)?;
            txt = fun_67(txt, ret_1, a_stringQuotes, i_expr)?;
            Ok(txt)
        }
        (Deref @ DAE::Exp::ENUM_LITERAL { index: i_index, .. }, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(*i_index))?;
            Ok(txt)
        }
        (i_exp, _) => {
            let mut txt = in_txt;
            let mut txt_2;
            txt_2 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("initial value of unknown type: ") }))?;
            txt_2 = ExpressionDumpTpl::dumpExp(txt_2, i_exp, &literal!("\""))?;
            txt = error(txt, &Tpl::sourceInfo(literal!("CodegenUtil.tpl"), 267, 14), &Tpl::textString(txt_2)?)?;
            Ok(txt)
        }
        _ => Err("initValXml: no case matched"),
    } }
}

pub fn getVariablity(mut in_txt: Tpl::Text, in_a_varKind: &BackendDAE::VarKind) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_varKind {
        BackendDAE::VarKind::DISCRETE { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("discrete") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::PARAM { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("parameter") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::CONST { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("constant") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("continuous") }))?;
            Ok(txt)
        }
        _ => Err("getVariablity: no case matched"),
    } }
}

pub fn variabilityString(mut in_txt: Tpl::Text, in_a_varKind: &BackendDAE::VarKind) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_varKind {
        BackendDAE::VarKind::VARIABLE { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("variable") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::STATE { derName: None, index: i_index, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("STATE(") }))?;
            txt = Tpl::writeStr(txt, intString(*i_index))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::STATE { derName: Some(i_dcr), index: i_index, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("STATE(") }))?;
            txt = Tpl::writeStr(txt, intString(*i_index))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",") }))?;
            txt = crefStrNoUnderscore(txt, i_dcr)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::STATE_DER { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("STATE_DER") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::DUMMY_DER { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("DUMMY_DER") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::DUMMY_STATE { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("DUMMY_STATE") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::CLOCKED_STATE { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("CLOCKED_STATE") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::DISCRETE { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("DISCRETE") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::PARAM { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("PARAM") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::CONST { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("CONST") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::EXTOBJ { fullClassName: i_fullClassName, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("EXTOBJ: ") }))?;
            txt = dotPath(txt, i_fullClassName)?;
            Ok(txt)
        }
        BackendDAE::VarKind::JAC_VAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("JACOBIAN_VAR") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::JAC_TMP_VAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("JACOBIAN_TMP_VAR") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::SEED_VAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("SEED_VAR") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::OPT_CONSTR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OPT_CONSTR") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::OPT_FCONSTR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OPT_FCONSTR") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::OPT_INPUT_WITH_DER { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OPT_INPUT_WITH_DER") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::OPT_INPUT_DER { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OPT_INPUT_DER") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::OPT_TGRID { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OPT_TGRID") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::OPT_LOOP_INPUT { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OPT_LOOP_INPUT") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::ALG_STATE { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("ALG_STATE") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::DAE_RESIDUAL_VAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("DAE_RESIDUAL_VAR") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::DAE_AUX_VAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("DAE_AUX_VAR") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::LOOP_ITERATION { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("LOOP_ITERATION") }))?;
            Ok(txt)
        }
        BackendDAE::VarKind::LOOP_SOLVED { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("LOOP_SOLVED") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("#UNKNOWN_VARKIND") }))?;
            Ok(txt)
        }
        _ => Err("variabilityString: no case matched"),
    } }
}

pub fn getAliasVar(mut in_txt: Tpl::Text, in_a_aliasvar: &SimCodeVar::AliasVariable) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_aliasvar {
        SimCodeVar::AliasVariable::NOALIAS { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"noAlias\"") }))?;
            Ok(txt)
        }
        SimCodeVar::AliasVariable::ALIAS { varName: i_varName, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"alias\" aliasVariable=\"") }))?;
            txt = crefStrNoUnderscore(txt, i_varName)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
            Ok(txt)
        }
        SimCodeVar::AliasVariable::NEGATEDALIAS { varName: i_varName, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"negatedAlias\" aliasVariable=\"") }))?;
            txt = crefStrNoUnderscore(txt, i_varName)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"noAlias\"") }))?;
            Ok(txt)
        }
        _ => Err("getAliasVar: no case matched"),
    } }
}

pub fn dotPath<'a>(mut in_txt: Tpl::Text, mut in_a_path: &'a metamodelica::Ref<Absyn::Path>) -> Result<Tpl::Text> {
    '__tco: loop {
        break ::match_deref::match_deref! { match in_a_path {
            Deref @ Absyn::Path::QUALIFIED { name: i_name, path: i_path, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeStr(txt, i_name.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".") }))?;
                (in_txt, in_a_path) = (txt, i_path);
                continue '__tco;
            }
            Deref @ Absyn::Path::IDENT { name: i_name, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeStr(txt, i_name.clone())?;
                Ok(txt)
            }
            Deref @ Absyn::Path::FULLYQUALIFIED { path: i_path, .. } => {
                let mut txt = in_txt;
                (in_txt, in_a_path) = (txt, i_path);
                continue '__tco;
            }
            _ => {
                let mut txt = in_txt;
                Ok(txt)
            }
            _ => Err("dotPath: no case matched"),
        } };
    }
}

pub fn error(mut txt: Tpl::Text, a_srcInfo: &SourceInfo, a_errMessage: &ArcStr) -> Result<Tpl::Text> {
    let mut out_txt;
    let mut ret_0;
    Tpl::addSourceTemplateError(a_errMessage.clone(), a_srcInfo)?;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![literal!("\n"), literal!("#error \"")],
            lastHasNewLine: false,
        }),
    )?;
    ret_0 = Error::infoStr(a_srcInfo)?;
    out_txt = Tpl::writeStr(out_txt, ret_0)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }),
    )?;
    out_txt = Tpl::writeStr(out_txt, a_errMessage.clone())?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }),
    )?;
    out_txt = Tpl::writeTok(out_txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
    Ok(out_txt)
}

pub fn errorMsg(mut txt: Tpl::Text, a_errMessage: &ArcStr) -> Result<Tpl::Text> {
    let mut out_txt;
    Tpl::addTemplateError(a_errMessage.clone())?;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![literal!("\n"), literal!("#error \"")],
            lastHasNewLine: false,
        }),
    )?;
    out_txt = Tpl::writeStr(out_txt, a_errMessage.clone())?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }),
    )?;
    out_txt = Tpl::writeTok(out_txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
    Ok(out_txt)
}

fn fun_75(mut in_txt: Tpl::Text, in_a_language: &ArcStr, in_a_name: &ArcStr) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_language, in_a_name) {
        (Deref @ "BUILTIN", a_name) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, a_name.clone())?;
            Ok(txt)
        }
        (Deref @ "C", a_name) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, a_name.clone())?;
            Ok(txt)
        }
        (Deref @ "FORTRAN 77", a_name) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, a_name.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            Ok(txt)
        }
        (i_language, _) => {
            let mut txt = in_txt;
            let mut txt_0;
            txt_0 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("Unsupported external language: ") }))?;
            txt_0 = Tpl::writeStr(txt_0, i_language.clone())?;
            txt = error(txt, &Tpl::sourceInfo(literal!("CodegenUtil.tpl"), 380, 14), &Tpl::textString(txt_0)?)?;
            Ok(txt)
        }
        _ => Err("fun_75: no case matched"),
    } }
}

pub fn extFunctionName(mut txt: Tpl::Text, a_name: &ArcStr, a_language: &ArcStr) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = fun_75(txt, a_language, a_name)?;
    Ok(out_txt)
}
