// Generated by Susan from Unparsing.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use openmodelica_ast::Absyn;
use openmodelica_frontend_dump::AbsynUtil;
use openmodelica_frontend_types::DAE;
use openmodelica_frontend_types::SCode;
use openmodelica_tpl::Tpl;
use openmodelica_util::System;

fn lm_43(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<SCode::Element>>) -> Result<Tpl::Text> {
    for lstElt_43 in items {
        ::match_deref::match_deref! { match lstElt_43 {
            i_cl => {
                txt = classExternalHeader(txt, i_cl, &literal!(""))?;
            }
            _ => return Err("lm_43: no case matched"),
        } }
    }
    Ok(txt)
}

pub fn programExternalHeader(
    mut txt: Tpl::Text,
    a_program: &metamodelica::List<metamodelica::Ref<SCode::Element>>,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("/* Automatically generated header for external MetaModelica functions */\n"),
                literal!("#ifdef __cplusplus\n"),
                literal!("extern \"C\" {\n"),
                literal!("#endif\n")
            ],
            lastHasNewLine: true,
        }),
    )?;
    out_txt = lm_43(out_txt, a_program)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("#ifdef __cplusplus\n"),
                literal!("}\n"),
                literal!("#endif\n"),
                literal!("\n")
            ],
            lastHasNewLine: true,
        }),
    )?;
    Ok(out_txt)
}

fn lm_45(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<DAE::Var>>) -> Result<Tpl::Text> {
    for lstElt_45 in items {
        ::match_deref::match_deref! { match lstElt_45 {
            Deref @ DAE::Var { name: i_var_name, .. } => {
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
                txt = Tpl::writeStr(txt, i_var_name.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn fun_46(
    mut in_txt: Tpl::Text,
    in_mArg: &ArcStr,
    mut in_a_fieldsStr: Tpl::Text,
    mut in_a_nElts: Tpl::Text,
    mut in_a_omcname: Tpl::Text,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        Deref @ "0" => {
            let mut txt = in_txt;
            let mut a_omcname = in_a_omcname;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("ADD_METARECORD_DEFINITIONS const char* ") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__desc__fields[1] = {\"no fields\"};") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut a_fieldsStr = in_a_fieldsStr;
            let mut a_nElts = in_a_nElts;
            let mut a_omcname = in_a_omcname;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("ADD_METARECORD_DEFINITIONS const char* ") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__desc__fields[") }))?;
            txt = Tpl::writeText(txt, a_nElts)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("] = {") }))?;
            txt = Tpl::writeText(txt, a_fieldsStr)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("};") }))?;
            Ok(txt)
        }
        _ => Err("fun_46: no case matched"),
    } }
}

fn lm_47(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<DAE::Type>>) -> Result<Tpl::Text> {
    for lstElt_47 in items {
        ::match_deref::match_deref! { match lstElt_47 {
            Deref @ DAE::Type::T_METARECORD { fields: i_ty_fields, path: i_path, .. } => {
                let mut l_fieldsStr;
                let mut ret_2;
                let mut ret_3;
                let mut ret_4;
                let mut l_omcname;
                let mut ret_6;
                let mut l_nElts;
                let mut str_8;
                let mut l_fieldsDescription;
                let mut ret_9;
                l_fieldsStr = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_fieldsStr = lm_45(l_fieldsStr, i_ty_fields)?;
                l_fieldsStr = Tpl::popIter(l_fieldsStr)?;
                ret_2 = AbsynUtil::pathString(i_path.clone(), literal!("$"), false, false)?;
                ret_3 = System::stringReplace(ret_2, literal!("_"), literal!("__"))?;
                ret_4 = System::stringReplace(ret_3, literal!("$"), literal!("_"))?;
                l_omcname = Tpl::writeStr((*Tpl::emptyTxt).clone(), ret_4)?;
                ret_6 = listLength(i_ty_fields.clone());
                l_nElts = Tpl::writeStr((*Tpl::emptyTxt).clone(), intString(ret_6))?;
                str_8 = Tpl::textString(l_nElts.clone())?;
                l_fieldsDescription = fun_46((*Tpl::emptyTxt).clone(), &str_8, l_fieldsStr, l_nElts, l_omcname.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("#ifdef ADD_METARECORD_DEFINITIONS\n"), literal!("#ifndef ")], lastHasNewLine: false }))?;
                txt = Tpl::writeText(txt, l_omcname.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("__desc_added\n"), literal!("#define ")], lastHasNewLine: false }))?;
                txt = Tpl::writeText(txt, l_omcname.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("__desc_added\n") }))?;
                txt = Tpl::writeText(txt, l_fieldsDescription)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("ADD_METARECORD_DEFINITIONS struct record_description ") }))?;
                txt = Tpl::writeText(txt, l_omcname.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("__desc = {\n") }))?;
                txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
                txt = Tpl::writeText(txt, l_omcname.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\",\n"), literal!("\"")], lastHasNewLine: false }))?;
                ret_9 = AbsynUtil::pathString(i_path.clone(), literal!("."), false, false)?;
                txt = Tpl::writeStr(txt, ret_9)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("\",\n") }))?;
                txt = Tpl::writeText(txt, l_omcname.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("__desc__fields\n") }))?;
                txt = Tpl::popBlock(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("};\n"), literal!("#endif\n"), literal!("#else /* Only use the file as a header */\n"), literal!("extern struct record_description ")], lastHasNewLine: false }))?;
                txt = Tpl::writeText(txt, l_omcname)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("__desc;\n"), literal!("#endif")], lastHasNewLine: false }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

pub fn programExternalHeaderFromTypes(
    mut txt: Tpl::Text,
    a_tys: &metamodelica::List<metamodelica::Ref<DAE::Type>>,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("/* Automatically generated header for bootstrapping MetaModelica */\n"),
                literal!("#ifdef __cplusplus\n"),
                literal!("extern \"C\" {\n"),
                literal!("#endif\n")
            ],
            lastHasNewLine: true,
        }),
    )?;
    out_txt = Tpl::pushIter(
        out_txt,
        metamodelica::Ref::new(Tpl::IterOptions {
            startIndex0: 0,
            empty: None,
            separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)),
            alignNum: 0,
            alignOfset: 0,
            alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
            wrapWidth: 0,
            wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
        }),
    )?;
    out_txt = lm_47(out_txt, a_tys)?;
    out_txt = Tpl::popIter(out_txt)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("#ifdef __cplusplus\n"),
                literal!("}\n"),
                literal!("#endif\n"),
                literal!("\n")
            ],
            lastHasNewLine: true,
        }),
    )?;
    Ok(out_txt)
}

fn lm_49(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<SCode::Element>>,
    a_c_name: &ArcStr,
) -> Result<Tpl::Text> {
    for lstElt_49 in items {
        ::match_deref::match_deref! { match lstElt_49 {
            i_elt => {
                txt = elementExternalHeader(txt, i_elt, a_c_name)?;
            }
            _ => return Err("lm_49: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_50(mut in_txt: Tpl::Text, in_a_cl: &metamodelica::Ref<SCode::Element>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_cl {
        i_c @ Deref @ SCode::Element::CLASS { restriction: SCode::Restriction::R_METARECORD { moved: true, name: Deref @ Absyn::Path::IDENT { name: i_name, .. }, .. }, .. } => {
            let mut txt = in_txt;
            txt = elementExternalHeader(txt, i_c, i_name)?;
            Ok(txt)
        }
        Deref @ SCode::Element::CLASS { classDef: Deref @ SCode::ClassDef::PARTS { elementLst: i_p_elementLst, .. }, name: i_c_name, .. } => {
            let mut txt = in_txt;
            txt = lm_49(txt, i_p_elementLst, i_c_name)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_50: no case matched"),
    } }
}

pub fn classExternalHeader(
    mut txt: Tpl::Text,
    a_cl: &metamodelica::Ref<SCode::Element>,
    a_pack: &ArcStr,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = fun_50(txt, a_cl)?;
    Ok(out_txt)
}

pub fn pathString<'a>(mut in_txt: Tpl::Text, mut in_a_path: &'a metamodelica::Ref<Absyn::Path>) -> Result<Tpl::Text> {
    '__tco: loop {
        break ::match_deref::match_deref! { match in_a_path {
            Deref @ Absyn::Path::IDENT { name: i_name, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeStr(txt, i_name.clone())?;
                Ok(txt)
            }
            Deref @ Absyn::Path::QUALIFIED { name: i_name, path: i_path, .. } => {
                let mut txt = in_txt;
                txt = Tpl::writeStr(txt, i_name.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".") }))?;
                (in_txt, in_a_path) = (txt, i_path);
                continue '__tco;
            }
            Deref @ Absyn::Path::FULLYQUALIFIED { path: i_path, .. } => {
                let mut txt = in_txt;
                (in_txt, in_a_path) = (txt, i_path);
                continue '__tco;
            }
            _ => {
                let mut txt = in_txt;
                Ok(txt)
            }
            _ => Err("pathString: no case matched"),
        } };
    }
}

pub fn metaHelperBoxStart(mut in_txt: Tpl::Text, mut in_a_numVariables: i32) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_numVariables {
        i_numVariables @ 0 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 1 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 2 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 3 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 4 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 5 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 6 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 7 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 8 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables @ 9 => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            Ok(txt)
        }
        i_numVariables => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeStr(txt, intString(i_numVariables))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(", ") }))?;
            Ok(txt)
        }
        _ => Err("metaHelperBoxStart: no case matched"),
    } }
}

fn lm_54(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<SCode::Element>>) -> Result<Tpl::Text> {
    for lstElt_54 in items {
        ::match_deref::match_deref! { match lstElt_54 {
            Deref @ SCode::Element::COMPONENT { name: i_name, .. } => {
                txt = Tpl::writeStr(txt, i_name.clone())?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn lm_55(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<SCode::Element>>) -> Result<Tpl::Text> {
    for lstElt_55 in items {
        ::match_deref::match_deref! { match lstElt_55 {
            Deref @ SCode::Element::COMPONENT { name: i_name, .. } => {
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
                txt = Tpl::writeStr(txt, i_name.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn fun_56(
    mut in_txt: Tpl::Text,
    in_mArg: &ArcStr,
    mut in_a_fieldsStr: Tpl::Text,
    mut in_a_nElts: Tpl::Text,
    mut in_a_omcname: Tpl::Text,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        Deref @ "0" => {
            let mut txt = in_txt;
            let mut a_omcname = in_a_omcname;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("ADD_METARECORD_DEFINITIONS const char* ") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__desc__fields[1] = {\"no fields\"};") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut a_fieldsStr = in_a_fieldsStr;
            let mut a_nElts = in_a_nElts;
            let mut a_omcname = in_a_omcname;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("ADD_METARECORD_DEFINITIONS const char* ") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__desc__fields[") }))?;
            txt = Tpl::writeText(txt, a_nElts)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("] = {") }))?;
            txt = Tpl::writeText(txt, a_fieldsStr)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("};") }))?;
            Ok(txt)
        }
        _ => Err("fun_56: no case matched"),
    } }
}

fn fun_57(
    mut in_txt: Tpl::Text,
    in_a_p_elementLst: &metamodelica::List<metamodelica::Ref<SCode::Element>>,
    mut in_a_fields: Tpl::Text,
    mut in_a_omcname: Tpl::Text,
    mut in_a_ctor: Tpl::Text,
    mut in_a_fullname: Tpl::Text,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_p_elementLst {
        Deref @ metamodelica::ListNode::Nil => {
            let mut txt = in_txt;
            let mut a_omcname = in_a_omcname;
            let mut a_ctor = in_a_ctor;
            let mut a_fullname = in_a_fullname;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("static const MMC_DEFSTRUCTLIT(") }))?;
            txt = Tpl::writeText(txt, a_fullname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__struct,1,") }))?;
            txt = Tpl::writeText(txt, a_ctor)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(") {&") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("__desc}};\n"), literal!("static void *")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, a_fullname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" = MMC_REFSTRUCTLIT(") }))?;
            txt = Tpl::writeText(txt, a_fullname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__struct);") }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            Ok(txt)
        }
        i_p_elementLst => {
            let mut txt = in_txt;
            let mut a_fields = in_a_fields;
            let mut a_omcname = in_a_omcname;
            let mut a_ctor = in_a_ctor;
            let mut a_fullname = in_a_fullname;
            let mut ret_0;
            let mut ret_1;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("#define ") }))?;
            txt = Tpl::writeText(txt, a_fullname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeText(txt, a_fields.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(") (mmc_mk_box") }))?;
            ret_0 = listLength(i_p_elementLst.clone());
            ret_1 = intAdd(1, ret_0);
            txt = metaHelperBoxStart(txt, ret_1)?;
            txt = Tpl::writeText(txt, a_ctor)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",&") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__desc,") }))?;
            txt = Tpl::writeText(txt, a_fields)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("))") }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            Ok(txt)
        }
        _ => Err("fun_57: no case matched"),
    } }
}

pub fn elementExternalHeader(
    mut in_txt: Tpl::Text,
    in_a_elt: &metamodelica::Ref<SCode::Element>,
    in_a_pack: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_elt, in_a_pack) {
        (Deref @ SCode::Element::CLASS { restriction: SCode::Restriction::R_METARECORD { moved: true, name: i_r_name, index: i_r_index, .. }, classDef: Deref @ SCode::ClassDef::PARTS { elementLst: i_p_elementLst, .. }, name: i_c_name, .. }, a_pack) => {
            let mut txt = in_txt;
            let mut l_fields;
            let mut l_fieldsStr;
            let mut l_omcname;
            let mut ret_3;
            let mut ret_5;
            let mut l_nElts;
            let mut l_fullname;
            let mut ret_7;
            let mut ret_9;
            let mut l_ctor;
            let mut str_11;
            let mut l_fieldsDescription;
            l_fields = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_fields = lm_54(l_fields, i_p_elementLst)?;
            l_fields = Tpl::popIter(l_fields)?;
            l_fieldsStr = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_fieldsStr = lm_55(l_fieldsStr, i_p_elementLst)?;
            l_fieldsStr = Tpl::popIter(l_fieldsStr)?;
            l_omcname = Tpl::writeStr((*Tpl::emptyTxt).clone(), a_pack.clone())?;
            l_omcname = Tpl::writeTok(l_omcname, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            l_omcname = pathString(l_omcname, i_r_name)?;
            l_omcname = Tpl::writeTok(l_omcname, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            ret_3 = System::stringReplace(i_c_name.clone(), literal!("_"), literal!("__"))?;
            l_omcname = Tpl::writeStr(l_omcname, ret_3)?;
            ret_5 = listLength(i_p_elementLst.clone());
            l_nElts = Tpl::writeStr((*Tpl::emptyTxt).clone(), intString(ret_5))?;
            l_fullname = Tpl::writeStr((*Tpl::emptyTxt).clone(), a_pack.clone())?;
            l_fullname = Tpl::writeTok(l_fullname, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__") }))?;
            ret_7 = System::stringReplace(i_c_name.clone(), literal!("_"), literal!("_5f"))?;
            l_fullname = Tpl::writeStr(l_fullname, ret_7)?;
            ret_9 = intAdd(3, *i_r_index);
            l_ctor = Tpl::writeStr((*Tpl::emptyTxt).clone(), intString(ret_9))?;
            str_11 = Tpl::textString(l_nElts.clone())?;
            l_fieldsDescription = fun_56((*Tpl::emptyTxt).clone(), &str_11, l_fieldsStr, l_nElts.clone(), l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("#ifdef ADD_METARECORD_DEFINITIONS\n"), literal!("#ifndef ")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("__desc_added\n"), literal!("#define ")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("__desc_added\n") }))?;
            txt = Tpl::writeText(txt, l_fieldsDescription)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("ADD_METARECORD_DEFINITIONS struct record_description ") }))?;
            txt = Tpl::writeText(txt, l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("__desc = {\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"") }))?;
            txt = Tpl::writeText(txt, l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\",\n"), literal!("\"")], lastHasNewLine: false }))?;
            txt = Tpl::writeStr(txt, a_pack.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".") }))?;
            txt = pathString(txt, i_r_name)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".") }))?;
            txt = Tpl::writeStr(txt, i_c_name.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("\",\n") }))?;
            txt = Tpl::writeText(txt, l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("__desc__fields\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("};\n"), literal!("#endif\n"), literal!("#else /* Only use the file as a header */\n"), literal!("extern struct record_description ")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("__desc;\n"), literal!("#endif\n"), literal!("#define ")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_fullname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_3dBOX") }))?;
            txt = Tpl::writeText(txt, l_nElts)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, l_ctor.clone())?;
            txt = Tpl::softNewLine(txt)?;
            txt = fun_57(txt, i_p_elementLst, l_fields, l_omcname, l_ctor, l_fullname)?;
            Ok(txt)
        }
        (i_elt @ Deref @ SCode::Element::CLASS { .. }, a_pack) => {
            let mut txt = in_txt;
            txt = classExternalHeader(txt, i_elt, a_pack)?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("elementExternalHeader: no case matched"),
    } }
}

fn lm_59(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<SCode::Element>>,
    mut a_buf2: Tpl::Text,
    mut a_buf1: Tpl::Text,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text)> {
    for lstElt_59 in items {
        ::match_deref::match_deref! { match lstElt_59 {
            i_cl => {
                (txt, a_buf1, a_buf2) = classExternalHeaderJulia(txt, a_buf1, a_buf2, i_cl, &literal!(""))?;
            }
            _ => return Err("lm_59: no case matched"),
        } }
    }
    Ok((txt, a_buf2, a_buf1))
}

pub fn programExternalHeaderJulia(
    mut txt: Tpl::Text,
    a_program: &metamodelica::List<metamodelica::Ref<SCode::Element>>,
) -> Result<Tpl::Text> {
    let mut l_buf1;
    let mut l_buf2;
    let mut l_res;
    let mut out_txt;
    l_buf1 = (*Tpl::emptyTxt).clone();
    l_buf2 = (*Tpl::emptyTxt).clone();
    (l_res, l_buf2, l_buf1) = lm_59((*Tpl::emptyTxt).clone(), a_program, l_buf2, l_buf1)?;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("/* Automatically generated header for external MetaModelica functions */\n"),
                literal!("#include <julia.h>\n"),
                literal!("#include <assert.h>\n"),
                literal!("#ifdef __cplusplus\n"),
                literal!("extern \"C\" {\n"),
                literal!("#endif\n"),
                literal!("#ifdef ADD_METARECORD_DEFINITIONS\n")
            ],
            lastHasNewLine: true,
        }),
    )?;
    out_txt = Tpl::writeText(out_txt, l_buf1)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("void OpenModelica_initAbsynReferences()\n"),
                literal!("{\n"),
                literal!(
                    "  /* Note: These values may be garbage collected away? Call this before each file is parsed? */\n"
                )
            ],
            lastHasNewLine: true,
        }),
    )?;
    out_txt = Tpl::pushBlock(out_txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
    out_txt = Tpl::writeText(out_txt, l_buf2)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::popBlock(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("}\n"),
                literal!("#else\n"),
                literal!("void OpenModelica_initAbsynReferences();\n"),
                literal!("#endif\n")
            ],
            lastHasNewLine: true,
        }),
    )?;
    out_txt = Tpl::writeText(out_txt, l_res)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("#ifdef __cplusplus\n"),
                literal!("}\n"),
                literal!("#endif\n"),
                literal!("\n")
            ],
            lastHasNewLine: true,
        }),
    )?;
    Ok(out_txt)
}

fn fun_61(
    mut in_txt: Tpl::Text,
    in_a_cl: &metamodelica::Ref<SCode::Element>,
    mut in_a_buf1: Tpl::Text,
    mut in_a_buf2: Tpl::Text,
    in_a_pack: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_cl, in_a_pack) {
        (i_c @ Deref @ SCode::Element::CLASS { name: i_c_name, .. }, a_pack) => {
            let mut txt = in_txt;
            let mut a_buf1 = in_a_buf1;
            let mut a_buf2 = in_a_buf2;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("jl_eval_string(\"using ") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\");\n"), literal!("jl_module_t* ")], lastHasNewLine: false }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" = (jl_module_t *) jl_eval_string(\"") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\");\n"), literal!("if (!")], lastHasNewLine: false }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(")\n"), literal!("{\n")], lastHasNewLine: true }))?;
            a_buf2 = Tpl::pushBlock(a_buf2, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("fprintf(stderr, \"module ") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(" not loaded, load it via using.\");\n"), literal!("fflush(NULL);\n")], lastHasNewLine: true }))?;
            a_buf2 = Tpl::popBlock(a_buf2)?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("}\n"), literal!("assert(jl_is_module(")], lastHasNewLine: false }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("));") }))?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            (txt, a_buf1, a_buf2) = classExternalHeaderJuliaWork(txt, a_buf1, a_buf2, i_c, a_pack)?;
            Ok((txt, a_buf1, a_buf2))
        }
        (_, _) => {
            let mut txt = in_txt;
            let mut a_buf1 = in_a_buf1;
            let mut a_buf2 = in_a_buf2;
            Ok((txt, a_buf1, a_buf2))
        }
        _ => Err("fun_61: no case matched"),
    } }
}

pub fn classExternalHeaderJulia(
    mut txt: Tpl::Text,
    mut a_buf1: Tpl::Text,
    mut a_buf2: Tpl::Text,
    a_cl: &metamodelica::Ref<SCode::Element>,
    a_pack: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text)> {
    let mut out_txt;
    let mut out_a_buf1;
    let mut out_a_buf2;
    (out_txt, out_a_buf1, out_a_buf2) = fun_61(txt, a_cl, a_buf1, a_buf2, a_pack)?;
    Ok((out_txt, out_a_buf1, out_a_buf2))
}

fn lm_63(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<SCode::Element>>,
    a_c_name: &ArcStr,
    mut a_buf2: Tpl::Text,
    mut a_buf1: Tpl::Text,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text)> {
    for lstElt_63 in items {
        ::match_deref::match_deref! { match lstElt_63 {
            i_elt => {
                (txt, a_buf1, a_buf2) = elementExternalHeaderJulia(txt, a_buf1, a_buf2, i_elt, a_c_name)?;
            }
            _ => return Err("lm_63: no case matched"),
        } }
    }
    Ok((txt, a_buf2, a_buf1))
}

fn fun_64(
    mut in_txt: Tpl::Text,
    in_a_cl: &metamodelica::Ref<SCode::Element>,
    mut in_a_buf1: Tpl::Text,
    mut in_a_buf2: Tpl::Text,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match in_a_cl {
        Deref @ SCode::Element::CLASS { classDef: Deref @ SCode::ClassDef::PARTS { elementLst: i_p_elementLst, .. }, name: i_c_name, .. } => {
            let mut txt = in_txt;
            let mut a_buf1 = in_a_buf1;
            let mut a_buf2 = in_a_buf2;
            (txt, a_buf2, a_buf1) = lm_63(txt, i_p_elementLst, i_c_name, a_buf2, a_buf1)?;
            Ok((txt, a_buf1, a_buf2))
        }
        _ => {
            let mut txt = in_txt;
            let mut a_buf1 = in_a_buf1;
            let mut a_buf2 = in_a_buf2;
            Ok((txt, a_buf1, a_buf2))
        }
        _ => Err("fun_64: no case matched"),
    } }
}

pub fn classExternalHeaderJuliaWork(
    mut txt: Tpl::Text,
    mut a_buf1: Tpl::Text,
    mut a_buf2: Tpl::Text,
    a_cl: &metamodelica::Ref<SCode::Element>,
    a_pack: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text)> {
    let mut out_txt;
    let mut out_a_buf1;
    let mut out_a_buf2;
    (out_txt, out_a_buf1, out_a_buf2) = fun_64(txt, a_cl, a_buf1, a_buf2)?;
    Ok((out_txt, out_a_buf1, out_a_buf2))
}

fn lm_66(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<SCode::Element>>) -> Result<Tpl::Text> {
    for lstElt_66 in items {
        ::match_deref::match_deref! { match lstElt_66 {
            Deref @ SCode::Element::COMPONENT { name: i_name, .. } => {
                txt = Tpl::writeStr(txt, i_name.clone())?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn lm_67(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<SCode::Element>>) -> Result<Tpl::Text> {
    for lstElt_67 in items {
        ::match_deref::match_deref! { match lstElt_67 {
            Deref @ SCode::Element::COMPONENT { name: i_name, .. } => {
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(", ") }))?;
                txt = Tpl::writeStr(txt, i_name.clone())?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn lm_68(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<SCode::Element>>) -> Result<Tpl::Text> {
    for lstElt_68 in items {
        ::match_deref::match_deref! { match lstElt_68 {
            Deref @ SCode::Element::COMPONENT { name: i_name, .. } => {
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("jl_value_t *") }))?;
                txt = Tpl::writeStr(txt, i_name.clone())?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn fun_69(
    mut in_txt: Tpl::Text,
    mut in_mArg: i32,
    mut in_a_fields1: Tpl::Text,
    mut in_a_fields2: Tpl::Text,
    in_a_p_elementLst: &metamodelica::List<metamodelica::Ref<SCode::Element>>,
    mut in_a_fieldsWithType: Tpl::Text,
    mut in_a_omcname: Tpl::Text,
    mut in_a_fullname: Tpl::Text,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_p_elementLst) {
        (0, _) => {
            let mut txt = in_txt;
            let mut a_omcname = in_a_omcname;
            let mut a_fullname = in_a_fullname;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("#define ") }))?;
            txt = Tpl::writeText(txt, a_fullname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" jl_call0(") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")") }))?;
            Ok(txt)
        }
        (1, a_p_elementLst) => {
            let mut txt = in_txt;
            let mut a_fields2 = in_a_fields2;
            let mut a_fieldsWithType = in_a_fieldsWithType;
            let mut a_omcname = in_a_omcname;
            let mut a_fullname = in_a_fullname;
            let mut ret_0;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("static inline jl_value_t* ") }))?;
            txt = Tpl::writeText(txt, a_fullname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeText(txt, a_fieldsWithType)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(") {\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("return jl_call") }))?;
            ret_0 = listLength(a_p_elementLst.clone());
            txt = Tpl::writeStr(txt, intString(ret_0))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeText(txt, a_fields2)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(");\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok(txt)
        }
        (2, a_p_elementLst) => {
            let mut txt = in_txt;
            let mut a_fields2 = in_a_fields2;
            let mut a_fieldsWithType = in_a_fieldsWithType;
            let mut a_omcname = in_a_omcname;
            let mut a_fullname = in_a_fullname;
            let mut ret_1;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("static inline jl_value_t* ") }))?;
            txt = Tpl::writeText(txt, a_fullname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeText(txt, a_fieldsWithType)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(") {\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("return jl_call") }))?;
            ret_1 = listLength(a_p_elementLst.clone());
            txt = Tpl::writeStr(txt, intString(ret_1))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeText(txt, a_fields2)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(");\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok(txt)
        }
        (3, a_p_elementLst) => {
            let mut txt = in_txt;
            let mut a_fields2 = in_a_fields2;
            let mut a_fieldsWithType = in_a_fieldsWithType;
            let mut a_omcname = in_a_omcname;
            let mut a_fullname = in_a_fullname;
            let mut ret_2;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("static inline jl_value_t* ") }))?;
            txt = Tpl::writeText(txt, a_fullname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeText(txt, a_fieldsWithType)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(") {\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("return jl_call") }))?;
            ret_2 = listLength(a_p_elementLst.clone());
            txt = Tpl::writeStr(txt, intString(ret_2))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeText(txt, a_fields2)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(");\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok(txt)
        }
        (_, a_p_elementLst) => {
            let mut txt = in_txt;
            let mut a_fields1 = in_a_fields1;
            let mut a_fieldsWithType = in_a_fieldsWithType;
            let mut a_omcname = in_a_omcname;
            let mut a_fullname = in_a_fullname;
            let mut ret_3;
            let mut ret_4;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("static inline jl_value_t* ") }))?;
            txt = Tpl::writeText(txt, a_fullname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("(") }))?;
            txt = Tpl::writeText(txt, a_fieldsWithType)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(") {\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("jl_value_t *values[") }))?;
            ret_3 = listLength(a_p_elementLst.clone());
            txt = Tpl::writeStr(txt, intString(ret_3))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("] = {") }))?;
            txt = Tpl::writeText(txt, a_fields1)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("};\n"), literal!("return jl_call(")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, a_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(", values, ") }))?;
            ret_4 = listLength(a_p_elementLst.clone());
            txt = Tpl::writeStr(txt, intString(ret_4))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(");\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok(txt)
        }
        _ => Err("fun_69: no case matched"),
    } }
}

fn fun_70(
    mut in_txt: Tpl::Text,
    in_a_elt: &metamodelica::Ref<SCode::Element>,
    mut in_a_buf1: Tpl::Text,
    mut in_a_buf2: Tpl::Text,
    in_a_pack: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_elt, in_a_pack) {
        (Deref @ SCode::Element::CLASS { restriction: SCode::Restriction::R_UNIONTYPE { .. }, classDef: Deref @ SCode::ClassDef::PARTS { .. }, name: i_c_name, .. }, a_pack) => {
            let mut txt = in_txt;
            let mut a_buf1 = in_a_buf1;
            let mut a_buf2 = in_a_buf2;
            let mut l_omcname;
            l_omcname = Tpl::writeStr((*Tpl::emptyTxt).clone(), a_pack.clone())?;
            l_omcname = Tpl::writeTok(l_omcname, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            l_omcname = Tpl::writeStr(l_omcname, i_c_name.clone())?;
            a_buf1 = Tpl::writeTok(a_buf1, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("jl_value_t *") }))?;
            a_buf1 = Tpl::writeText(a_buf1, l_omcname.clone())?;
            a_buf1 = Tpl::writeTok(a_buf1, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(" = NULL;\n") }))?;
            a_buf1 = Tpl::writeTok(a_buf1, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("assert((") }))?;
            a_buf2 = Tpl::writeText(a_buf2, l_omcname.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" = jl_get_global(") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, a_pack.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(", jl_symbol(\"") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"))));") }))?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("extern jl_value_t *") }))?;
            txt = Tpl::writeText(txt, l_omcname)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            Ok((txt, a_buf1, a_buf2))
        }
        (Deref @ SCode::Element::CLASS { restriction: SCode::Restriction::R_METARECORD { moved: true, name: i_r_name, .. }, classDef: Deref @ SCode::ClassDef::PARTS { elementLst: i_p_elementLst, .. }, name: i_c_name, .. }, a_pack) => {
            let mut txt = in_txt;
            let mut a_buf1 = in_a_buf1;
            let mut a_buf2 = in_a_buf2;
            let mut l_fields1;
            let mut l_fields2;
            let mut l_fieldsWithType;
            let mut l_funcName;
            let mut l_omcname;
            let mut ret_5;
            let mut l_fullname;
            let mut ret_7;
            let mut ret_8;
            l_fields1 = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_fields1 = lm_66(l_fields1, i_p_elementLst)?;
            l_fields1 = Tpl::popIter(l_fields1)?;
            l_fields2 = lm_67((*Tpl::emptyTxt).clone(), i_p_elementLst)?;
            l_fieldsWithType = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(",") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_fieldsWithType = lm_68(l_fieldsWithType, i_p_elementLst)?;
            l_fieldsWithType = Tpl::popIter(l_fieldsWithType)?;
            l_funcName = Tpl::writeStr((*Tpl::emptyTxt).clone(), a_pack.clone())?;
            l_funcName = Tpl::writeTok(l_funcName, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".") }))?;
            l_funcName = pathString(l_funcName, i_r_name)?;
            l_omcname = Tpl::writeStr((*Tpl::emptyTxt).clone(), a_pack.clone())?;
            l_omcname = Tpl::writeTok(l_omcname, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            l_omcname = pathString(l_omcname, i_r_name)?;
            l_omcname = Tpl::writeTok(l_omcname, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            ret_5 = System::stringReplace(i_c_name.clone(), literal!("_"), literal!("__"))?;
            l_omcname = Tpl::writeStr(l_omcname, ret_5)?;
            l_fullname = Tpl::writeStr((*Tpl::emptyTxt).clone(), a_pack.clone())?;
            l_fullname = Tpl::writeTok(l_fullname, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__") }))?;
            ret_7 = System::stringReplace(i_c_name.clone(), literal!("_"), literal!("_5f"))?;
            l_fullname = Tpl::writeStr(l_fullname, ret_7)?;
            a_buf1 = Tpl::writeTok(a_buf1, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("jl_function_t *") }))?;
            a_buf1 = Tpl::writeText(a_buf1, l_omcname.clone())?;
            a_buf1 = Tpl::writeTok(a_buf1, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(" = NULL;\n"), literal!("jl_value_t *")], lastHasNewLine: false }))?;
            a_buf1 = Tpl::writeText(a_buf1, l_omcname.clone())?;
            a_buf1 = Tpl::writeTok(a_buf1, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("_type = NULL;\n") }))?;
            a_buf1 = Tpl::writeTok(a_buf1, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("assert((") }))?;
            a_buf2 = Tpl::writeText(a_buf2, l_omcname.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" = jl_get_function(") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, a_pack.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(", \"") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\")));\n"), literal!("assert((")], lastHasNewLine: false }))?;
            a_buf2 = Tpl::writeText(a_buf2, l_omcname.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_type = jl_get_global(") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, a_pack.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(", jl_symbol(\"") }))?;
            a_buf2 = Tpl::writeStr(a_buf2, i_c_name.clone())?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\"))));") }))?;
            a_buf2 = Tpl::writeTok(a_buf2, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("extern jl_function_t *") }))?;
            txt = Tpl::writeText(txt, l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(";\n"), literal!("extern jl_function_t *")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_omcname.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("_type;\n") }))?;
            ret_8 = listLength(i_p_elementLst.clone());
            txt = fun_69(txt, ret_8, l_fields1, l_fields2, i_p_elementLst, l_fieldsWithType, l_omcname, l_fullname)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            Ok((txt, a_buf1, a_buf2))
        }
        (i_elt @ Deref @ SCode::Element::CLASS { .. }, a_pack) => {
            let mut txt = in_txt;
            let mut a_buf1 = in_a_buf1;
            let mut a_buf2 = in_a_buf2;
            (txt, a_buf1, a_buf2) = classExternalHeaderJuliaWork(txt, a_buf1, a_buf2, i_elt, a_pack)?;
            Ok((txt, a_buf1, a_buf2))
        }
        (_, _) => {
            let mut txt = in_txt;
            let mut a_buf1 = in_a_buf1;
            let mut a_buf2 = in_a_buf2;
            Ok((txt, a_buf1, a_buf2))
        }
        _ => Err("fun_70: no case matched"),
    } }
}

pub fn elementExternalHeaderJulia(
    mut txt: Tpl::Text,
    mut a_buf1: Tpl::Text,
    mut a_buf2: Tpl::Text,
    a_elt: &metamodelica::Ref<SCode::Element>,
    a_pack: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text)> {
    let mut out_txt;
    let mut out_a_buf1;
    let mut out_a_buf2;
    (out_txt, out_a_buf1, out_a_buf2) = fun_70(txt, a_elt, a_buf1, a_buf2, a_pack)?;
    Ok((out_txt, out_a_buf1, out_a_buf2))
}
