// Generated by Susan from CodegenFMUCppHpcom.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use crate::CodegenCppHpcom;
use crate::CodegenFMUCpp;
use openmodelica_codegen_cpp::CodegenCpp;
use openmodelica_codegen_cpp_common::CodegenCppInit;
use openmodelica_codegen_util::CodegenUtil;
use openmodelica_simcode_types::HpcOmSimCode;
use openmodelica_simcode_types::SimCode;
use openmodelica_simcode_types::SimCodeFunction;
use openmodelica_tpl::Tpl;
use openmodelica_util::Config;
use openmodelica_util::Flags;
use openmodelica_util::System;

pub fn translateModel(
    mut in_txt: Tpl::Text,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    in_a_FMUVersion: &ArcStr,
    in_a_FMUType: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_simCode, in_a_FMUVersion, in_a_FMUType) {
        (i_simCode @ Deref @ SimCode::SimCode { modelInfo: i_modelInfo @ SimCode::ModelInfo { name: i_modelInfo_name, .. }, makefileParams: SimCodeFunction::MakefileParams { .. }, hpcomData: HpcOmSimCode::HpcOmData { hpcOmMemory: i_hpcomData_hpcOmMemory, schedules: i_hpcomData_schedules, .. }, fileNamePrefix: i_fileNamePrefix, allEquations: i_allEquations, varToArrayIndexMapping: i_varToArrayIndexMapping, .. }, a_FMUVersion, a_FMUType) => {
            let mut txt = in_txt;
            let mut ret_1;
            let mut l_guid;
            let mut ret_3;
            let mut l_target;
            let mut l_stateDerVectorName;
            let mut l_extraFuncs;
            let mut l_extraFuncsDecl;
            let mut l_complexStartExpressions;
            let mut l_className;
            let mut l_numRealVars;
            let mut l_numIntVars;
            let mut l_numBoolVars;
            let mut l_numStringVars;
            let mut l_numPreVars;
            let mut txt_14;
            let mut l_cpp;
            let mut txt_16;
            let mut txt_17;
            let mut txt_18;
            let mut txt_19;
            let mut txt_20;
            let mut txt_21;
            let mut txt_22;
            let mut txt_23;
            let mut txt_24;
            let mut txt_25;
            let mut txt_26;
            let mut txt_27;
            let mut txt_28;
            let mut txt_29;
            let mut txt_30;
            let mut txt_31;
            let mut txt_32;
            let mut txt_33;
            let mut txt_34;
            let mut txt_35;
            let mut txt_36;
            let mut txt_37;
            let mut txt_38;
            let mut txt_39;
            let mut txt_40;
            let mut txt_41;
            let mut txt_42;
            let mut ret_43;
            let mut txt_44;
            let mut txt_45;
            let mut txt_46;
            ret_1 = System::getUUIDStr();
            l_guid = Tpl::writeStr((*Tpl::emptyTxt).clone(), ret_1)?;
            ret_3 = Config::simulationCodeTarget()?;
            l_target = Tpl::writeStr((*Tpl::emptyTxt).clone(), ret_3)?;
            l_stateDerVectorName = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("__zDot") }))?;
            l_extraFuncs = (*Tpl::emptyTxt).clone();
            l_extraFuncsDecl = (*Tpl::emptyTxt).clone();
            l_complexStartExpressions = (*Tpl::emptyTxt).clone();
            l_className = CodegenCpp::lastIdentOfPath((*Tpl::emptyTxt).clone(), i_modelInfo_name)?;
            l_numRealVars = CodegenCppHpcom::numRealvarsHpcom((*Tpl::emptyTxt).clone(), i_modelInfo, i_hpcomData_hpcOmMemory)?;
            l_numIntVars = CodegenCppHpcom::numIntvarsHpcom((*Tpl::emptyTxt).clone(), i_modelInfo, i_hpcomData_hpcOmMemory)?;
            l_numBoolVars = CodegenCppHpcom::numBoolvarsHpcom((*Tpl::emptyTxt).clone(), i_modelInfo, i_hpcomData_hpcOmMemory)?;
            l_numStringVars = CodegenCppHpcom::numStringvarsHpcom((*Tpl::emptyTxt).clone(), i_modelInfo, i_hpcomData_hpcOmMemory)?;
            l_numPreVars = CodegenCppHpcom::numPreVarsHpcom((*Tpl::emptyTxt).clone(), i_modelInfo, i_hpcomData_hpcOmMemory)?;
            (txt_14, l_complexStartExpressions, l_stateDerVectorName) = CodegenCppInit::modelInitXMLFile((*Tpl::emptyTxt).clone(), i_simCode, &Tpl::textString(l_numRealVars.clone())?, &Tpl::textString(l_numIntVars.clone())?, &Tpl::textString(l_numBoolVars.clone())?, &Tpl::textString(l_numStringVars.clone())?, a_FMUVersion, a_FMUType, &Tpl::textString(l_guid.clone())?, true, &literal!("hpcom cpp-runtime"), l_complexStartExpressions, l_stateDerVectorName)?;
            Tpl::textFile(txt_14, literal!("modelDescription.xml"))?;
            l_cpp = CodegenCpp::translateModel((*Tpl::emptyTxt).clone(), i_simCode)?;
            (txt_16, l_extraFuncs, l_extraFuncsDecl, _) = CodegenFMUCpp::fmuWriteOutputHeaderFile((*Tpl::emptyTxt).clone(), i_simCode, l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })))?;
            txt_17 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OMCpp") }))?;
            txt_17 = Tpl::writeStr(txt_17, i_fileNamePrefix.clone())?;
            txt_17 = Tpl::writeTok(txt_17, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("WriteOutput.h") }))?;
            Tpl::textFile(txt_16, Tpl::textString(txt_17)?)?;
            (txt_18, l_extraFuncs, l_extraFuncsDecl, _) = CodegenFMUCpp::fmuModelHeaderFile((*Tpl::emptyTxt).clone(), i_simCode, l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })), &Tpl::textString(l_guid.clone())?, a_FMUVersion)?;
            txt_19 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OMCpp") }))?;
            txt_19 = Tpl::writeStr(txt_19, i_fileNamePrefix.clone())?;
            txt_19 = Tpl::writeTok(txt_19, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("FMU.h") }))?;
            Tpl::textFile(txt_18, Tpl::textString(txt_19)?)?;
            (txt_20, l_extraFuncs, l_extraFuncsDecl, _) = CodegenFMUCpp::fmuModelCppFile((*Tpl::emptyTxt).clone(), i_simCode, l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })), &Tpl::textString(l_guid)?, a_FMUVersion)?;
            txt_21 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OMCpp") }))?;
            txt_21 = Tpl::writeStr(txt_21, i_fileNamePrefix.clone())?;
            txt_21 = Tpl::writeTok(txt_21, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("FMU.cpp") }))?;
            Tpl::textFile(txt_20, Tpl::textString(txt_21)?)?;
            (txt_22, l_extraFuncs, l_extraFuncsDecl, _) = fmuMakefile((*Tpl::emptyTxt).clone(), &Tpl::textString(l_target)?, i_simCode, l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })), a_FMUVersion)?;
            txt_23 = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_fileNamePrefix.clone())?;
            txt_23 = Tpl::writeTok(txt_23, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_FMU.makefile") }))?;
            Tpl::textFile(txt_22, Tpl::textString(txt_23)?)?;
            txt_24 = CodegenFMUCpp::fmuCalcHelperMainfile((*Tpl::emptyTxt).clone(), i_simCode)?;
            txt_25 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OMCpp") }))?;
            txt_25 = Tpl::writeStr(txt_25, i_fileNamePrefix.clone())?;
            txt_25 = Tpl::writeTok(txt_25, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("CalcHelperMain.cpp") }))?;
            Tpl::textFile(txt_24, Tpl::textString(txt_25)?)?;
            (txt_26, l_extraFuncs, l_extraFuncsDecl, _, l_stateDerVectorName) = CodegenCppHpcom::updateHpcom((*Tpl::emptyTxt).clone(), i_allEquations, i_simCode, l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })), &SimCodeFunction::contextOther(), l_stateDerVectorName, false)?;
            txt_27 = Tpl::writeText((*Tpl::emptyTxt).clone(), l_numRealVars.clone())?;
            txt_27 = Tpl::writeTok(txt_27, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-1") }))?;
            txt_28 = Tpl::writeText((*Tpl::emptyTxt).clone(), l_numIntVars.clone())?;
            txt_28 = Tpl::writeTok(txt_28, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-1") }))?;
            txt_29 = Tpl::writeText((*Tpl::emptyTxt).clone(), l_numBoolVars.clone())?;
            txt_29 = Tpl::writeTok(txt_29, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-1") }))?;
            txt_30 = Tpl::writeText((*Tpl::emptyTxt).clone(), l_numStringVars.clone())?;
            txt_30 = Tpl::writeTok(txt_30, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-1") }))?;
            txt_31 = CodegenCppHpcom::additionalHpcomConstructorDefinitions((*Tpl::emptyTxt).clone(), i_hpcomData_schedules)?;
            txt_32 = CodegenUtil::dotPath((*Tpl::emptyTxt).clone(), i_modelInfo_name)?;
            txt_33 = CodegenCppHpcom::additionalHpcomConstructorBodyStatements((*Tpl::emptyTxt).clone(), i_hpcomData_schedules, &Tpl::textString(l_className.clone())?, &Tpl::textString(txt_32)?)?;
            txt_34 = CodegenCppHpcom::additionalHpcomDestructorBodyStatements((*Tpl::emptyTxt).clone(), i_hpcomData_schedules)?;
            (txt_35, txt_26, txt_27, txt_28, txt_29, txt_30, l_extraFuncs, l_extraFuncsDecl, l_className, txt_31, txt_33, txt_34, l_stateDerVectorName) = CodegenCpp::simulationCppFile((*Tpl::emptyTxt).clone(), i_simCode, &SimCodeFunction::contextOther(), txt_26, txt_27, txt_28, txt_29, txt_30, l_extraFuncs, l_extraFuncsDecl, l_className, txt_31, txt_33, txt_34, l_stateDerVectorName, false)?;
            txt_36 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OMCpp") }))?;
            txt_36 = Tpl::writeStr(txt_36, i_fileNamePrefix.clone())?;
            txt_36 = Tpl::writeTok(txt_36, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".cpp") }))?;
            Tpl::textFile(txt_35, Tpl::textString(txt_36)?)?;
            (txt_37, l_extraFuncs, l_extraFuncsDecl, l_className) = CodegenCppHpcom::additionalHpcomIncludes((*Tpl::emptyTxt).clone(), i_simCode, l_extraFuncs, l_extraFuncsDecl, l_className, false)?;
            (txt_38, l_extraFuncs, l_extraFuncsDecl, _) = CodegenCppHpcom::additionalHpcomProtectedMemberDeclaration((*Tpl::emptyTxt).clone(), i_simCode, l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })), false)?;
            txt_39 = Tpl::writeText((*Tpl::emptyTxt).clone(), l_numRealVars)?;
            txt_39 = Tpl::writeTok(txt_39, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-1") }))?;
            txt_40 = Tpl::writeText((*Tpl::emptyTxt).clone(), l_numIntVars)?;
            txt_40 = Tpl::writeTok(txt_40, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-1") }))?;
            txt_41 = Tpl::writeText((*Tpl::emptyTxt).clone(), l_numBoolVars)?;
            txt_41 = Tpl::writeTok(txt_41, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-1") }))?;
            txt_42 = Tpl::writeText((*Tpl::emptyTxt).clone(), l_numStringVars)?;
            txt_42 = Tpl::writeTok(txt_42, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-1") }))?;
            ret_43 = Flags::isSet(Flags::GEN_DEBUG_SYMBOLS.clone())?;
            (txt_44, txt_39, txt_40, txt_41, txt_42) = CodegenCpp::memberVariableDefine((*Tpl::emptyTxt).clone(), i_modelInfo, i_varToArrayIndexMapping, txt_39, txt_40, txt_41, txt_42, ret_43, false)?;
            (txt_45, l_extraFuncs, l_extraFuncsDecl, _) = CodegenCpp::simulationHeaderFile((*Tpl::emptyTxt).clone(), i_simCode, &SimCodeFunction::contextOther(), l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })), &Tpl::textString(txt_37)?, &literal!(""), &Tpl::textString(txt_38)?, &Tpl::textString(txt_44)?, false)?;
            txt_46 = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OMCpp") }))?;
            txt_46 = Tpl::writeStr(txt_46, i_fileNamePrefix.clone())?;
            txt_46 = Tpl::writeTok(txt_46, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".h") }))?;
            Tpl::textFile(txt_45, Tpl::textString(txt_46)?)?;
            Ok(txt)
        }
        (_, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("translateModel: no case matched"),
    } }
}

fn fun_53(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -lboost_thread") }))?;
            Ok(txt)
        }
        _ => Err("fun_53: no case matched"),
    } }
}

pub fn fmuMakefile(
    mut txt: Tpl::Text,
    a_target: &ArcStr,
    a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    mut a_extraFuncs: Tpl::Text,
    mut a_extraFuncsDecl: Tpl::Text,
    mut a_extraFuncsNamespace: Tpl::Text,
    a_FMUVersion: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    let mut ret_1;
    let mut l_type;
    let mut l_additionalCFlags__GCC;
    let mut l_additionalCFlags__MSVC;
    let mut l_additionalLinkerFlags__GCC;
    let mut l_additionalLinkerFlags__MSVC;
    let mut ret_6;
    let mut ret_7;
    let mut ret_8;
    let mut out_txt;
    let mut out_a_extraFuncs;
    let mut out_a_extraFuncsDecl;
    let mut out_a_extraFuncsNamespace;
    ret_1 = Flags::getConfigString(Flags::HPCOM_CODE.clone())?;
    l_type = Tpl::writeStr((*Tpl::emptyTxt).clone(), ret_1)?;
    l_additionalCFlags__GCC = (*Tpl::emptyTxt).clone();
    l_additionalCFlags__MSVC = (*Tpl::emptyTxt).clone();
    l_additionalLinkerFlags__GCC = (*Tpl::emptyTxt).clone();
    l_additionalLinkerFlags__MSVC = (*Tpl::emptyTxt).clone();
    ret_6 = stringEq(&Tpl::textString(l_type.clone())?, &literal!("pthreads"));
    ret_7 = stringEq(&Tpl::textString(l_type)?, &literal!("pthreads_spin"));
    ret_8 = boolOr(ret_6, ret_7);
    l_additionalLinkerFlags__GCC = fun_53(l_additionalLinkerFlags__GCC, ret_8)?;
    (
        out_txt,
        l_additionalCFlags__GCC,
        l_additionalCFlags__MSVC,
        l_additionalLinkerFlags__GCC,
        l_additionalLinkerFlags__MSVC,
    ) = CodegenCppHpcom::getAdditionalMakefileFlags(
        txt,
        l_additionalCFlags__GCC,
        l_additionalCFlags__MSVC,
        l_additionalLinkerFlags__GCC,
        l_additionalLinkerFlags__MSVC,
    )?;
    out_txt = Tpl::softNewLine(out_txt)?;
    (
        out_txt,
        out_a_extraFuncs,
        out_a_extraFuncsDecl,
        out_a_extraFuncsNamespace,
    ) = CodegenFMUCpp::fmuMakefile(
        out_txt,
        a_target,
        a_simCode,
        a_extraFuncs,
        a_extraFuncsDecl,
        a_extraFuncsNamespace,
        a_FMUVersion,
        &Tpl::textString(l_additionalLinkerFlags__GCC)?,
        &Tpl::textString(l_additionalLinkerFlags__MSVC)?,
        &Tpl::textString(l_additionalCFlags__GCC)?,
        &Tpl::textString(l_additionalCFlags__MSVC)?,
        &literal!(""),
    )?;
    Ok((
        out_txt,
        out_a_extraFuncs,
        out_a_extraFuncsDecl,
        out_a_extraFuncsNamespace,
    ))
}
