// Generated by Susan from GraphvizDump.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use crate::BackendDump;
use crate::BackendEquation;
use crate::BackendVariable;
use openmodelica_backend_types::BackendDAE;
use openmodelica_codegen_util::CodegenUtil;
use openmodelica_frontend_types::DAE;
use openmodelica_tpl::Tpl;

pub fn dumpBackendDAE(
    mut in_txt: Tpl::Text,
    in_a_backendDAE: &metamodelica::Ref<BackendDAE::BackendDAE>,
    in_a_suffix: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_backendDAE, in_a_suffix) {
        (i_dae @ Deref @ BackendDAE::BackendDAE { shared: Deref @ BackendDAE::Shared { info: BackendDAE::ExtraInfo { fileNamePrefix: i_info_fileNamePrefix, .. }, .. }, .. }, a_suffix) => {
            let mut txt = in_txt;
            let mut l_0__;
            let mut txt_2;
            let mut txt_3;
            let mut l_0___1;
            l_0__ = dumpAdjacencyMatrix((*Tpl::emptyTxt).clone(), i_dae, a_suffix)?;
            txt_2 = dumpMatching((*Tpl::emptyTxt).clone(), i_dae, a_suffix)?;
            txt_3 = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_info_fileNamePrefix.clone())?;
            txt_3 = Tpl::writeTok(txt_3, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt_3 = Tpl::writeStr(txt_3, a_suffix.clone())?;
            txt_3 = Tpl::writeTok(txt_3, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_matching.dot") }))?;
            Tpl::textFile(txt_2, Tpl::textString(txt_3)?)?;
            l_0___1 = (*Tpl::emptyTxt).clone();
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpBackendDAE: no case matched"),
    } }
}

pub fn dumpAdjacencyMatrix(
    mut in_txt: Tpl::Text,
    in_a_backendDAE: &metamodelica::Ref<BackendDAE::BackendDAE>,
    in_a_suffix: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_backendDAE, in_a_suffix) {
        (i_dae @ Deref @ BackendDAE::BackendDAE { shared: Deref @ BackendDAE::Shared { info: BackendDAE::ExtraInfo { fileNamePrefix: i_info_fileNamePrefix, .. }, .. }, .. }, a_suffix) => {
            let mut txt = in_txt;
            let mut txt_1;
            let mut txt_2;
            let mut l_0__;
            txt_1 = dumpDependence((*Tpl::emptyTxt).clone(), i_dae, a_suffix)?;
            txt_2 = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_info_fileNamePrefix.clone())?;
            txt_2 = Tpl::writeTok(txt_2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt_2 = Tpl::writeStr(txt_2, a_suffix.clone())?;
            txt_2 = Tpl::writeTok(txt_2, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_dependence.dot") }))?;
            Tpl::textFile(txt_1, Tpl::textString(txt_2)?)?;
            l_0__ = (*Tpl::emptyTxt).clone();
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpAdjacencyMatrix: no case matched"),
    } }
}

fn fun_11(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_var_varName: &metamodelica::Ref<DAE::ComponentRef>,
    mut in_a_varID: i32,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_var_varName, in_a_varID, in_a_clusterID) {
        (false, a_var_varName, a_varID, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [label=\"") }))?;
            txt = CodegenUtil::crefStr(txt, a_var_varName)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\", shape=\"box\"]") }))?;
            Ok(txt)
        }
        (_, a_var_varName, a_varID, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [label=\"der(") }))?;
            txt = CodegenUtil::crefStr(txt, a_var_varName)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")\", shape=\"box\"]") }))?;
            Ok(txt)
        }
        _ => Err("fun_11: no case matched"),
    } }
}

fn lm_12(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<BackendDAE::Var>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_12 in items {
        ::match_deref::match_deref! { match lstElt_12 {
            i_var @ Deref @ BackendDAE::Var { varName: i_var_varName, .. } => {
                let mut x_varID;
                let mut ret_0;
                x_varID = Tpl::getIteri_i0(txt.clone())?;
                ret_0 = BackendVariable::isStateVar(i_var);
                txt = fun_11(txt, ret_0, i_var_varName, x_varID, a_clusterID)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn lm_13(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<BackendDAE::Equation>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_13 in items {
        ::match_deref::match_deref! { match lstElt_13 {
            i_eq => {
                let mut x_eqID;
                let mut ret_0;
                x_eqID = Tpl::getIteri_i0(txt.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("eq") }))?;
                txt = Tpl::writeStr(txt, intString(a_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
                txt = Tpl::writeStr(txt, intString(x_eqID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [label=\"") }))?;
                ret_0 = BackendDump::equationString(i_eq)?;
                txt = Tpl::writeStr(txt, ret_0)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\", shape=\"box\"]") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_13: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_14(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<BackendDAE::EqSystem>>) -> Result<Tpl::Text> {
    for lstElt_14 in items {
        ::match_deref::match_deref! { match lstElt_14 {
            Deref @ BackendDAE::EqSystem { orderedVars: i_eqSystem_orderedVars, orderedEqs: i_eqSystem_orderedEqs, m: i_eqSystem_m, .. } => {
                let mut x_clusterID;
                let mut ret_1;
                let mut l_varDeclaration;
                let mut ret_3;
                let mut l_eqDeclaration;
                x_clusterID = Tpl::getIteri_i0(txt.clone())?;
                ret_1 = BackendVariable::varList(i_eqSystem_orderedVars)?;
                l_varDeclaration = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_varDeclaration = lm_12(l_varDeclaration, &ret_1, x_clusterID)?;
                l_varDeclaration = Tpl::popIter(l_varDeclaration)?;
                ret_3 = BackendEquation::equationList(i_eqSystem_orderedEqs.clone())?;
                l_eqDeclaration = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_eqDeclaration = lm_13(l_eqDeclaration, &ret_3, x_clusterID)?;
                l_eqDeclaration = Tpl::popIter(l_eqDeclaration)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("subgraph cluster_") }))?;
                txt = Tpl::writeStr(txt, intString(x_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(" {\n") }))?;
                txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("label = \"system #") }))?;
                txt = Tpl::writeStr(txt, intString(x_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\";\n"), literal!("color=white\n"), literal!("\n")], lastHasNewLine: true }))?;
                txt = Tpl::writeText(txt, l_varDeclaration)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
                txt = Tpl::writeText(txt, l_eqDeclaration)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
                txt = dumpDependence2(txt, x_clusterID, i_eqSystem_m)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::popBlock(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

pub fn dumpDependence(
    mut in_txt: Tpl::Text,
    in_a_backendDAE: &metamodelica::Ref<BackendDAE::BackendDAE>,
    in_a_suffix: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_backendDAE, in_a_suffix) {
        (Deref @ BackendDAE::BackendDAE { eqs: i_eqs, shared: Deref @ BackendDAE::Shared { info: BackendDAE::ExtraInfo { fileNamePrefix: i_info_fileNamePrefix, .. }, .. }, .. }, a_suffix) => {
            let mut txt = in_txt;
            let mut l_systems;
            l_systems = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\n"), literal!("\n")], lastHasNewLine: true })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_systems = lm_14(l_systems, i_eqs)?;
            l_systems = Tpl::popIter(l_systems)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("digraph G {\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("label=\"") }))?;
            txt = Tpl::writeStr(txt, i_info_fileNamePrefix.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [") }))?;
            txt = Tpl::writeStr(txt, a_suffix.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(" - dependence]\";\n"), literal!("rankdir=LR;\n"), literal!("\n")], lastHasNewLine: true }))?;
            txt = Tpl::writeText(txt, l_systems)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpDependence: no case matched"),
    } }
}

fn fun_16(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    mut in_a_eqID: i32,
    mut in_a_varID: i32,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_eqID, in_a_varID, in_a_clusterID) {
        (false, _, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        (_, a_eqID, a_varID, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -> eq") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_eqID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [style=\"dashed\", arrowhead=\"none\"];") }))?;
            Ok(txt)
        }
        _ => Err("fun_16: no case matched"),
    } }
}

fn lm_17(
    mut txt: Tpl::Text,
    items: &metamodelica::List<i32>,
    mut a_eqID: i32,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_17 in items {
        ::match_deref::match_deref! { match lstElt_17 {
            i_varID => {
                let mut ret_0;
                ret_0 = intGt(*i_varID, 0);
                txt = fun_16(txt, ret_0, a_eqID, *i_varID, a_clusterID)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_17: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_18(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::List<i32>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_18 in items {
        ::match_deref::match_deref! { match lstElt_18 {
            i_varList => {
                let mut x_eqID;
                let mut l_foo;
                x_eqID = Tpl::getIteri_i0(txt.clone())?;
                l_foo = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_foo = lm_17(l_foo, i_varList, x_eqID, a_clusterID)?;
                l_foo = Tpl::popIter(l_foo)?;
                txt = Tpl::writeText(txt, l_foo)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_18: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_19(
    mut in_txt: Tpl::Text,
    in_a_m: &Option<metamodelica::Array<metamodelica::List<i32>>>,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_m, in_a_clusterID) {
        (Some(i_incMatrix), a_clusterID) => {
            let mut txt = in_txt;
            let mut ret_1;
            let mut l_incNodes;
            ret_1 = arrayList(i_incMatrix.clone());
            l_incNodes = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_incNodes = lm_18(l_incNodes, &ret_1, a_clusterID)?;
            l_incNodes = Tpl::popIter(l_incNodes)?;
            txt = Tpl::writeText(txt, l_incNodes)?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("// no adjacency matrix") }))?;
            Ok(txt)
        }
        _ => Err("fun_19: no case matched"),
    } }
}

pub fn dumpDependence2(
    mut txt: Tpl::Text,
    mut a_clusterID: i32,
    a_m: &Option<metamodelica::Array<metamodelica::List<i32>>>,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = fun_19(txt, a_m, a_clusterID)?;
    Ok(out_txt)
}

fn fun_21(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    in_a_var_varName: &metamodelica::Ref<DAE::ComponentRef>,
    mut in_a_varID: i32,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_var_varName, in_a_varID, in_a_clusterID) {
        (false, a_var_varName, a_varID, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [label=\"") }))?;
            txt = CodegenUtil::crefStr(txt, a_var_varName)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\", shape=\"box\"]") }))?;
            Ok(txt)
        }
        (_, a_var_varName, a_varID, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [label=\"der(") }))?;
            txt = CodegenUtil::crefStr(txt, a_var_varName)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(")\", shape=\"box\"]") }))?;
            Ok(txt)
        }
        _ => Err("fun_21: no case matched"),
    } }
}

fn lm_22(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<BackendDAE::Var>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_22 in items {
        ::match_deref::match_deref! { match lstElt_22 {
            i_var @ Deref @ BackendDAE::Var { varName: i_var_varName, .. } => {
                let mut x_varID;
                let mut ret_0;
                x_varID = Tpl::getIteri_i0(txt.clone())?;
                ret_0 = BackendVariable::isStateVar(i_var);
                txt = fun_21(txt, ret_0, i_var_varName, x_varID, a_clusterID)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn lm_23(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<BackendDAE::Equation>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_23 in items {
        ::match_deref::match_deref! { match lstElt_23 {
            i_eq => {
                let mut x_eqID;
                let mut ret_0;
                x_eqID = Tpl::getIteri_i0(txt.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("eq") }))?;
                txt = Tpl::writeStr(txt, intString(a_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
                txt = Tpl::writeStr(txt, intString(x_eqID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [label=\"") }))?;
                ret_0 = BackendDump::equationString(i_eq)?;
                txt = Tpl::writeStr(txt, ret_0)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\", shape=\"box\"]") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_23: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_24(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<BackendDAE::EqSystem>>) -> Result<Tpl::Text> {
    for lstElt_24 in items {
        ::match_deref::match_deref! { match lstElt_24 {
            Deref @ BackendDAE::EqSystem { orderedVars: i_eqSystem_orderedVars, orderedEqs: i_eqSystem_orderedEqs, matching: i_eqSystem_matching, m: i_eqSystem_m, .. } => {
                let mut x_clusterID;
                let mut ret_1;
                let mut l_varDeclaration;
                let mut ret_3;
                let mut l_eqDeclaration;
                x_clusterID = Tpl::getIteri_i0(txt.clone())?;
                ret_1 = BackendVariable::varList(i_eqSystem_orderedVars)?;
                l_varDeclaration = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_varDeclaration = lm_22(l_varDeclaration, &ret_1, x_clusterID)?;
                l_varDeclaration = Tpl::popIter(l_varDeclaration)?;
                ret_3 = BackendEquation::equationList(i_eqSystem_orderedEqs.clone())?;
                l_eqDeclaration = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_eqDeclaration = lm_23(l_eqDeclaration, &ret_3, x_clusterID)?;
                l_eqDeclaration = Tpl::popIter(l_eqDeclaration)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("subgraph cluster_") }))?;
                txt = Tpl::writeStr(txt, intString(x_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(" {\n") }))?;
                txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("label = \"system #") }))?;
                txt = Tpl::writeStr(txt, intString(x_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\";\n"), literal!("color=white\n"), literal!("\n")], lastHasNewLine: true }))?;
                txt = Tpl::writeText(txt, l_varDeclaration)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
                txt = Tpl::writeText(txt, l_eqDeclaration)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
                txt = connections(txt, x_clusterID, i_eqSystem_matching, i_eqSystem_m)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::popBlock(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

pub fn dumpMatching(
    mut in_txt: Tpl::Text,
    in_a_backendDAE: &metamodelica::Ref<BackendDAE::BackendDAE>,
    in_a_suffix: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_backendDAE, in_a_suffix) {
        (Deref @ BackendDAE::BackendDAE { eqs: i_eqs, shared: Deref @ BackendDAE::Shared { info: BackendDAE::ExtraInfo { fileNamePrefix: i_info_fileNamePrefix, .. }, .. }, .. }, a_suffix) => {
            let mut txt = in_txt;
            let mut l_systems;
            l_systems = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\n"), literal!("\n")], lastHasNewLine: true })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_systems = lm_24(l_systems, i_eqs)?;
            l_systems = Tpl::popIter(l_systems)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("digraph G {\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("label=\"") }))?;
            txt = Tpl::writeStr(txt, i_info_fileNamePrefix.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [") }))?;
            txt = Tpl::writeStr(txt, a_suffix.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(" - matching]\";\n"), literal!("rankdir=LR;\n"), literal!("\n")], lastHasNewLine: true }))?;
            txt = Tpl::writeText(txt, l_systems)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpMatching: no case matched"),
    } }
}

fn fun_26(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    mut in_a_eqID: i32,
    mut in_a_varID: i32,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_eqID, in_a_varID, in_a_clusterID) {
        (false, _, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        (_, a_eqID, a_varID, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -> eq") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_eqID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [style=\"dashed\", arrowhead=\"none\"];") }))?;
            Ok(txt)
        }
        _ => Err("fun_26: no case matched"),
    } }
}

fn fun_27(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    mut in_a_eqID: i32,
    mut in_a_clusterID: i32,
    mut in_a_varID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_eqID, in_a_clusterID, in_a_varID) {
        (false, a_eqID, a_clusterID, a_varID) => {
            let mut txt = in_txt;
            let mut ret_0;
            ret_0 = intGt(a_varID, 0);
            txt = fun_26(txt, ret_0, a_eqID, a_varID, a_clusterID)?;
            Ok(txt)
        }
        (_, a_eqID, a_clusterID, a_varID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -> eq") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_eqID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [style=\"bold\", arrowhead=\"none\"];") }))?;
            Ok(txt)
        }
        _ => Err("fun_27: no case matched"),
    } }
}

fn lm_28(
    mut txt: Tpl::Text,
    items: &metamodelica::List<i32>,
    mut a_clusterID: i32,
    mut a_eqID: i32,
    a_ass2: &metamodelica::Array<i32>,
) -> Result<Tpl::Text> {
    for lstElt_28 in items {
        ::match_deref::match_deref! { match lstElt_28 {
            i_varID => {
                let mut ret_0;
                let mut ret_1;
                let mut ret_2;
                ret_0 = arrayList(a_ass2.clone());
                ret_1 = listGet(ret_0, a_eqID)?;
                ret_2 = intEq(ret_1, *i_varID);
                txt = fun_27(txt, ret_2, a_eqID, a_clusterID, *i_varID)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_28: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_29(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::List<i32>>,
    mut a_clusterID: i32,
    a_ass2: &metamodelica::Array<i32>,
) -> Result<Tpl::Text> {
    for lstElt_29 in items {
        ::match_deref::match_deref! { match lstElt_29 {
            i_varList => {
                let mut x_eqID;
                let mut l_foo;
                x_eqID = Tpl::getIteri_i0(txt.clone())?;
                l_foo = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_foo = lm_28(l_foo, i_varList, a_clusterID, x_eqID, a_ass2)?;
                l_foo = Tpl::popIter(l_foo)?;
                txt = Tpl::writeText(txt, l_foo)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_29: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_30(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    mut in_a_eqID: i32,
    mut in_a_varID: i32,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_eqID, in_a_varID, in_a_clusterID) {
        (false, _, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        (_, a_eqID, a_varID, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -> eq") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_eqID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [style=\"dashed\", arrowhead=\"none\"];") }))?;
            Ok(txt)
        }
        _ => Err("fun_30: no case matched"),
    } }
}

fn lm_31(
    mut txt: Tpl::Text,
    items: &metamodelica::List<i32>,
    mut a_eqID: i32,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_31 in items {
        ::match_deref::match_deref! { match lstElt_31 {
            i_varID => {
                let mut ret_0;
                ret_0 = intGt(*i_varID, 0);
                txt = fun_30(txt, ret_0, a_eqID, *i_varID, a_clusterID)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_31: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_32(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::List<i32>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_32 in items {
        ::match_deref::match_deref! { match lstElt_32 {
            i_varList => {
                let mut x_eqID;
                let mut l_foo;
                x_eqID = Tpl::getIteri_i0(txt.clone())?;
                l_foo = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_foo = lm_31(l_foo, i_varList, x_eqID, a_clusterID)?;
                l_foo = Tpl::popIter(l_foo)?;
                txt = Tpl::writeText(txt, l_foo)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_32: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_33(
    mut in_txt: Tpl::Text,
    in_a_matching: &metamodelica::Ref<BackendDAE::Matching>,
    mut in_a_clusterID: i32,
    in_a_incMatrix: &metamodelica::Array<metamodelica::List<i32>>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_matching, in_a_clusterID, in_a_incMatrix) {
        (Deref @ BackendDAE::Matching::MATCHING { ass2: i_ass2, .. }, a_clusterID, a_incMatrix) => {
            let mut txt = in_txt;
            let mut ret_1;
            let mut l_incNodes;
            ret_1 = arrayList(a_incMatrix.clone());
            l_incNodes = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_incNodes = lm_29(l_incNodes, &ret_1, a_clusterID, i_ass2)?;
            l_incNodes = Tpl::popIter(l_incNodes)?;
            txt = Tpl::writeText(txt, l_incNodes)?;
            Ok(txt)
        }
        (_, a_clusterID, a_incMatrix) => {
            let mut txt = in_txt;
            let mut ret_2;
            let mut l_incNodes;
            ret_2 = arrayList(a_incMatrix.clone());
            l_incNodes = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_incNodes = lm_32(l_incNodes, &ret_2, a_clusterID)?;
            l_incNodes = Tpl::popIter(l_incNodes)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("// no matching\n") }))?;
            txt = Tpl::writeText(txt, l_incNodes)?;
            Ok(txt)
        }
        _ => Err("fun_33: no case matched"),
    } }
}

fn fun_34(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    mut in_a_eqID: i32,
    mut in_a_varID: i32,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_mArg, in_a_eqID, in_a_varID, in_a_clusterID) {
        (false, _, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        (_, a_eqID, a_varID, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_varID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -> eq") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(a_eqID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [style=\"bold\", arrowhead=\"none\"];") }))?;
            Ok(txt)
        }
        _ => Err("fun_34: no case matched"),
    } }
}

fn lm_35(mut txt: Tpl::Text, items: &metamodelica::List<i32>, mut a_clusterID: i32) -> Result<Tpl::Text> {
    for lstElt_35 in items {
        ::match_deref::match_deref! { match lstElt_35 {
            i_varID => {
                let mut x_eqID;
                let mut ret_0;
                x_eqID = Tpl::getIteri_i0(txt.clone())?;
                ret_0 = intGt(*i_varID, 0);
                txt = fun_34(txt, ret_0, x_eqID, *i_varID, a_clusterID)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_35: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_36(
    mut in_txt: Tpl::Text,
    in_a_matching: &metamodelica::Ref<BackendDAE::Matching>,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_matching, in_a_clusterID) {
        (Deref @ BackendDAE::Matching::MATCHING { ass2: i_ass2, .. }, a_clusterID) => {
            let mut txt = in_txt;
            let mut ret_1;
            let mut l_matchedNodes;
            ret_1 = arrayList(i_ass2.clone());
            l_matchedNodes = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_matchedNodes = lm_35(l_matchedNodes, &ret_1, a_clusterID)?;
            l_matchedNodes = Tpl::popIter(l_matchedNodes)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("// no adjacency matrix\n") }))?;
            txt = Tpl::writeText(txt, l_matchedNodes)?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("// no adjacency matrix\n"), literal!("// no matching")], lastHasNewLine: false }))?;
            Ok(txt)
        }
        _ => Err("fun_36: no case matched"),
    } }
}

fn fun_37(
    mut in_txt: Tpl::Text,
    in_a_m: &Option<metamodelica::Array<metamodelica::List<i32>>>,
    mut in_a_clusterID: i32,
    in_a_matching: &metamodelica::Ref<BackendDAE::Matching>,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_m, in_a_clusterID, in_a_matching) {
        (Some(i_incMatrix), a_clusterID, a_matching) => {
            let mut txt = in_txt;
            txt = fun_33(txt, a_matching, a_clusterID, i_incMatrix)?;
            Ok(txt)
        }
        (_, a_clusterID, a_matching) => {
            let mut txt = in_txt;
            txt = fun_36(txt, a_matching, a_clusterID)?;
            Ok(txt)
        }
        _ => Err("fun_37: no case matched"),
    } }
}

pub fn connections(
    mut txt: Tpl::Text,
    mut a_clusterID: i32,
    a_matching: &metamodelica::Ref<BackendDAE::Matching>,
    a_m: &Option<metamodelica::Array<metamodelica::List<i32>>>,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = fun_37(txt, a_m, a_clusterID, a_matching)?;
    Ok(out_txt)
}

fn lm_39(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<BackendDAE::Var>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_39 in items {
        ::match_deref::match_deref! { match lstElt_39 {
            Deref @ BackendDAE::Var { varName: i_var_varName, .. } => {
                let mut x_varID;
                x_varID = Tpl::getIteri_i0(txt.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
                txt = Tpl::writeStr(txt, intString(a_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
                txt = Tpl::writeStr(txt, intString(x_varID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [label=\"") }))?;
                txt = CodegenUtil::crefStr(txt, i_var_varName)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\", shape=\"box\"]") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

fn lm_40(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<BackendDAE::Equation>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_40 in items {
        ::match_deref::match_deref! { match lstElt_40 {
            i_eq => {
                let mut x_eqID;
                let mut ret_0;
                x_eqID = Tpl::getIteri_i0(txt.clone())?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("eq") }))?;
                txt = Tpl::writeStr(txt, intString(a_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
                txt = Tpl::writeStr(txt, intString(x_eqID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [label=\"") }))?;
                ret_0 = BackendDump::equationString(i_eq)?;
                txt = Tpl::writeStr(txt, ret_0)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\", shape=\"box\"]") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_40: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_41(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<BackendDAE::EqSystem>>) -> Result<Tpl::Text> {
    for lstElt_41 in items {
        ::match_deref::match_deref! { match lstElt_41 {
            Deref @ BackendDAE::EqSystem { orderedVars: i_eqSystem_orderedVars, orderedEqs: i_eqSystem_orderedEqs, matching: i_eqSystem_matching, .. } => {
                let mut x_clusterID;
                let mut ret_1;
                let mut l_varDeclaration;
                let mut ret_3;
                let mut l_eqDeclaration;
                x_clusterID = Tpl::getIteri_i0(txt.clone())?;
                ret_1 = BackendVariable::varList(i_eqSystem_orderedVars)?;
                l_varDeclaration = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_varDeclaration = lm_39(l_varDeclaration, &ret_1, x_clusterID)?;
                l_varDeclaration = Tpl::popIter(l_varDeclaration)?;
                ret_3 = BackendEquation::equationList(i_eqSystem_orderedEqs.clone())?;
                l_eqDeclaration = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
                l_eqDeclaration = lm_40(l_eqDeclaration, &ret_3, x_clusterID)?;
                l_eqDeclaration = Tpl::popIter(l_eqDeclaration)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("subgraph cluster_") }))?;
                txt = Tpl::writeStr(txt, intString(x_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(" {\n") }))?;
                txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("label = \"system #") }))?;
                txt = Tpl::writeStr(txt, intString(x_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\";\n"), literal!("color=white\n"), literal!("\n")], lastHasNewLine: true }))?;
                txt = Tpl::writeText(txt, l_varDeclaration)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
                txt = dumpStrongComponent(txt, x_clusterID, i_eqSystem_matching)?;
                txt = Tpl::softNewLine(txt)?;
                txt = Tpl::popBlock(txt)?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

pub fn dumpSorting(
    mut in_txt: Tpl::Text,
    in_a_backendDAE: &metamodelica::Ref<BackendDAE::BackendDAE>,
    in_a_suffix: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_backendDAE, in_a_suffix) {
        (Deref @ BackendDAE::BackendDAE { eqs: i_eqs, shared: Deref @ BackendDAE::Shared { info: BackendDAE::ExtraInfo { fileNamePrefix: i_info_fileNamePrefix, .. }, .. }, .. }, a_suffix) => {
            let mut txt = in_txt;
            let mut l_systems;
            l_systems = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("\n"), literal!("\n")], lastHasNewLine: true })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_systems = lm_41(l_systems, i_eqs)?;
            l_systems = Tpl::popIter(l_systems)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("digraph G {\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 2 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("label=\"") }))?;
            txt = Tpl::writeStr(txt, i_info_fileNamePrefix.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" [") }))?;
            txt = Tpl::writeStr(txt, a_suffix.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(" - sorting]\";\n"), literal!("rankdir=LR;\n"), literal!("\n")], lastHasNewLine: true }))?;
            txt = Tpl::writeText(txt, l_systems)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("}") }))?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpSorting: no case matched"),
    } }
}

fn lm_43(mut txt: Tpl::Text, items: &metamodelica::List<i32>, mut a_clusterID: i32) -> Result<Tpl::Text> {
    for lstElt_43 in items {
        ::match_deref::match_deref! { match lstElt_43 {
            i_v => {
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
                txt = Tpl::writeStr(txt, intString(a_clusterID))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
                txt = Tpl::writeStr(txt, intString(*i_v))?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_43: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_44(
    mut in_txt: Tpl::Text,
    in_a_comp: &metamodelica::Ref<BackendDAE::StrongComponent>,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_comp, in_a_clusterID) {
        (Deref @ BackendDAE::StrongComponent::SINGLEEQUATION { var: i_c_var, .. }, a_clusterID) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("var") }))?;
            txt = Tpl::writeStr(txt, intString(a_clusterID))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("_") }))?;
            txt = Tpl::writeStr(txt, intString(*i_c_var))?;
            Ok(txt)
        }
        (Deref @ BackendDAE::StrongComponent::EQUATIONSYSTEM { vars: i_c_vars, .. }, a_clusterID) => {
            let mut txt = in_txt;
            let mut l_foo;
            l_foo = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" <-> ") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_foo = lm_43(l_foo, i_c_vars, a_clusterID)?;
            l_foo = Tpl::popIter(l_foo)?;
            txt = Tpl::writeText(txt, l_foo)?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("asd") }))?;
            Ok(txt)
        }
        _ => Err("fun_44: no case matched"),
    } }
}

fn lm_45(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::Ref<BackendDAE::StrongComponent>>,
    mut a_clusterID: i32,
) -> Result<Tpl::Text> {
    for lstElt_45 in items {
        ::match_deref::match_deref! { match lstElt_45 {
            i_comp => {
                txt = fun_44(txt, i_comp, a_clusterID)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_45: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_46(
    mut in_txt: Tpl::Text,
    in_a_matching: &metamodelica::Ref<BackendDAE::Matching>,
    mut in_a_clusterID: i32,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_matching, in_a_clusterID) {
        (Deref @ BackendDAE::Matching::MATCHING { comps: i_comps, .. }, a_clusterID) => {
            let mut txt = in_txt;
            let mut l_cmpNodes;
            l_cmpNodes = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 1, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -> ") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_cmpNodes = lm_45(l_cmpNodes, i_comps, a_clusterID)?;
            l_cmpNodes = Tpl::popIter(l_cmpNodes)?;
            txt = Tpl::writeText(txt, l_cmpNodes)?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_46: no case matched"),
    } }
}

pub fn dumpStrongComponent(
    mut txt: Tpl::Text,
    mut a_clusterID: i32,
    a_matching: &metamodelica::Ref<BackendDAE::Matching>,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = fun_46(txt, a_matching, a_clusterID)?;
    Ok(out_txt)
}
