// Generated by Susan from SimCodeDump.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use openmodelica_codegen_util::CodegenUtil;
use openmodelica_frontend_dump::ExpressionDumpTpl;
use openmodelica_frontend_types::DAE;
use openmodelica_simcode_types::SimCodeVar;
use openmodelica_tpl::Tpl;
use openmodelica_util::Util;

fn lm_47(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<SimCodeVar::SimVar>>) -> Result<Tpl::Text> {
    for lstElt_47 in items {
        ::match_deref::match_deref! { match lstElt_47 {
            Deref @ SimCodeVar::SimVar { name: i_v_name, .. } => {
                let mut x_index0;
                let mut txt_0;
                let mut ret_1;
                x_index0 = Tpl::getIteri_i0(txt.clone())?;
                txt = Tpl::writeStr(txt, intString(x_index0))?;
                txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(": ") }))?;
                txt_0 = CodegenUtil::crefStrNoUnderscore((*Tpl::emptyTxt).clone(), i_v_name)?;
                ret_1 = Util::escapeModelicaStringToXmlString(Tpl::textString(txt_0)?)?;
                txt = Tpl::writeStr(txt, ret_1)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => {
            }
        } }
    }
    Ok(txt)
}

pub fn dumpVarsShort(
    mut txt: Tpl::Text,
    a_vars: &metamodelica::List<metamodelica::Ref<SimCodeVar::SimVar>>,
) -> Result<Tpl::Text> {
    let mut l_varsString;
    let mut out_txt;
    l_varsString = Tpl::pushIter(
        (*Tpl::emptyTxt).clone(),
        metamodelica::Ref::new(Tpl::IterOptions {
            startIndex0: 0,
            empty: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING {
                value: literal!(""),
            })),
            separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)),
            alignNum: 0,
            alignOfset: 0,
            alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
            wrapWidth: 0,
            wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
        }),
    )?;
    l_varsString = lm_47(l_varsString, a_vars)?;
    l_varsString = Tpl::popIter(l_varsString)?;
    out_txt = Tpl::writeText(txt, l_varsString)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(out_txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
    Ok(out_txt)
}

pub fn dumpAlias(mut in_txt: Tpl::Text, in_a_alias: &SimCodeVar::AliasVariable) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_alias {
        SimCodeVar::AliasVariable::ALIAS { varName: i_varName, .. } => {
            let mut txt = in_txt;
            let mut txt_0;
            let mut ret_1;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<alias>") }))?;
            txt_0 = CodegenUtil::crefStrNoUnderscore((*Tpl::emptyTxt).clone(), i_varName)?;
            ret_1 = Util::escapeModelicaStringToXmlString(Tpl::textString(txt_0)?)?;
            txt = Tpl::writeStr(txt, ret_1)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</alias>") }))?;
            Ok(txt)
        }
        SimCodeVar::AliasVariable::NEGATEDALIAS { varName: i_varName, .. } => {
            let mut txt = in_txt;
            let mut txt_2;
            let mut ret_3;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 1 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<alias negated=\"true\">") }))?;
            txt_2 = CodegenUtil::crefStrNoUnderscore((*Tpl::emptyTxt).clone(), i_varName)?;
            ret_3 = Util::escapeModelicaStringToXmlString(Tpl::textString(txt_2)?)?;
            txt = Tpl::writeStr(txt, ret_3)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</alias>") }))?;
            txt = Tpl::popBlock(txt)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpAlias: no case matched"),
    } }
}

pub fn printExpStrEscaped(mut txt: Tpl::Text, a_exp: &metamodelica::Ref<DAE::Exp>) -> Result<Tpl::Text> {
    let mut txt_0;
    let mut ret_1;
    let mut out_txt;
    txt_0 = ExpressionDumpTpl::dumpExp((*Tpl::emptyTxt).clone(), a_exp, &literal!("\""))?;
    ret_1 = Util::escapeModelicaStringToXmlString(Tpl::textString(txt_0)?)?;
    out_txt = Tpl::writeStr(txt, ret_1)?;
    Ok(out_txt)
}
