// Generated by Susan from VisualXMLTpl.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use crate::VisualXML;
use openmodelica_frontend_dump::AbsynUtil;
use openmodelica_frontend_dump::ComponentReferenceBasics;
use openmodelica_frontend_dump::ExpressionBasics;
use openmodelica_frontend_types::DAE;
use openmodelica_tpl::Tpl;

pub fn dumpVisXML(
    mut txt: Tpl::Text,
    a_vis: &metamodelica::Array<VisualXML::Visualization>,
    a_fileName: &ArcStr,
) -> Result<Tpl::Text> {
    let mut txt_0;
    let mut out_txt;
    txt_0 = dumpVisXML1((*Tpl::emptyTxt).clone(), a_vis)?;
    Tpl::textFile(txt_0, a_fileName.clone())?;
    out_txt = txt;
    Ok(out_txt)
}

fn lm_9(mut txt: Tpl::Text, items: &metamodelica::List<VisualXML::Visualization>) -> Result<Tpl::Text> {
    for lstElt_9 in items {
        ::match_deref::match_deref! { match lstElt_9 {
            i_vis => {
                txt = dumpVisualization(txt, i_vis)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_9: no case matched"),
        } }
    }
    Ok(txt)
}

pub fn dumpVisXML1(mut txt: Tpl::Text, a_visArr: &metamodelica::Array<VisualXML::Visualization>) -> Result<Tpl::Text> {
    let mut ret_1;
    let mut l_visDump;
    let mut out_txt;
    ret_1 = arrayList(a_visArr.clone());
    l_visDump = Tpl::pushIter(
        (*Tpl::emptyTxt).clone(),
        metamodelica::Ref::new(Tpl::IterOptions {
            startIndex0: 0,
            empty: None,
            separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)),
            alignNum: 0,
            alignOfset: 0,
            alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
            wrapWidth: 0,
            wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
        }),
    )?;
    l_visDump = lm_9(l_visDump, &ret_1)?;
    l_visDump = Tpl::popIter(l_visDump)?;
    out_txt = Tpl::writeTok(
        txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST {
            strList: metamodelica::list![
                literal!("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"),
                literal!("<visualization>\n")
            ],
            lastHasNewLine: true,
        }),
    )?;
    out_txt = Tpl::writeText(out_txt, l_visDump)?;
    out_txt = Tpl::softNewLine(out_txt)?;
    out_txt = Tpl::writeTok(
        out_txt,
        metamodelica::Ref::new(Tpl::StringToken::ST_STRING {
            value: literal!("</visualization>"),
        }),
    )?;
    Ok(out_txt)
}

fn lm_11(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::List<metamodelica::Ref<DAE::Exp>>>,
) -> Result<Tpl::Text> {
    for lstElt_11 in items {
        ::match_deref::match_deref! { match lstElt_11 {
            i_T0 => {
                txt = dumpVecExp(txt, i_T0)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_11: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_12(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::List<metamodelica::Ref<DAE::Exp>>>,
) -> Result<Tpl::Text> {
    for lstElt_12 in items {
        ::match_deref::match_deref! { match lstElt_12 {
            i_T0 => {
                txt = dumpVecExp(txt, i_T0)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_12: no case matched"),
        } }
    }
    Ok(txt)
}

fn lm_13(
    mut txt: Tpl::Text,
    items: &metamodelica::List<metamodelica::List<metamodelica::Ref<DAE::Exp>>>,
) -> Result<Tpl::Text> {
    for lstElt_13 in items {
        ::match_deref::match_deref! { match lstElt_13 {
            i_T0 => {
                txt = dumpVecExp(txt, i_T0)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_13: no case matched"),
        } }
    }
    Ok(txt)
}

pub fn dumpVisualization(mut in_txt: Tpl::Text, in_a_vis: &VisualXML::Visualization) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_vis {
        VisualXML::Visualization::SHAPE { shapeType: Deref @ DAE::Exp::SCONST { string: i_svalue, .. }, T: i_T, r: i_r, r_shape: i_r__shape, lengthDir: i_lengthDir, widthDir: i_widthDir, color: i_color, ident: i_ident, length: i_length, width: i_width, height: i_height, extra: i_extra, specularCoeff: i_specularCoeff, .. } => {
            let mut txt = in_txt;
            let mut ret_1;
            let mut l_TDump;
            let mut ret_3;
            let mut l_rDump;
            let mut ret_5;
            let mut l_r__shapeDump;
            let mut ret_7;
            let mut l_lDirDump;
            let mut ret_9;
            let mut l_wDirDump;
            let mut ret_11;
            let mut l_colorDump;
            let mut ret_12;
            ret_1 = arrayList(i_T.clone());
            l_TDump = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_TDump = lm_11(l_TDump, &ret_1)?;
            l_TDump = Tpl::popIter(l_TDump)?;
            ret_3 = arrayList(i_r.clone());
            l_rDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_3)?;
            ret_5 = arrayList(i_r__shape.clone());
            l_r__shapeDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_5)?;
            ret_7 = arrayList(i_lengthDir.clone());
            l_lDirDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_7)?;
            ret_9 = arrayList(i_widthDir.clone());
            l_wDirDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_9)?;
            ret_11 = arrayList(i_color.clone());
            l_colorDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_11)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("  <shape>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 6 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<ident>") }))?;
            ret_12 = ComponentReferenceBasics::printComponentRefStr(i_ident)?;
            txt = Tpl::writeStr(txt, ret_12)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</ident>\n"), literal!("<type>")], lastHasNewLine: false }))?;
            txt = Tpl::writeStr(txt, i_svalue.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</type>\n"), literal!("<T>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_TDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</T>\n"), literal!("<r>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_rDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</r>\n"), literal!("<r_shape>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_r__shapeDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</r_shape>\n"), literal!("<lengthDir>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_lDirDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</lengthDir>\n"), literal!("<widthDir>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_wDirDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</widthDir>\n"), literal!("<length>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_length)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</length>\n"), literal!("<width>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_width)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</width>\n"), literal!("<height>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_height)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</height>\n"), literal!("<extra>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_extra)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</extra>\n"), literal!("<color>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_colorDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</color>\n"), literal!("<specCoeff>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_specularCoeff)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</specCoeff>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("  </shape>") }))?;
            Ok(txt)
        }
        VisualXML::Visualization::VECTOR { T: i_T, r: i_r, coordinates: i_coordinates, color: i_color, ident: i_ident, specularCoeff: i_specularCoeff, quantity: i_quantity, headAtOrigin: i_headAtOrigin, twoHeadedArrow: i_twoHeadedArrow, .. } => {
            let mut txt = in_txt;
            let mut ret_13;
            let mut l_TDump;
            let mut ret_14;
            let mut l_rDump;
            let mut ret_16;
            let mut l_coordDump;
            let mut ret_17;
            let mut l_colorDump;
            let mut ret_18;
            ret_13 = arrayList(i_T.clone());
            l_TDump = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_TDump = lm_12(l_TDump, &ret_13)?;
            l_TDump = Tpl::popIter(l_TDump)?;
            ret_14 = arrayList(i_r.clone());
            l_rDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_14)?;
            ret_16 = arrayList(i_coordinates.clone());
            l_coordDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_16)?;
            ret_17 = arrayList(i_color.clone());
            l_colorDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_17)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("  <vector>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 6 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<ident>") }))?;
            ret_18 = ComponentReferenceBasics::printComponentRefStr(i_ident)?;
            txt = Tpl::writeStr(txt, ret_18)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</ident>\n"), literal!("<T>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_TDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</T>\n"), literal!("<r>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_rDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</r>\n"), literal!("<coordinates>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_coordDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</coordinates>\n"), literal!("<color>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_colorDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</color>\n"), literal!("<specCoeff>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_specularCoeff)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</specCoeff>\n"), literal!("<quantity>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_quantity)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</quantity>\n"), literal!("<headAtOrigin>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_headAtOrigin)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</headAtOrigin>\n"), literal!("<twoHeadedArrow>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_twoHeadedArrow)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</twoHeadedArrow>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("  </vector>") }))?;
            Ok(txt)
        }
        VisualXML::Visualization::SURFACE { T: i_T, r_0: i_r__0, color: i_color, ident: i_ident, nu: i_nu, nv: i_nv, wireframe: i_wireframe, multiColored: i_multiColored, specularCoeff: i_specularCoeff, transparency: i_transparency, .. } => {
            let mut txt = in_txt;
            let mut ret_19;
            let mut l_TDump;
            let mut ret_21;
            let mut l_r__0Dump;
            let mut ret_22;
            let mut l_colorDump;
            let mut ret_23;
            ret_19 = arrayList(i_T.clone());
            l_TDump = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_TDump = lm_13(l_TDump, &ret_19)?;
            l_TDump = Tpl::popIter(l_TDump)?;
            ret_21 = arrayList(i_r__0.clone());
            l_r__0Dump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_21)?;
            ret_22 = arrayList(i_color.clone());
            l_colorDump = dumpVecExp((*Tpl::emptyTxt).clone(), &ret_22)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("  <surface>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 6 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<ident>") }))?;
            ret_23 = ComponentReferenceBasics::printComponentRefStr(i_ident)?;
            txt = Tpl::writeStr(txt, ret_23)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</ident>\n"), literal!("<T>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_TDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</T>\n"), literal!("<r>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_r__0Dump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</r>\n"), literal!("<nu>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_nu)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</nu>\n"), literal!("<nv>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_nv)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</nv>\n"), literal!("<wireframe>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_wireframe)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</wireframe>\n"), literal!("<multiColored>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_multiColored)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</multiColored>\n"), literal!("<color>\n")], lastHasNewLine: true }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeText(txt, l_colorDump)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</color>\n"), literal!("<specCoeff>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_specularCoeff)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</specCoeff>\n"), literal!("<transparency>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_transparency)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</transparency>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("  </surface>") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("dumpVisualization: no case matched"),
    } }
}

fn lm_15(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<DAE::Exp>>) -> Result<Tpl::Text> {
    for lstElt_15 in items {
        ::match_deref::match_deref! { match lstElt_15 {
            i_vec => {
                txt = dumpExp(txt, i_vec)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_15: no case matched"),
        } }
    }
    Ok(txt)
}

pub fn dumpVecExp(mut txt: Tpl::Text, a_vector: &metamodelica::List<metamodelica::Ref<DAE::Exp>>) -> Result<Tpl::Text> {
    let mut l_vecDump;
    let mut out_txt;
    l_vecDump = Tpl::pushIter(
        (*Tpl::emptyTxt).clone(),
        metamodelica::Ref::new(Tpl::IterOptions {
            startIndex0: 0,
            empty: None,
            separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)),
            alignNum: 0,
            alignOfset: 0,
            alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
            wrapWidth: 0,
            wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE),
        }),
    )?;
    l_vecDump = lm_15(l_vecDump, a_vector)?;
    l_vecDump = Tpl::popIter(l_vecDump)?;
    out_txt = Tpl::writeText(txt, l_vecDump)?;
    Ok(out_txt)
}

fn lm_17(mut txt: Tpl::Text, items: &metamodelica::List<metamodelica::Ref<DAE::Exp>>) -> Result<Tpl::Text> {
    for lstElt_17 in items {
        ::match_deref::match_deref! { match lstElt_17 {
            i_e => {
                txt = dumpExp(txt, i_e)?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_17: no case matched"),
        } }
    }
    Ok(txt)
}

pub fn dumpExp(mut in_txt: Tpl::Text, in_a_expIn: &metamodelica::Ref<DAE::Exp>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_expIn {
        Deref @ DAE::Exp::ENUM_LITERAL { index: i_index, .. } => {
            let mut txt = in_txt;
            let mut ret_0;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<enum>") }))?;
            ret_0 = intString(*i_index);
            txt = Tpl::writeStr(txt, ret_0)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</enum>") }))?;
            Ok(txt)
        }
        i_expIn @ Deref @ DAE::Exp::BCONST { .. } => {
            let mut txt = in_txt;
            let mut ret_1;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<bconst>") }))?;
            ret_1 = ExpressionBasics::printExpStr(i_expIn.clone())?;
            txt = Tpl::writeStr(txt, ret_1)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</bconst>") }))?;
            Ok(txt)
        }
        i_expIn @ Deref @ DAE::Exp::CREF { .. } => {
            let mut txt = in_txt;
            let mut ret_2;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<cref>") }))?;
            ret_2 = ExpressionBasics::printExpStr(i_expIn.clone())?;
            txt = Tpl::writeStr(txt, ret_2)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</cref>") }))?;
            Ok(txt)
        }
        Deref @ DAE::Exp::BINARY { exp1: i_exp1, operator: i_operator, exp2: i_exp2, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<binary>\n") }))?;
            txt = dumpExp(txt, i_exp1)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<op>") }))?;
            txt = dumpOperator(txt, i_operator)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</op>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = dumpExp(txt, i_exp2)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</binary>") }))?;
            Ok(txt)
        }
        Deref @ DAE::Exp::UNARY { operator: i_operator, exp: i_exp, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<unary>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<op>") }))?;
            txt = dumpOperator(txt, i_operator)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</op>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = dumpExp(txt, i_exp)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</unary>") }))?;
            Ok(txt)
        }
        Deref @ DAE::Exp::LBINARY { exp1: i_exp1, operator: i_operator, exp2: i_exp2, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<lbinary>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = dumpExp(txt, i_exp1)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<op>") }))?;
            txt = dumpOperator(txt, i_operator)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</op>\n") }))?;
            txt = dumpExp(txt, i_exp2)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</lbinary>") }))?;
            Ok(txt)
        }
        Deref @ DAE::Exp::LUNARY { operator: i_operator, exp: i_exp, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<lunary>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<op>") }))?;
            txt = dumpOperator(txt, i_operator)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</op>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = dumpExp(txt, i_exp)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</lunary>") }))?;
            Ok(txt)
        }
        Deref @ DAE::Exp::RELATION { exp1: i_exp1, operator: i_operator, exp2: i_exp2, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<relation>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<exp1>") }))?;
            txt = dumpExp(txt, i_exp1)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</exp1>\n"), literal!("<op>")], lastHasNewLine: false }))?;
            txt = dumpOperator(txt, i_operator)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</op>\n"), literal!("<exp2>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_exp2)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</exp2>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</relation>") }))?;
            Ok(txt)
        }
        Deref @ DAE::Exp::IFEXP { expCond: i_expCond, expThen: i_expThen, expElse: i_expElse, .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<ifexp>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<cond>") }))?;
            txt = dumpExp(txt, i_expCond)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</cond>\n"), literal!("<then>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_expThen)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</then>\n"), literal!("<else>")], lastHasNewLine: false }))?;
            txt = dumpExp(txt, i_expElse)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</else>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</ifexp>") }))?;
            Ok(txt)
        }
        Deref @ DAE::Exp::CALL { expLst: i_expLst, path: i_path, .. } => {
            let mut txt = in_txt;
            let mut l_elist;
            let mut ret_4;
            l_elist = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE)), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_elist = lm_17(l_elist, i_expLst)?;
            l_elist = Tpl::popIter(l_elist)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("<call>\n") }))?;
            txt = Tpl::pushBlock(txt, metamodelica::Ref::new(Tpl::BlockType::BT_INDENT { width: 4 }))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<path>") }))?;
            ret_4 = AbsynUtil::pathString(i_path.clone(), literal!("."), true, false)?;
            txt = Tpl::writeStr(txt, ret_4)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("</path>\n"), literal!("<expLst>")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, l_elist)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("</expLst>\n") }))?;
            txt = Tpl::popBlock(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</call>") }))?;
            Ok(txt)
        }
        i_expIn => {
            let mut txt = in_txt;
            let mut ret_5;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("<exp>") }))?;
            ret_5 = ExpressionBasics::printExpStr(i_expIn.clone())?;
            txt = Tpl::writeStr(txt, ret_5)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("</exp>") }))?;
            Ok(txt)
        }
        _ => Err("dumpExp: no case matched"),
    } }
}

pub fn dumpOperator(mut in_txt: Tpl::Text, in_a_op: &DAE::Operator) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_op {
        DAE::Operator::ADD { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("add") }))?;
            Ok(txt)
        }
        DAE::Operator::SUB { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("sub") }))?;
            Ok(txt)
        }
        DAE::Operator::MUL { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("mul") }))?;
            Ok(txt)
        }
        DAE::Operator::DIV { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("div") }))?;
            Ok(txt)
        }
        DAE::Operator::POW { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("pow") }))?;
            Ok(txt)
        }
        DAE::Operator::UMINUS { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("uminus") }))?;
            Ok(txt)
        }
        DAE::Operator::UMINUS_ARR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("uminus_arr") }))?;
            Ok(txt)
        }
        DAE::Operator::ADD_ARR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("add_arr") }))?;
            Ok(txt)
        }
        DAE::Operator::SUB_ARR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("sub_arr") }))?;
            Ok(txt)
        }
        DAE::Operator::MUL_ARR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("mul_arr") }))?;
            Ok(txt)
        }
        DAE::Operator::DIV_ARR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("siv_arr") }))?;
            Ok(txt)
        }
        DAE::Operator::MUL_ARRAY_SCALAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("mul_array_scalar") }))?;
            Ok(txt)
        }
        DAE::Operator::ADD_ARRAY_SCALAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("add_array_scalar") }))?;
            Ok(txt)
        }
        DAE::Operator::SUB_SCALAR_ARRAY { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("sub_scalar_array") }))?;
            Ok(txt)
        }
        DAE::Operator::MUL_SCALAR_PRODUCT { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("mul_scalar_product") }))?;
            Ok(txt)
        }
        DAE::Operator::MUL_MATRIX_PRODUCT { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("mul_matrix_product") }))?;
            Ok(txt)
        }
        DAE::Operator::DIV_ARRAY_SCALAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("div_array_scalar") }))?;
            Ok(txt)
        }
        DAE::Operator::DIV_SCALAR_ARRAY { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("siv_scalar_array") }))?;
            Ok(txt)
        }
        DAE::Operator::POW_ARRAY_SCALAR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("pow_array_scalar") }))?;
            Ok(txt)
        }
        DAE::Operator::POW_SCALAR_ARRAY { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("pow_scalar_array") }))?;
            Ok(txt)
        }
        DAE::Operator::POW_ARR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("pow_arr") }))?;
            Ok(txt)
        }
        DAE::Operator::POW_ARR2 { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("por_arr2") }))?;
            Ok(txt)
        }
        DAE::Operator::AND { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("and") }))?;
            Ok(txt)
        }
        DAE::Operator::OR { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("or") }))?;
            Ok(txt)
        }
        DAE::Operator::NOT { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("not") }))?;
            Ok(txt)
        }
        DAE::Operator::LESS { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("less") }))?;
            Ok(txt)
        }
        DAE::Operator::LESSEQ { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("lesseq") }))?;
            Ok(txt)
        }
        DAE::Operator::GREATER { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("greater") }))?;
            Ok(txt)
        }
        DAE::Operator::GREATEREQ { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("greatereq") }))?;
            Ok(txt)
        }
        DAE::Operator::EQUAL { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("equal") }))?;
            Ok(txt)
        }
        DAE::Operator::NEQUAL { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("nequal") }))?;
            Ok(txt)
        }
        DAE::Operator::USERDEFINED { .. } => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("userdefined") }))?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-unknown operator-") }))?;
            Ok(txt)
        }
        _ => Err("dumpOperator: no case matched"),
    } }
}
