// Generated by Susan from CodegenOMSICpp.tpl.
#![allow(warnings)]

use arcstr::{ArcStr, literal};
use metamodelica::Result;
use metamodelica::*;

use openmodelica_codegen_cpp_omsi::CodegenCppOMSI;
use openmodelica_codegen_util::CodegenUtil;
use openmodelica_simcode_types::SimCode;
use openmodelica_simcode_types::SimCodeFunction;
use openmodelica_tpl::Tpl;
use openmodelica_util::Config;
use openmodelica_util::Flags;
use openmodelica_util::System;
use openmodelica_util::Testsuite;

fn fun_49(mut in_txt: Tpl::Text, in_a_simCode: &metamodelica::Ref<SimCode::SimCode>) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_simCode {
        i_simCode @ Deref @ SimCode::SimCode { modelInfo: SimCode::ModelInfo { name: i_modelInfo_name, .. }, .. } => {
            let mut txt = in_txt;
            let mut l_extraFuncs;
            let mut l_extraFuncsDecl;
            let mut txt_2;
            let mut txt_3;
            l_extraFuncs = (*Tpl::emptyTxt).clone();
            l_extraFuncsDecl = (*Tpl::emptyTxt).clone();
            (txt_2, l_extraFuncs, l_extraFuncsDecl, _) = simulationOMSUCPPMainRunScript((*Tpl::emptyTxt).clone(), i_simCode, l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })), &literal!(""), &literal!(""), &literal!("exec"))?;
            txt_3 = CodegenUtil::dotPath((*Tpl::emptyTxt).clone(), i_modelInfo_name)?;
            (txt_3, l_extraFuncs, l_extraFuncsDecl, _) = CodegenCppOMSI::simulationMainRunScriptSuffix(txt_3, i_simCode, l_extraFuncs, l_extraFuncsDecl, Tpl::strTokText(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("") })))?;
            Tpl::textFile(txt_2, Tpl::textString(txt_3)?)?;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_49: no case matched"),
    } }
}

pub fn translateModel(
    mut txt: Tpl::Text,
    a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    a_FMUVersion: &ArcStr,
    a_FMUType: &ArcStr,
) -> Result<Tpl::Text> {
    let mut out_txt;
    out_txt = fun_49(txt, a_simCode)?;
    Ok(out_txt)
}

fn fun_51(
    mut in_txt: Tpl::Text,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    in_a_settings_method: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_simCode, in_a_settings_method) {
        (Deref @ SimCode::SimCode { daeModeData: None, .. }, a_settings_method) => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, a_settings_method.clone())?;
            Ok(txt)
        }
        (_, _) => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("ida") }))?;
            Ok(txt)
        }
        _ => Err("fun_51: no case matched"),
    } }
}

fn fun_52(mut in_txt: Tpl::Text, in_a_makefileParams_platform: &ArcStr) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_a_makefileParams_platform {
        Deref @ "i386-pc-linux" => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("linux32") }))?;
            Ok(txt)
        }
        Deref @ "x86_64-linux" => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("linux64") }))?;
            Ok(txt)
        }
        i_makefileParams_platform => {
            let mut txt = in_txt;
            txt = Tpl::writeStr(txt, i_makefileParams_platform.clone())?;
            Ok(txt)
        }
        _ => Err("fun_52: no case matched"),
    } }
}

fn fun_53(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-O none") }))?;
            Ok(txt)
        }
        _ => Err("fun_53: no case matched"),
    } }
}

fn lm_54(mut txt: Tpl::Text, items: &metamodelica::List<ArcStr>) -> Result<Tpl::Text> {
    for lstElt_54 in items {
        ::match_deref::match_deref! { match lstElt_54 {
            i_path => {
                txt = Tpl::writeStr(txt, i_path.clone())?;
                txt = Tpl::nextIter(txt)?;
            }
            _ => return Err("lm_54: no case matched"),
        } }
    }
    Ok(txt)
}

fn fun_55(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut ret_0;
            let mut ret_1;
            let mut ret_2;
            let mut ret_3;
            let mut ret_4;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-u true -p ") }))?;
            ret_0 = Flags::getConfigInt(Flags::ZEROMQ_PUB_PORT.clone())?;
            txt = Tpl::writeStr(txt, intString(ret_0))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -s ") }))?;
            ret_1 = Flags::getConfigInt(Flags::ZEROMQ_SUB_PORT.clone())?;
            txt = Tpl::writeStr(txt, intString(ret_1))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -v ") }))?;
            ret_2 = Flags::getConfigString(Flags::ZEROMQ_SERVER_ID.clone())?;
            txt = Tpl::writeStr(txt, ret_2)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -c ") }))?;
            ret_3 = Flags::getConfigString(Flags::ZEROMQ_CLIENT_ID.clone())?;
            txt = Tpl::writeStr(txt, ret_3)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -g ") }))?;
            ret_4 = Flags::getConfigString(Flags::ZEROMQ_JOB_ID.clone())?;
            txt = Tpl::writeStr(txt, ret_4)?;
            Ok(txt)
        }
        _ => Err("fun_55: no case matched"),
    } }
}

fn fun_56(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    mut in_a_home: Tpl::Text,
    mut in_a_omPlatform: Tpl::Text,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut a_home = in_a_home;
            let mut a_omPlatform = in_a_omPlatform;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("if defined OMDEV set OMC_MSYS=%OMDEV%\\\\tools\\\\msys\\\\") }))?;
            txt = Tpl::writeText(txt, a_omPlatform.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("if not defined OMDEV set OMC_MSYS=") }))?;
            txt = Tpl::writeText(txt, a_home)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\\\\tools\\\\msys\\\\") }))?;
            txt = Tpl::writeText(txt, a_omPlatform)?;
            Ok(txt)
        }
        _ => Err("fun_56: no case matched"),
    } }
}

fn fun_57(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut ret_0;
            let mut ret_1;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";%OMC_MSYS%\\\\bin;%OMC_MSYS%\\\\lib\\\\gcc\\\\") }))?;
            ret_0 = System::gccDumpMachine();
            txt = Tpl::writeStr(txt, ret_0)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\\\\") }))?;
            ret_1 = System::gccVersion();
            txt = Tpl::writeStr(txt, ret_1)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";%OMC_MSYS%\\\\..\\\\usr\\\\bin") }))?;
            Ok(txt)
        }
        _ => Err("fun_57: no case matched"),
    } }
}

fn fun_58(
    mut in_txt: Tpl::Text,
    mut in_mArg: bool,
    mut in_a_home: Tpl::Text,
    mut in_a_omPlatform: Tpl::Text,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut a_home = in_a_home;
            let mut a_omPlatform = in_a_omPlatform;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("if defined OMDEV set OMC_MSYS=%OMDEV%\\\\tools\\\\msys\\\\") }))?;
            txt = Tpl::writeText(txt, a_omPlatform.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE))?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("if not defined OMDEV set OMC_MSYS=") }))?;
            txt = Tpl::writeText(txt, a_home)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\\\\tools\\\\msys\\\\") }))?;
            txt = Tpl::writeText(txt, a_omPlatform)?;
            Ok(txt)
        }
        _ => Err("fun_58: no case matched"),
    } }
}

fn fun_59(mut in_txt: Tpl::Text, mut in_mArg: bool) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match in_mArg {
        false => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => {
            let mut txt = in_txt;
            let mut ret_0;
            let mut ret_1;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";%OMC_MSYS%\\\\bin;%OMC_MSYS%\\\\lib\\\\gcc\\\\") }))?;
            ret_0 = System::gccDumpMachine();
            txt = Tpl::writeStr(txt, ret_0)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("\\\\") }))?;
            ret_1 = System::gccVersion();
            txt = Tpl::writeStr(txt, ret_1)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";%OMC_MSYS%\\\\..\\\\usr\\\\bin") }))?;
            Ok(txt)
        }
        _ => Err("fun_59: no case matched"),
    } }
}

fn fun_60(
    mut in_txt: Tpl::Text,
    in_a_makefileParams_platform: &ArcStr,
    in_a_preRunCommandWindows: &ArcStr,
    mut in_a_libPaths: Tpl::Text,
    mut in_a_libFolder: Tpl::Text,
    mut in_a_home: Tpl::Text,
    mut in_a_outputParameter: Tpl::Text,
    mut in_a_zermMQParams: Tpl::Text,
    mut in_a_execParameters: Tpl::Text,
    mut in_a_binFolder: Tpl::Text,
    in_a_execCommandLinux: &ArcStr,
    in_a_preRunCommandLinux: &ArcStr,
) -> Result<Tpl::Text> {
    ::match_deref::match_deref! { match (in_a_makefileParams_platform, in_a_preRunCommandWindows, in_a_execCommandLinux, in_a_preRunCommandLinux) {
        (Deref @ "linux32", _, a_execCommandLinux, a_preRunCommandLinux) => {
            let mut txt = in_txt;
            let mut a_outputParameter = in_a_outputParameter;
            let mut a_zermMQParams = in_a_zermMQParams;
            let mut a_execParameters = in_a_execParameters;
            let mut a_binFolder = in_a_binFolder;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("#!/bin/sh\n") }))?;
            txt = Tpl::writeStr(txt, a_preRunCommandLinux.clone())?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeStr(txt, a_execCommandLinux.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_binFolder)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("/OMCppOSUSimulation ") }))?;
            txt = Tpl::writeText(txt, a_execParameters)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_zermMQParams)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_outputParameter)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" $*") }))?;
            Ok(txt)
        }
        (Deref @ "linux64", _, a_execCommandLinux, a_preRunCommandLinux) => {
            let mut txt = in_txt;
            let mut a_outputParameter = in_a_outputParameter;
            let mut a_zermMQParams = in_a_zermMQParams;
            let mut a_execParameters = in_a_execParameters;
            let mut a_binFolder = in_a_binFolder;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!("#!/bin/sh\n") }))?;
            txt = Tpl::writeStr(txt, a_preRunCommandLinux.clone())?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeStr(txt, a_execCommandLinux.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_binFolder)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("/OMCppOSUSimulation ") }))?;
            txt = Tpl::writeText(txt, a_execParameters)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_zermMQParams)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_outputParameter)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" $*") }))?;
            Ok(txt)
        }
        (Deref @ "win32", a_preRunCommandWindows, _, _) => {
            let mut txt = in_txt;
            let mut a_libPaths = in_a_libPaths;
            let mut a_libFolder = in_a_libFolder;
            let mut a_home = in_a_home;
            let mut a_outputParameter = in_a_outputParameter;
            let mut a_zermMQParams = in_a_zermMQParams;
            let mut a_execParameters = in_a_execParameters;
            let mut a_binFolder = in_a_binFolder;
            let mut ret_1;
            let mut l_omPlatform;
            let mut ret_3;
            let mut ret_4;
            let mut l_msysPath;
            let mut ret_6;
            let mut ret_7;
            let mut l_msysPathEntries;
            ret_1 = System::openModelicaPlatform();
            l_omPlatform = Tpl::writeStr((*Tpl::emptyTxt).clone(), ret_1)?;
            ret_3 = System::stringFind(Tpl::textString(l_omPlatform.clone())?, literal!("msvc"))?;
            ret_4 = intEq(-1, ret_3);
            l_msysPath = fun_56((*Tpl::emptyTxt).clone(), ret_4, a_home, l_omPlatform.clone())?;
            ret_6 = System::stringFind(Tpl::textString(l_omPlatform)?, literal!("msvc"))?;
            ret_7 = intEq(-1, ret_6);
            l_msysPathEntries = fun_57((*Tpl::emptyTxt).clone(), ret_7)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("@echo off\n"), literal!("setlocal\n")], lastHasNewLine: true }))?;
            txt = Tpl::writeText(txt, l_msysPath)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("SET PATH=") }))?;
            txt = Tpl::writeText(txt, a_binFolder)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            txt = Tpl::writeText(txt, a_libFolder.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            txt = Tpl::writeText(txt, a_libPaths)?;
            txt = Tpl::writeText(txt, l_msysPathEntries)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(";%PATH%\n"), literal!("REM ::export PATH=")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, a_libFolder)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(":$PATH REPLACE C: with /C/\n") }))?;
            txt = Tpl::writeStr(txt, a_preRunCommandWindows.clone())?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OMCppOSUSimulation.exe ") }))?;
            txt = Tpl::writeText(txt, a_execParameters)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_zermMQParams)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_outputParameter)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("endlocal") }))?;
            Ok(txt)
        }
        (Deref @ "win64", a_preRunCommandWindows, _, _) => {
            let mut txt = in_txt;
            let mut a_libPaths = in_a_libPaths;
            let mut a_libFolder = in_a_libFolder;
            let mut a_home = in_a_home;
            let mut a_outputParameter = in_a_outputParameter;
            let mut a_zermMQParams = in_a_zermMQParams;
            let mut a_execParameters = in_a_execParameters;
            let mut a_binFolder = in_a_binFolder;
            let mut ret_8;
            let mut l_omPlatform;
            let mut ret_9;
            let mut ret_10;
            let mut l_msysPath;
            let mut ret_11;
            let mut ret_12;
            let mut l_msysPathEntries;
            ret_8 = System::openModelicaPlatform();
            l_omPlatform = Tpl::writeStr((*Tpl::emptyTxt).clone(), ret_8)?;
            ret_9 = System::stringFind(Tpl::textString(l_omPlatform.clone())?, literal!("msvc"))?;
            ret_10 = intEq(-1, ret_9);
            l_msysPath = fun_58((*Tpl::emptyTxt).clone(), ret_10, a_home, l_omPlatform.clone())?;
            ret_11 = System::stringFind(Tpl::textString(l_omPlatform)?, literal!("msvc"))?;
            ret_12 = intEq(-1, ret_11);
            l_msysPathEntries = fun_59((*Tpl::emptyTxt).clone(), ret_12)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!("@echo off\n"), literal!("setlocal\n")], lastHasNewLine: true }))?;
            txt = Tpl::writeText(txt, l_msysPath)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("SET PATH=") }))?;
            txt = Tpl::writeText(txt, a_binFolder)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            txt = Tpl::writeText(txt, a_libFolder.clone())?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") }))?;
            txt = Tpl::writeText(txt, a_libPaths)?;
            txt = Tpl::writeText(txt, l_msysPathEntries)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING_LIST { strList: metamodelica::list![literal!(";%PATH%\n"), literal!("REM ::export PATH=")], lastHasNewLine: false }))?;
            txt = Tpl::writeText(txt, a_libFolder)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_LINE { line: literal!(":$PATH REPLACE C: with /C/\n") }))?;
            txt = Tpl::writeStr(txt, a_preRunCommandWindows.clone())?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("OMCppOSUSimulation.exe ") }))?;
            txt = Tpl::writeText(txt, a_execParameters)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_zermMQParams)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" ") }))?;
            txt = Tpl::writeText(txt, a_outputParameter)?;
            txt = Tpl::softNewLine(txt)?;
            txt = Tpl::writeTok(txt, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("endlocal") }))?;
            Ok(txt)
        }
        (_, _, _, _) => {
            let mut txt = in_txt;
            Ok(txt)
        }
        _ => Err("fun_60: no case matched"),
    } }
}

pub fn simulationOMSUCPPMainRunScript(
    mut in_txt: Tpl::Text,
    in_a_simCode: &metamodelica::Ref<SimCode::SimCode>,
    mut in_a_extraFuncs: Tpl::Text,
    mut in_a_extraFuncsDecl: Tpl::Text,
    mut in_a_extraFuncsNamespace: Tpl::Text,
    in_a_preRunCommandLinux: &ArcStr,
    in_a_preRunCommandWindows: &ArcStr,
    in_a_execCommandLinux: &ArcStr,
) -> Result<(Tpl::Text, Tpl::Text, Tpl::Text, Tpl::Text)> {
    ::match_deref::match_deref! { match (in_a_simCode, in_a_preRunCommandLinux, in_a_preRunCommandWindows, in_a_execCommandLinux) {
        (i_simCode @ Deref @ SimCode::SimCode { modelInfo: SimCode::ModelInfo { name: i_modelInfo_name, .. }, makefileParams: SimCodeFunction::MakefileParams { compileDir: i_makefileParams_compileDir, omhome: i_makefileParams_omhome, platform: i_makefileParams_platform, libPaths: i_makefileParams_libPaths, .. }, simulationSettingsOpt: Some(SimCode::SimulationSettings { startTime: i_settings_startTime, stopTime: i_settings_stopTime, stepSize: i_settings_stepSize, numberOfIntervals: i_settings_numberOfIntervals, tolerance: i_settings_tolerance, method: i_settings_method, outputFormat: i_settings_outputFormat, .. }), fileNamePrefix: i_fileNamePrefix, .. }, a_preRunCommandLinux, a_preRunCommandWindows, a_execCommandLinux) => {
            let mut txt = in_txt;
            let mut a_extraFuncs = in_a_extraFuncs;
            let mut a_extraFuncsDecl = in_a_extraFuncsDecl;
            let mut a_extraFuncsNamespace = in_a_extraFuncsNamespace;
            let mut l_start;
            let mut l_end;
            let mut l_stepsize;
            let mut l_intervals;
            let mut l_tol;
            let mut l_solver;
            let mut l_moLib;
            let mut l_home;
            let mut l_outputformat;
            let mut l_modelName;
            let mut l_fileNamePrefixx;
            let mut l_platformstr;
            let mut l_execParameters;
            let mut ret_13;
            let mut ret_14;
            let mut ret_16;
            let mut l_outputParameter;
            let mut ret_18;
            let mut l_libFolder;
            let mut ret_20;
            let mut l_binFolder;
            let mut l_libPaths;
            let mut ret_23;
            let mut l_zermMQParams;
            l_start = Tpl::writeStr((*Tpl::emptyTxt).clone(), realString(*i_settings_startTime))?;
            l_end = Tpl::writeStr((*Tpl::emptyTxt).clone(), realString(*i_settings_stopTime))?;
            l_stepsize = Tpl::writeStr((*Tpl::emptyTxt).clone(), realString(*i_settings_stepSize))?;
            l_intervals = Tpl::writeStr((*Tpl::emptyTxt).clone(), intString(*i_settings_numberOfIntervals))?;
            l_tol = Tpl::writeStr((*Tpl::emptyTxt).clone(), realString(*i_settings_tolerance))?;
            l_solver = fun_51((*Tpl::emptyTxt).clone(), i_simCode, i_settings_method)?;
            l_moLib = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_makefileParams_compileDir.clone())?;
            l_home = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_makefileParams_omhome.clone())?;
            l_outputformat = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_settings_outputFormat.clone())?;
            l_modelName = CodegenUtil::dotPath((*Tpl::emptyTxt).clone(), i_modelInfo_name)?;
            l_fileNamePrefixx = Tpl::writeStr((*Tpl::emptyTxt).clone(), i_fileNamePrefix.clone())?;
            l_platformstr = fun_52((*Tpl::emptyTxt).clone(), i_makefileParams_platform)?;
            l_execParameters = Tpl::writeTok((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!("-S ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_start)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -E ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_end)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -H ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_stepsize)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -G ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_intervals)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -P ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_outputformat)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -T ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_tol)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -I ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_solver)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -R ") }))?;
            ret_13 = Config::simulationCodeTarget()?;
            (l_execParameters, a_extraFuncs, a_extraFuncsDecl, a_extraFuncsNamespace) = CodegenCppOMSI::simulationLibDir(l_execParameters, &ret_13, i_simCode, a_extraFuncs, a_extraFuncsDecl, a_extraFuncsNamespace)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -M ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_moLib.clone())?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -r ") }))?;
            ret_14 = Testsuite::isRunning()?;
            (l_execParameters, a_extraFuncs, a_extraFuncsDecl, a_extraFuncsNamespace) = CodegenCppOMSI::simulationResults(l_execParameters, ret_14, i_simCode, a_extraFuncs, a_extraFuncsDecl, a_extraFuncsNamespace)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -a ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_moLib)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(" -o ") }))?;
            l_execParameters = Tpl::writeText(l_execParameters, l_fileNamePrefixx)?;
            l_execParameters = Tpl::writeTok(l_execParameters, metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(".fmu") }))?;
            ret_16 = stringEq(i_settings_outputFormat, &literal!("empty"));
            l_outputParameter = fun_53((*Tpl::emptyTxt).clone(), ret_16)?;
            ret_18 = Config::simulationCodeTarget()?;
            (l_libFolder, a_extraFuncs, a_extraFuncsDecl, a_extraFuncsNamespace) = CodegenCppOMSI::simulationLibDir((*Tpl::emptyTxt).clone(), &ret_18, i_simCode, a_extraFuncs, a_extraFuncsDecl, a_extraFuncsNamespace)?;
            ret_20 = Config::simulationCodeTarget()?;
            l_binFolder = CodegenCppOMSI::simulationBinDir((*Tpl::emptyTxt).clone(), &ret_20, i_simCode)?;
            l_libPaths = Tpl::pushIter((*Tpl::emptyTxt).clone(), metamodelica::Ref::new(Tpl::IterOptions { startIndex0: 0, empty: None, separator: Some(metamodelica::Ref::new(Tpl::StringToken::ST_STRING { value: literal!(";") })), alignNum: 0, alignOfset: 0, alignSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE), wrapWidth: 0, wrapSeparator: metamodelica::Ref::new(Tpl::StringToken::ST_NEW_LINE) }))?;
            l_libPaths = lm_54(l_libPaths, i_makefileParams_libPaths)?;
            l_libPaths = Tpl::popIter(l_libPaths)?;
            ret_23 = Flags::getConfigBool(Flags::USE_ZEROMQ_IN_SIM.clone())?;
            l_zermMQParams = fun_55((*Tpl::emptyTxt).clone(), ret_23)?;
            txt = fun_60(txt, i_makefileParams_platform, a_preRunCommandWindows, l_libPaths, l_libFolder, l_home, l_outputParameter, l_zermMQParams, l_execParameters, l_binFolder, a_execCommandLinux, a_preRunCommandLinux)?;
            Ok((txt, a_extraFuncs, a_extraFuncsDecl, a_extraFuncsNamespace))
        }
        (_, _, _, _) => {
            let mut txt = in_txt;
            let mut a_extraFuncs = in_a_extraFuncs;
            let mut a_extraFuncsDecl = in_a_extraFuncsDecl;
            let mut a_extraFuncsNamespace = in_a_extraFuncsNamespace;
            Ok((txt, a_extraFuncs, a_extraFuncsDecl, a_extraFuncsNamespace))
        }
        _ => Err("simulationOMSUCPPMainRunScript: no case matched"),
    } }
}
